SELECT 
	A.PEDIDO_COMPRA   AS pedido_compra,
	SUBSTRING(A.REFERENCIA, PATINDEX('%[^0]%', A.REFERENCIA+'.'), LEN(A.REFERENCIA)) AS referencia,
	A.PRODUTO         AS produto,
	A.CODIGO_BARRAS   AS ean,
	A.QUANTIDADE      AS quantidade,
	A.UNIDADE_MEDIDA  AS unidade_medida,
	A.OPERACAO_FISCAL AS operacao_fiscal,
	A.VALOR_UNITARIO  AS valor_unitario,
	A.TIPO_DESCONTO   AS tipo_desconto,
	A.DESCONTO        AS desconto,
	A.PRECO_FABRICA   AS preco_fabrica,
	A.PRECO_VENDA     AS preco_venda,
	A.PRECO_MAXIMO    AS preco_maximo,
	A.VALOR_REPASSE   AS valor_repasse,

	CASE WHEN  MAX ( B.SALDO ) > 0 
			THEN 'PENDENTE'                           
			ELSE 'ENCERRADO'
	END                            AS estado
FROM PEDIDOS_COMPRAS_PRODUTOS A WITH(NOLOCK)
LEFT JOIN PEDIDOS_COMPRAS_PRODUTOS_SALDO B WITH(NOLOCK) ON B.PEDIDO_COMPRA_PRODUTO = A.PEDIDO_COMPRA_PRODUTO
LEFT JOIN PEDIDOS_COMPRAS					C WITH(NOLOCK) ON C.PEDIDO_COMPRA = A.PEDIDO_COMPRA
GROUP BY
	A.PEDIDO_COMPRA,
	A.REFERENCIA, 
	A.PRODUTO,
	A.CODIGO_BARRAS,
	A.QUANTIDADE,
	A.UNIDADE_MEDIDA,
	A.OPERACAO_FISCAL,
	A.VALOR_UNITARIO,
	A.TIPO_DESCONTO,
	A.DESCONTO,
	A.PRECO_FABRICA,
	A.PRECO_VENDA,
	A.PRECO_MAXIMO,
	A.VALOR_REPASSE