SELECT
	A.CONFIGURACAO_OL AS apontador,
	A.PRODUTO AS produto,
	A.DESCONTO_TOTAL AS desconto_total,
	A.DESCONTO_DISTRIBUIDORA AS desconto_distribuidora,
	A.DESCONTO_FABRICANTE AS desconto_industria
FROM
	CONFIGURACOES_OL_PRODUTOS A

UNION ALL

SELECT
	A.CONFIGURACAO_OL AS apontador,
	B.PRODUTO AS produto,
	A.DESCONTO_TOTAL AS desconto_total,
	A.DESCONTO_DISTRIBUIDORA AS desconto_distribuidora,
	A.DESCONTO_FABRICANTE AS desconto_industria
FROM
	CONFIGURACOES_OL_MARCAS A
	INNER JOIN PRODUTOS B ON B.MARCA = A.MARCA