WITH TEMP_PEDIDOS_VENDAS AS (
SELECT
	A.PEDIDO_VENDA_VALIDACAO                      AS pedido_venda_validacao,
    A.PEDIDO_VENDA                                AS pedido_venda,
    MAX(M.NF_NUMERO)                              AS nf_numero,
    ISNULL(A.EMPRESA_CROSSDOCKING, A.EMPRESA)     AS empresa,
    A.DATA_HORA                                   AS data_hora,
	SF.DATA_HORA								  AS data_hora_lib,
    A.ENTIDADE                                    AS entidade,
    A.VENDEDOR                                    AS vendedor,
    --UPPER(I.NOME)                                 AS vendedor_nome,
    null                                          AS vendedor_nome,
    E.DONO                                        AS dono,
    --UPPER(J.NOME)                                 AS dono_nome,
    null                                          AS dono_nome,
    A.CONDICAO_COMERCIAL                          AS condicao_comercial,
    C.DESCRICAO                                   AS condicao_comercial_descricao,
    C.CODIGO_CONDICAO_COMERCIAL                   AS codigo_condicao_comercial,
    A.ORIGEM_VENDA_CANAL                          AS origem_venda_canal,
    D.DESCRICAO                                   AS origem_venda_canal_descricao,
    H.DESCRICAO                                   AS status_pedidos_vendas,
    A.CONFIGURACAO_OL                             AS configuracao_ol,
    CAST(SUM(F.QUANTIDADE_ATENDIDA) AS NUMERIC(15,2))                    AS quantidade_atendida,
    CAST(SUM(F.QUANTIDADE_DIGITADA) AS NUMERIC(15,2))                    AS quantidade_digitada,
    CAST(SUM(F.QUANTIDADE_ATENDIDA * F.VALOR_UNITARIO) AS NUMERIC(15,2)) AS valor_atendido,
    CAST(SUM(F.TOTAL_PRODUTO) AS NUMERIC(15,2))                          AS valor_digitado,
    A.CONDICAO_PAGAMENTO						  AS condicao_pagamento
FROM      PEDIDOS_VENDAS_VALIDACOES          A WITH(NOLOCK)
JOIN      PEDIDOS_VENDAS_VALIDACOES_PRODUTOS F WITH(NOLOCK) ON F.PEDIDO_VENDA_VALIDACAO = A.PEDIDO_VENDA_VALIDACAO
JOIN      ORIGENS_VENDAS_CANAIS              D WITH(NOLOCK) ON D.ORIGEM_VENDA_CANAL     = A.ORIGEM_VENDA_CANAL
JOIN      VENDEDORES                         I WITH(NOLOCK) ON I.VENDEDOR               = A.VENDEDOR
JOIN      ENTIDADES                          K WITH(NOLOCK) ON K.ENTIDADE               = A.ENTIDADE
JOIN      PEDIDOS_VENDAS_VALIDACOES_STATUS   L WITH(NOLOCK) ON L.PEDIDO_VENDA_VALIDACAO = A.PEDIDO_VENDA_VALIDACAO
LEFT JOIN NF_FATURAMENTO                     M WITH(NOLOCK) ON M.PEDIDO_VENDA           = A.PEDIDO_VENDA
LEFT JOIN PEDIDOS_VENDAS                     E WITH(NOLOCK) ON E.PEDIDO_VENDA_VALIDACAO = A.PEDIDO_VENDA_VALIDACAO
LEFT JOIN VENDEDORES                         J WITH(NOLOCK) ON J.VENDEDOR               = E.DONO
LEFT JOIN PEDIDOS_VENDAS_STATUS              G WITH(NOLOCK) ON G.PEDIDO_VENDA           = A.PEDIDO_VENDA
LEFT JOIN STATUS_PEDIDOS_VENDAS              H WITH(NOLOCK) ON H.STATUS_PEDIDO_VENDA    = ISNULL(G.STATUS_PEDIDO_VENDA, L.STATUS_PEDIDO_VENDA)
LEFT JOIN CONDICOES_PAGAMENTO                B WITH(NOLOCK) ON B.CONDICAO_PAGAMENTO     = A.CONDICAO_PAGAMENTO
LEFT JOIN CONDICOES_COMERCIAIS               C WITH(NOLOCK) ON C.CONDICAO_COMERCIAL     = A.CONDICAO_COMERCIAL
LEFT JOIN SOLICITACOES_FATURAMENTOS			SF WITH(NOLOCK) ON SF.PEDIDO_VENDA			= E.PEDIDO_VENDA
    WHERE CAST(A.DATA_HORA AS DATE) = 'REPLACE_START_DATE'
    -- WHERE A.DATA_HORA BETWEEN CAST(GETDATE() - 10 AS DATE) AND CAST(GETDATE() + 1 AS DATE)
    GROUP BY A.PEDIDO_VENDA_VALIDACAO, A.PEDIDO_VENDA, ISNULL(A.EMPRESA_CROSSDOCKING, A.EMPRESA), A.DATA_HORA, A.ENTIDADE, A.VENDEDOR, UPPER(I.NOME), E.DONO, UPPER(J.NOME), A.CONDICAO_COMERCIAL, C.DESCRICAO, C.CODIGO_CONDICAO_COMERCIAL, A.ORIGEM_VENDA_CANAL, D.DESCRICAO, H.DESCRICAO, A.CONFIGURACAO_OL, A.CONDICAO_PAGAMENTO, SF.DATA_HORA
),
PEDIDOS_SALDO_CONF AS (
	SELECT
		A.PEDIDO_VENDA,
		SUM(C.SALDO) AS SALDO_CONF
	FROM 
		TEMP_PEDIDOS_VENDAS           A WITH(NOLOCK)
	JOIN ESTOQUE_TRANSFERENCIAS         B WITH(NOLOCK) ON B.PEDIDO_VENDA = A.PEDIDO_VENDA
	JOIN ESTOQUE_TRANSFERENCIAS_SALDO    C WITH(NOLOCK) ON C.ESTOQUE_TRANSFERENCIA = B.ESTOQUE_TRANSFERENCIA
	--    WHERE C.SALDO > 0
	GROUP BY A.PEDIDO_VENDA
)

SELECT
	A.*,
	ISNULL(B.SALDO_CONF, 0) AS saldo_conf
FROM
	TEMP_PEDIDOS_VENDAS A WITH(NOLOCK)
	LEFT JOIN PEDIDOS_SALDO_CONF B WITH(NOLOCK) ON B.PEDIDO_VENDA = A.PEDIDO_VENDA
