SELECT
    A.RECEBIMENTO AS recebimento,
    A.DATA_HORA AS data_hora,
    A.EMPRESA AS empresa,
    A.FORNECEDOR AS fornecedor,
    CAST(A.MOVIMENTO AS DATE) AS movimento,
    A.CENTRO_ESTOQUE_RECEBIMENTO AS centro_estoque_recebimento,
    A.CENTRO_ESTOQUE_FINAL AS centro_estoque_final,
    A.INTEGRADO AS integrado
FROM
    RECEBIMENTOS_VOLUMES A
WHERE
    A.MOVIMENTO = CAST('REPLACE_START_DATE' AS DATE)
    AND A.EMPRESA IN (SELECT EMPRESA FROM OS_EMPRESAS_CENTROS_ESTOQUES_MAPAS)