SELECT
	A.RESTRICAO_DIVISAO_FABRICANTE_SUPERVISOR AS restricao_divisao_fabricante_supervisor,
	A.RESTRICAO_DIVISAO_FABRICANTE AS restricao_divisao_fabricante,
	A.SUPERVISOR AS supervisor,
	A.TIPO_RESTRICAO AS tipo_restricao,
	A.EMPRESA AS empresa
FROM RESTRICOES_DIVISOES_FABRICANTES_SUPERVISORES AS A