SELECT
	A.RESTRICAO_DIVISAO_FABRICANTE_EMPRESA AS restricao_divisao_fabricante_empresa,
	A.RESTRICAO_DIVISAO_FABRICANTE AS restricao_divisao_fabricante,
	A.EMPRESA AS empresa,
	A.TIPO_RESTRICAO AS tipo_restricao
FROM RESTRICOES_DIVISOES_FABRICANTES_EMPRESAS AS A