select 
    produto_venda,
    produto,
    preco_maximo,
    desconto_maximo,
    desconto_padrao,
    markup,
    preco_venda,
    tipo_bonificacao,
    valor_bonificacao,
    grupo_preco,
    preco_fabrica,
    tipo_comissao,
    comissao,
    ultimo_custo_entrada_validado,
    data_atualizacao_ultimo_custo,
    validacao_custo_preco,
    lucro_bruto,
    taxa_motoboy,
    valor_pmpf,
    lucro_bruto_minimo
from
	produtos_vendas
