SELECT
    fornecedor_desconto_marca,
    formulario_origem,
    tab_master_origem,
    reg_master_origem,
    reg_log_inclusao,
    fornecedor_desconto,
    marca,
    percentual_desconto,
    tipo
FROM
    FORNECEDORES_DESCONTOS_MARCAS
