select
	acordo_comercial
	,descricao
	,data_hora
	,comprador
	,empresa
	,entidade
	,movimento
	,data_inicial
	,data_final
	,status
	,representante
	,tipo_acordo_comercial
	,acordo_comercial_pai
	,valor
	,tipo_promocao_flexivel
	,tabela_encarte
	,tabela_desconto
	,convenio_cartao_promocao
	,almanaque
	,confirmar
	,tipo_data_apuracao
	,pbm
	,pbms_tipo_reembolso
	,data_base_estoque
	,custo
	,sugestao_compra
	,percentual_rebate
	,grupo_economico_conta
	,margem
	,margem_globo
	,custo_operacional_industria
	,custo_operacional_interno
	,desconto_financeiro
	,memoria_rf
	,memoria_rc
	,icms_origem
	,icms_interno
	,base_valor_liquido
	,desconsiderar_vendas_globo
	,desconsiderar_desc_pedidos
	,modalidade_acordo_comercial
	,registro_apuracao
	,premiacao
	,ressarcimento_negativo
	,aplicar_desconto_grade_pedido
from acordos_comerciais ac 
