SET NOCOUNT ON

DECLARE @MES     NUMERIC(2)
DECLARE @ANO     NUMERIC(4)

SET @MES     = MONTH('REPLACE_START_DATE')
SET @ANO     = YEAR('REPLACE_START_DATE')


--SET @MES     =3
--SET @ANO     =2023

-----------------------------------------------------------
-- Gera Tabela Temporária das Empresas do Usuário Logado --
-----------------------------------------------------------
if object_id('tempdb..#TEMP_EMPRESAS_USER') is not null DROP TABLE #TEMP_EMPRESAS_USER

SELECT * INTO #TEMP_EMPRESAS_USER FROM UDF_USUARIO_EMPRESAS('ADMIN')
-----------------------------------------------------------
                       
--------------------------------------      
--PEGA OS PEDIDOS
--------------------------------------
                      
if object_id('tempdb..#TEMP_PEDIDOS') is not null DROP TABLE #TEMP_PEDIDOS

SELECT DISTINCT
       MONTH(B.DATA_HORA)    AS MES,
       YEAR (B.DATA_HORA)    AS ANO,
       B.PEDIDO_COMPRA
                            
  INTO #TEMP_PEDIDOS                                                                                      

  FROM PEDIDOS_COMPRAS                B WITH(NOLOCK)
  JOIN TIPOS_PEDIDOS_COMPRA          ZZ WITH(NOLOCK) ON ZZ.TIPO_PEDIDO_COMPRA   = B.TIPO_PEDIDO_COMPRA
                                                    AND ZZ.CONSOME_ORCAMENTO    = 'S'

  JOIN #TEMP_EMPRESAS_USER            V              ON V.EMPRESA_USUARIA       = B.EMPRESA
  JOIN PEDIDOS_COMPRAS_PRODUTOS       C WITH(NOLOCK) ON C.PEDIDO_COMPRA         = B.PEDIDO_COMPRA
  JOIN OPERACOES_FISCAIS              F WITH(NOLOCK) ON F.OPERACAO_FISCAL       = C.OPERACAO_FISCAL
                                                    AND F.TIPO_OPERACAO         = 1 --COMPRAS
WHERE 1 = 1
  AND MONTH(B.DATA_HORA) = @MES
  AND YEAR (B.DATA_HORA) = @ANO


--------------------------------------
--PEGA AS NF_COMPRAS DE PEDIDOS
--------------------------------------

if object_id('tempdb..#TEMP_NF_COMPRA_PEDIDOS') is not null DROP TABLE #TEMP_NF_COMPRA_PEDIDOS

SELECT DISTINCT A.NF_COMPRA

   INTO #TEMP_NF_COMPRA_PEDIDOS

  FROM NF_COMPRA           A WITH(NOLOCK)
  JOIN #TEMP_EMPRESAS_USER V              ON V.EMPRESA_USUARIA = A.EMPRESA
  JOIN #TEMP_PEDIDOS       C WITH(NOLOCK) ON C.PEDIDO_COMPRA = A.PEDIDO_COMPRA



--------------------------------------
--PEGA AS METAS--
--------------------------------------
-- 1111111111111
if object_id('tempdb..#TEMP_METAS') is not null DROP TABLE #TEMP_METAS

SELECT DISTINCT A.MES,
       A.ANO,
       --B.FORNECEDOR AS ENTIDADE,
       A.COMPRADOR,
       A.GRUPO_COMPRA,
       A.VALOR_ORCAMENTO,
       A.VALOR_LIMITE_EXTRA,
       A.TOTAL_ORCAMENTO

   INTO #TEMP_METAS

  FROM VW_ORCAMENTOS_COMPRAS_GRUPOS_COMPRAS A WITH(NOLOCK)
  JOIN GRUPOS_COMPRAS                       B WITH(NOLOCK) ON B.GRUPO_COMPRA = A.GRUPO_COMPRA
     WHERE A.MES = @MES
       AND A.ANO = @ANO

--------------------------------------
--PEGA AS COMPRAS--
--------------------------------------
-- 222222222222
if object_id('tempdb..#TEMP_COMPRAS') is not null DROP TABLE #TEMP_COMPRAS

SELECT X.MES                 AS MES,
       X.ANO                 AS ANO,
       --B.ENTIDADE,       
       ISNULL(I.COMPRADOR,1) AS COMPRADOR,
       ISNULL(I.GRUPO_COMPRA,0) AS GRUPO_COMPRA,
       SUM(D.SALDO_ORCAMENTO * C.PRECO_FABRICA ) AS TOTAL_COMPRA_PEDIDOS_ORIGINAL,
       SUM(D.RECEBIMENTO     * C.PRECO_FABRICA ) AS TOTAL_COMPRA_PEDIDOS_CONSUMO,
       SUM(D.SALDO           * C.PRECO_FABRICA ) AS TOTAL_COMPRA_PEDIDOS

  INTO #TEMP_COMPRAS

  FROM PEDIDOS_COMPRAS                B WITH(NOLOCK)
  JOIN #TEMP_PEDIDOS                  X WITH(NOLOCK) ON X.PEDIDO_COMPRA         = B.PEDIDO_COMPRA
  JOIN PEDIDOS_COMPRAS_PRODUTOS       C WITH(NOLOCK) ON C.PEDIDO_COMPRA         = B.PEDIDO_COMPRA
  JOIN PEDIDOS_COMPRAS_PRODUTOS_SALDO D WITH(NOLOCK) ON D.PEDIDO_COMPRA_PRODUTO = C.PEDIDO_COMPRA_PRODUTO
  JOIN PRODUTOS                       E WITH(NOLOCK) ON E.PRODUTO               = C.PRODUTO
  LEFT JOIN PRODUTOS_COMPRADORES      I WITH(NOLOCK) ON I.PRODUTO               = C.PRODUTO  

WHERE 1 = 1
  AND ISNULL(C.QUANTIDADE_ESTOQUE,0) > 0
  AND C.QUANTIDADE_EMBALAGEM >= 1

GROUP BY X.MES,
         X.ANO,
         --B.ENTIDADE,
         ISNULL(I.COMPRADOR,1),
         ISNULL(I.GRUPO_COMPRA,0)


------------------------------------------------
----PEGA AS ENTRADAS DOS PEDIDOS DO COMPRADOR--
------------------------------------------------
-- 3333333
if object_id('tempdb..#TEMP_ENTRADAS_PEDIDOS') is not null DROP TABLE #TEMP_ENTRADAS_PEDIDOS


SELECT @MES AS MES,
       @ANO AS ANO,
       ISNULL(C.COMPRADOR,1) AS COMPRADOR,
       ISNULL(C.GRUPO_COMPRA,0) AS GRUPO_COMPRA,
       SUM(A.TOTAL_COMPRA_PRECO_FABRICA) AS TOTAL_COMPRAS

  INTO #TEMP_ENTRADAS_PEDIDOS

  FROM COMPRAS_ANALITICAS       A WITH(NOLOCK)
  JOIN NF_COMPRA                X WITH(NOLOCK) ON X.NF_COMPRA = A.NF_COMPRA
  JOIN #TEMP_NF_COMPRA_PEDIDOS  Y WITH(NOLOCK) ON Y.NF_COMPRA = A.NF_COMPRA
  JOIN PRODUTOS                 B WITH(NOLOCK) ON B.PRODUTO   = A.PRODUTO
LEFT JOIN PRODUTOS_COMPRADORES  C WITH(NOLOCK) ON C.PRODUTO = A.PRODUTO

GROUP BY A.MES,
         A.ANO,
         --X.ENTIDADE,
         ISNULL(C.COMPRADOR,1),
         ISNULL(C.GRUPO_COMPRA,0)

HAVING SUM(A.TOTAL_COMPRA_PRECO_FABRICA) > 0 


--------------------------------------
--RESULTADO--
--------------------------------------

if object_id('tempdb..#TEMP_RESULTADO') is not null DROP TABLE #TEMP_RESULTADO

SELECT X.MES,
       X.ANO,
       X.COMPRADOR,
       X.GRUPO_COMPRA,
       SUM(X.VALOR_ORCAMENTO)              AS VALOR_ORCAMENTO,
       SUM(X.VALOR_LIMITE_EXTRA)           AS VALOR_LIMITE_EXTRA,
       SUM(X.TOTAL_ORCAMENTO)              AS TOTAL_ORCAMENTO,
       SUM(X.TOTAL_COMPRA_PEDIDOS_ORIGINAL)                AS TOTAL_COMPRA_PEDIDOS_ORIGINAL,
       SUM(X.TOTAL_COMPRAS)                AS TOTAL_COMPRAS,
       SUM(X.TOTAL_ENTRADA_PEDIDOS)        AS TOTAL_ENTRADA_PEDIDOS,
       SUM(X.TOTAL_ENTRADA_OUTROS_PEDIDOS) AS TOTAL_ENTRADA_OUTROS_PEDIDOS,

       CASE WHEN SUM(X.TOTAL_ORCAMENTO) > 0
            THEN ( SUM(X.TOTAL_COMPRA_PEDIDOS_ORIGINAL )  / SUM(X.TOTAL_ORCAMENTO) ) * 100.00
            ELSE CASE WHEN SUM(X.TOTAL_COMPRA_PEDIDOS_ORIGINAL)  > 0
                      THEN -100
                      ELSE 0
                 END
       END                                 AS P_META,

       SUM(X.VALOR_ORCAMENTO) -
       SUM(X.TOTAL_COMPRA_PEDIDOS_ORIGINAL ) AS SALDO_COMPRAS_ORIGINAL,

       SUM(X.TOTAL_ORCAMENTO) -
       SUM(X.TOTAL_COMPRA_PEDIDOS_ORIGINAL ) AS SALDO_COMPRAS,

       SUM(X.TOTAL_ENTRADA_PEDIDOS)        +
       SUM(X.TOTAL_ENTRADA_OUTROS_PEDIDOS) AS TOTAL_ENTRADA_GERAL,

       IDENTITY ( INT , 1 , 1 )                               AS ID


  INTO #TEMP_RESULTADO


  FROM (

SELECT A.MES,
       A.ANO,
       A.COMPRADOR,
       A.GRUPO_COMPRA,
       A.VALOR_ORCAMENTO,
       A.VALOR_LIMITE_EXTRA,
       A.TOTAL_ORCAMENTO,
       0 AS TOTAL_COMPRA_PEDIDOS_ORIGINAL,
       0 AS TOTAL_COMPRAS,
       0 AS TOTAL_ENTRADA_PEDIDOS,
       0 AS TOTAL_ENTRADA_OUTROS_PEDIDOS

  FROM #TEMP_METAS A WITH(NOLOCK)

  UNION ALL

SELECT A.MES,
       A.ANO,
       A.COMPRADOR,
       A.GRUPO_COMPRA,
       0 AS VALOR_ORCAMENTO,
       0 AS VALOR_LIMITE_EXTRA,
       0 AS TOTAL_ORCAMENTO,
       A.TOTAL_COMPRA_PEDIDOS_ORIGINAL ,
       A.TOTAL_COMPRA_PEDIDOS  AS TOTAL_COMPRAS,
       0 AS TOTAL_ENTRADA_PEDIDOS,
       0 AS TOTAL_ENTRADA_OUTROS_PEDIDOS

  FROM #TEMP_COMPRAS A WITH(NOLOCK)


  UNION ALL

SELECT A.MES,
       A.ANO,
       A.COMPRADOR,
       A.GRUPO_COMPRA,
       0 AS VALOR_ORCAMENTO,
       0 AS VALOR_LIMITE_EXTRA,
       0 AS TOTAL_ORCAMENTO,
       0 AS TOTAL_COMPRA_PEDIDOS_ORIGINAL,
       0 AS TOTAL_COMPRAS,
       A.TOTAL_COMPRAS AS TOTAL_ENTRADA_PEDIDOS,
       0 AS TOTAL_ENTRADA_OUTROS_PEDIDOS

  FROM #TEMP_ENTRADAS_PEDIDOS A WITH(NOLOCK)


) X


GROUP BY X.MES,
         X.ANO,
         X.COMPRADOR,
         X.GRUPO_COMPRA

ORDER BY COMPRADOR


SELECT A.ID,
       A.MES,
       A.ANO,
       A.COMPRADOR,
       ISNULL(C.NOME, 'ND') AS COMPRADOR_NOME,
       A.GRUPO_COMPRA,
       B.DESCRICAO          AS GRUPO_COMPRA_DESCRICAO,
       A.VALOR_ORCAMENTO,
       A.VALOR_LIMITE_EXTRA,
       A.TOTAL_ORCAMENTO,
       A.TOTAL_COMPRA_PEDIDOS_ORIGINAL,
       A.TOTAL_COMPRAS,
       A.TOTAL_ENTRADA_PEDIDOS,
       A.TOTAL_ENTRADA_OUTROS_PEDIDOS,
       A.P_META,
       A.SALDO_COMPRAS_ORIGINAL,
       A.SALDO_COMPRAS,
       A.TOTAL_ENTRADA_GERAL

  FROM #TEMP_RESULTADO A WITH(NOLOCK)
  JOIN GRUPOS_COMPRAS  B WITH(NOLOCK) ON B.GRUPO_COMPRA = A.GRUPO_COMPRA
  LEFT JOIN COMPRADORES C WITH(NOLOCK) ON C.COMPRADOR = A.COMPRADOR
  
ORDER BY ID

