SELECT A.PEDIDO_VENDA_VALIDACAO,
       A.PEDIDO_VENDA,
       A.DATA_HORA,
       ISNULL(I.DESCRICAO, 'EM PROCESSAMENTO') AS STATUS,
       N.DESCRICAO AS ORIGEM_VENDA_CANAL,
       ISNULL(SUM(J.TOTAL_PRODUTO), 0) AS TOTAL_PEDIDO,
       (SELECT A2.TOTAL_GERAL
            FROM NF_FATURAMENTO A1
            JOIN NF_FATURAMENTO_TOTAIS A2 ON A2.NF_FATURAMENTO = A1.NF_FATURAMENTO
                WHERE A1.PEDIDO_VENDA = A.PEDIDO_VENDA) AS TOTAL_NF,
       A.EMPRESA,
       A.VENDEDOR,
       B.NOME AS VENDEDOR_DESCRICAO,
       A.ENTIDADE,
       C.NOME AS RAZAO_SOCIAL,
       C.NOME_FANTASIA,
       C.INSCRICAO_FEDERAL,
       P.ESTADO,
       A.CONDICAO_COMERCIAL,
       D.DESCRICAO AS CONDICAO_COMERCIAL_DESCRICAO,
       A.CONFIGURACAO_OL,
       E.DESCRICAO AS CONFIGURACAO_OL_DESCRICAO,
       A.GRUPO_CLIENTE,
       F.DESCRICAO AS GRUPO_CLIENTE_DESCRICAO,
       A.CLIENTE_REDE,
       G.DESCRICAO AS CLIENTE_REDE_DESCRICAO,
       L.MARCA AS MARCA,
       L.DESCRICAO AS MARCA_DESCRICAO,
       (SELECT TOP 1 B1.DESCRICAO
            FROM FABRICANTES_PRODUTOS B1
            JOIN FABRICANTES_PRODUTOS_MARCAS B2 ON B2.FABRICANTE_PRODUTO = B1.FABRICANTE_PRODUTO
                WHERE B2.MARCA = L.MARCA) AS FABRICANTE,
       O.DESCRICAO AS CATEGORIA
    FROM PEDIDOS_VENDAS_VALIDACOES               A WITH(NOLOCK)
    JOIN VENDEDORES                              B WITH(NOLOCK) ON B.VENDEDOR               = A.VENDEDOR
    JOIN ENTIDADES                               C WITH(NOLOCK) ON C.ENTIDADE               = A.ENTIDADE
    JOIN ENDERECOS                               P WITH(NOLOCK) ON P.ENTIDADE               = A.ENTIDADE
    JOIN CONDICOES_COMERCIAIS                    D WITH(NOLOCK) ON D.CONDICAO_COMERCIAL     = A.CONDICAO_COMERCIAL
    JOIN CONFIGURACOES_OL                        E WITH(NOLOCK) ON E.CONFIGURACAO_OL        = A.CONFIGURACAO_OL
    JOIN GRUPOS_CLIENTES                         F WITH(NOLOCK) ON F.GRUPO_CLIENTE          = A.GRUPO_CLIENTE
    JOIN CLIENTES_REDES                          G WITH(NOLOCK) ON G.CLIENTE_REDE           = A.CLIENTE_REDE
    JOIN Clientes_MegaFeira_Naz                  M WITH(NOLOCK) ON M.CodCli                 = A.ENTIDADE
    JOIN ORIGENS_VENDAS_CANAIS                   N WITH(NOLOCK) ON N.ORIGEM_VENDA_CANAL     = A.ORIGEM_VENDA_CANAL
    LEFT JOIN PEDIDOS_VENDAS_STATUS              H WITH(NOLOCK) ON H.PEDIDO_VENDA           = A.PEDIDO_VENDA
    LEFT JOIN STATUS_PEDIDOS_VENDAS              I WITH(NOLOCK) ON I.STATUS_PEDIDO_VENDA    = H.STATUS_PEDIDO_VENDA
    LEFT JOIN PEDIDOS_VENDAS_VALIDACOES_PRODUTOS J WITH(NOLOCK) ON J.PEDIDO_VENDA_VALIDACAO = A.PEDIDO_VENDA_VALIDACAO
    LEFT JOIN PRODUTOS                           K WITH(NOLOCK) ON K.PRODUTO                = J.PRODUTO
    LEFT JOIN MARCAS                             L WITH(NOLOCK) ON L.MARCA                  = K.MARCA
    LEFT JOIN CATEGORIAS_PRODUTOS                O WITH(NOLOCK) ON O.CATEGORIA_PRODUTO      = K.CATEGORIA_PRODUTO
        WHERE A.DATA_HORA BETWEEN CONVERT(varchar, CONVERT(date, '2025-07-21'), 103) AND CONVERT(varchar, CONVERT(date, '2025-07-31'), 103)
          AND M.MesAno = '072025'
        GROUP BY A.PEDIDO_VENDA_VALIDACAO,
                 A.PEDIDO_VENDA,
                 I.DESCRICAO,
                 A.EMPRESA,
                 A.VENDEDOR,
                 B.NOME,
                 A.ENTIDADE,
                 C.NOME,
                 C.NOME_FANTASIA,
                 A.CONDICAO_COMERCIAL,
                 D.DESCRICAO,
                 A.CONFIGURACAO_OL,
                 E.DESCRICAO,
                 A.GRUPO_CLIENTE,
                 F.DESCRICAO,
                 A.CLIENTE_REDE,
                 G.DESCRICAO,
                 L.MARCA,
                 L.DESCRICAO,
                 N.DESCRICAO,
                 A.DATA_HORA,
                 C.INSCRICAO_FEDERAL,
                 O.DESCRICAO,
                 P.ESTADO
