SET NOCOUNT ON

SELECT
	A.CONFIGURACAO_OL_MARCA
	,A.CONFIGURACAO_OL
	,A.MARCA
	,A.CONTADOR_F9
	,A.DESCONTO_TOTAL
	,A.DESCONTO_DISTRIBUIDORA
	,A.DESCONTO_FABRICANTE
	,A.CASHBACK_PONTUACAO
	,A.CASHBACK_RESGATE
	,A.DESCONTO_FABRICANTE_01
	,A.DESCONTO_FABRICANTE_02
	,A.DESCONTO_FABRICANTE_03
	,A.DESCONTO_FABRICANTE_04
	,A.DESCONTO_FABRICANTE_05
FROM
  CONFIGURACOES_OL_MARCAS A
