SET NOCOUNT ON;

WITH T1 AS (
	SELECT
		D.NF_FATURAMENTO_BOLETO AS venda_boleto,
		D.NF_FATURAMENTO AS registro_procfit,
		D.DIAS AS dias,
		D.VENCIMENTO AS vencimento,
		D.PERCENTUAL AS percentual,
		D.VALOR AS valor,
		D.TITULO AS titulo
	FROM
	NF_FATURAMENTO					A
	LEFT JOIN TITULOS_RECEBER		B ON	B.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM AND
									B.REG_MASTER_ORIGEM = A.REG_MASTER_ORIGEM AND
									B.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM AND
									B.EMPRESA = A.EMPRESA
	LEFT JOIN TITULOS_RECEBER_SALDO C ON C.TITULO_RECEBER = B.TITULO_RECEBER
	JOIN NF_FATURAMENTO_BOLETOS	D ON D.NF_FATURAMENTO = A.NF_FATURAMENTO
	WHERE 
		C.SITUACAO_TITULO = 1 
		AND A.EMPRESA IN (2, 3, 4, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19)
)

SELECT DISTINCT * FROM T1

