SELECT
	D.NF_FATURAMENTO_PARCELA AS venda_parcela,
	D.NF_FATURAMENTO AS registro_procfit,
	D.DIAS AS dias,
	D.VENCIMENTO AS vencimento,
	D.PERCENTUAL AS percentual,
	D.VALOR AS valor,
	D.TITULO AS titulo
FROM
NF_FATURAMENTO					A
LEFT JOIN TITULOS_RECEBER		B ON	B.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM AND
								B.REG_MASTER_ORIGEM = A.REG_MASTER_ORIGEM AND
								B.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM AND
								B.EMPRESA = A.EMPRESA
LEFT JOIN TITULOS_RECEBER_SALDO C ON C.TITULO_RECEBER = B.TITULO_RECEBER
JOIN NF_FATURAMENTO_PARCELAS	D ON D.NF_FATURAMENTO = A.NF_FATURAMENTO
WHERE C.SITUACAO_TITULO = 1