SET NOCOUNT ON;

DECLARE @EMPRESA                    NUMERIC(15)                          
DECLARE @EMBARQUE_INI                DATE
DECLARE @EMBARQUE_FIM                DATE
DECLARE @BIPAGEM_INI                DATETIME
DECLARE @BIPAGEM_FIM                DATETIME
DECLARE @TRANSPORTADORA                NUMERIC(15) 
DECLARE @ROTA                        NUMERIC(15)
DECLARE @CONTRATO                    NUMERIC(15)
DECLARE @ID_AUTORIZACAO_PAGAMENTO    NUMERIC(15)  
DECLARE @STATUS                        NUMERIC(1) -- 1-TODOS / 2-AUTORIZADOS / 3-NÃO AUTORIZADOS
DECLARE @ROMANEIO                    NUMERIC(15)

          
SET @EMPRESA             = NULL
SET @EMBARQUE_INI        = 'REPLACE_START_DATE'
SET @EMBARQUE_FIM        = 'REPLACE_END_DATE'
SET @BIPAGEM_INI        = NULL
SET @BIPAGEM_FIM        = NULL
SET @TRANSPORTADORA       = NULL
SET @ROTA       = NULL
SET @CONTRATO       = NULL
SET @ID_AUTORIZACAO_PAGAMENTO       = NULL
SET @STATUS       = 1
SET @ROMANEIO    = NULL

/*                                                                                       
IF @EMBARQUE_INI IS NOT NULL 
BEGIN  
    declare @hr_ini INT = 6
    declare @min_ini INT = 0
    declare @seg_ini INT = 0
    set @EMBARQUE_INI = ( select DATEADD(HOUR, @hr_ini, (select DATEADD(MINUTE, @min_ini, (select DATEADD(SECOND, @seg_ini, @EMBARQUE_INI))))) )
END ELSE  
    SET @EMBARQUE_INI = GETDATE()

                 
IF @EMBARQUE_FIM IS NOT NULL 
  BEGIN  
declare @hr_fim INT = 5
declare @min_fim INT = 59
declare @seg_fim INT = 59
set @EMBARQUE_FIM = ( select DATEADD(HOUR, @hr_fim, (select DATEADD(MINUTE, @min_fim, (select DATEADD(SECOND, @seg_fim, @EMBARQUE_FIM))))) )
END ELSE       
    SET @EMBARQUE_FIM = GETDATE()  
*/
        
IF OBJECT_ID ('TEMPDB..#TEMP_FRETES_LOCALIZADOS') IS NOT NULL
 DROP TABLE #TEMP_FRETES_LOCALIZADOS

-- PEGA TODOS OS FRETES GERADOS
-- SELECT *

--     INTO #TEMP_FRETES_LOCALIZADOS

-- FROM FRETES_PAGAR_TRANSPORTADORAS            A
-- WHERE
-- 1 = 1
-- -- AND A.EMPRESA = @EMPRESA
-- AND A.DATA_EMBARQUE BETWEEN @EMBARQUE_INI AND @EMBARQUE_FIM
-- AND ( A.TRANSPORTADORA = @TRANSPORTADORA OR @TRANSPORTADORA IS NULL )
-- AND ( A.ROTA = @ROTA OR @ROTA IS NULL )
-- AND ( A.FRETE_CONTRATO = @CONTRATO OR @CONTRATO IS NULL )
-- AND ( A.ID_AUTORIZACAO_PAGAMENTO = @ID_AUTORIZACAO_PAGAMENTO OR @ID_AUTORIZACAO_PAGAMENTO IS NULL )
-- AND ( @STATUS = 1 )          
-- AND ( A.NUM_ROMANEIO = @ROMANEIO OR @ROMANEIO IS NULL )

-- UNION ALL

-- PEGA TODOS OS FRETES AUTORIZADOS
-- Obs: O status aqui é diferente da variavel @STATUS
SELECT
    *
    , 1 AS 'STATUS'
INTO #TEMP_FRETES_LOCALIZADOS
FROM FRETES_PAGAR_TRANSPORTADORAS            A
WHERE
1 = 1
-- AND A.EMPRESA = @EMPRESA
AND A.DATA_EMBARQUE BETWEEN @EMBARQUE_INI AND @EMBARQUE_FIM
AND ( A.TRANSPORTADORA = @TRANSPORTADORA OR @TRANSPORTADORA IS NULL )
AND ( A.ROTA = @ROTA OR @ROTA IS NULL )
AND ( A.FRETE_CONTRATO = @CONTRATO OR @CONTRATO IS NULL )
AND ( A.ID_AUTORIZACAO_PAGAMENTO = @ID_AUTORIZACAO_PAGAMENTO OR @ID_AUTORIZACAO_PAGAMENTO IS NULL )
AND ( A.ID_AUTORIZACAO_PAGAMENTO IS NOT NULL )
-- AND ( @STATUS = 2 ) 
AND ( A.NUM_ROMANEIO = @ROMANEIO OR @ROMANEIO IS NULL )

UNION ALL

-- PEGA TODOS OS FRETES NÃO AUTORIZADOS
-- Obs: O status aqui é diferente da variavel @STATUS
SELECT
    *
    , 2 AS 'STATUS'
FROM FRETES_PAGAR_TRANSPORTADORAS            A
WHERE
1 = 1
-- AND A.EMPRESA = @EMPRESA
AND A.DATA_EMBARQUE BETWEEN @EMBARQUE_INI AND @EMBARQUE_FIM
AND ( A.TRANSPORTADORA = @TRANSPORTADORA OR @TRANSPORTADORA IS NULL )
AND ( A.ROTA = @ROTA OR @ROTA IS NULL )
AND ( A.FRETE_CONTRATO = @CONTRATO OR @CONTRATO IS NULL )
AND ( A.ID_AUTORIZACAO_PAGAMENTO = @ID_AUTORIZACAO_PAGAMENTO OR @ID_AUTORIZACAO_PAGAMENTO IS NULL )
AND ( A.ID_AUTORIZACAO_PAGAMENTO IS NULL )
-- AND ( @STATUS = 3 )         
AND ( A.NUM_ROMANEIO = @ROMANEIO OR @ROMANEIO IS NULL )

IF OBJECT_ID ('TEMPDB..#TEMP_TABELA_FINAL') IS NOT NULL
 DROP TABLE #TEMP_TABELA_FINAL

SELECT 
  A.FRETE_PAGAR_TRANSPORTADORA
, A.EMPRESA
, CONCAT(B.ENTIDADE, '-' , B.NOME_FANTASIA) AS NOME_EMPRESA
, A.TRANSPORTADORA
, C.RAZAO_SOCIAL AS NOME_TRANSPORTADORA
, A.NOTA_DESPACHO
, A.NUM_ROMANEIO
, A.DATA_EMBARQUE
, A.NF_FATURAMENTO          
, A.NF_NUMERO
, A.NF_SERIE
, A.ID_NOTA
, A.ENTIDADE_CLIENTE
, CONCAT(D.ENTIDADE, '-', D.NOME) AS NOME_CLIENTE
, A.EMISSAO_NF AS EMISSAO_NF
, F.DATA_HORA AS DATA_BIPAGEM
, A.TOTAL_NF
, A.TOTAL_PRODUTOS
, A.VOLUMES_NF
, A.ROTA
, A.FRETE_CONTRATO  
, CONCAT('Cód.', FRETE_CONTRATO, ' - ', A.PERCENTUAL_PAGAMENTO , '% | Base de cáculo: ', CASE WHEN A.TIPO_CALCULO = 1 THEN 'Valor de NF' WHEN A.TIPO_CALCULO = 2 THEN 'Valor de mercadoria' WHEN A.TIPO_CALCULO = 3 THEN 'Aéreo-AWB' END ) AS DESCRICAO_CONTRATO
, A.PERCENTUAL_PAGAMENTO
, A.TIPO_CALCULO
, A.VALOR_FRETE
, A.ID_AUTORIZACAO_PAGAMENTO  
, 1 AS CONT
, A.STATUS
    INTO #TEMP_TABELA_FINAL

FROM #TEMP_FRETES_LOCALIZADOS        A
JOIN EMPRESAS_USUARIAS                B WITH(NOLOCK) ON B.ENTIDADE = A.EMPRESA
JOIN VW_TRANSPORTADORAS                C WITH(NOLOCK) ON C.ENTIDADE = A.TRANSPORTADORA
LEFT JOIN ENTIDADES                        D WITH(NOLOCK) ON D.ENTIDADE = A.ENTIDADE_CLIENTE
LEFT JOIN NF_FATURAMENTO                    E WITH(NOLOCK) ON E.EMPRESA = A.EMPRESA AND E.NF_FATURAMENTO = A.NF_FATURAMENTO AND E.NF_SERIE = A.NF_SERIE
                                                    AND E.NOTA_DESPACHO = A.NOTA_DESPACHO AND E.ENTIDADE = A.ENTIDADE_CLIENTE
LEFT JOIN NF_FATURAMENTO_CANHOTOS        F WITH(NOLOCK) ON F.NF_FATURAMENTO = E.NF_FATURAMENTO

------------------
-- SELECT FINAL --
------------------

IF (@BIPAGEM_INI IS NULL)   
BEGIN

    SELECT B.* 
    FROM #TEMP_TABELA_FINAL    B  
    ORDER BY B.EMPRESA, B.NOME_TRANSPORTADORA, B.DATA_EMBARQUE  
    
END ELSE
BEGIN

    SELECT B.*                 
    FROM #TEMP_TABELA_FINAL    B
    WHERE B.DATA_BIPAGEM BETWEEN @BIPAGEM_INI AND @BIPAGEM_FIM 
    ORDER BY B.EMPRESA, B.NOME_TRANSPORTADORA, B.DATA_EMBARQUE  
    
END                                                