SELECT  A.PRODUTO   AS produto,
        B.DESCRICAO AS grupo,
        C.DESCRICAO AS subgrupo
    FROM PRODUTOS           A WITH(NOLOCK)
    JOIN GRUPOS_PRODUTOS    B WITH(NOLOCK) ON A.GRUPO_PRODUTO    = B.GRUPO_PRODUTO
    JOIN SUBGRUPOS_PRODUTOS C WITH(NOLOCK) ON A.SUBGRUPO_PRODUTO = C.SUBGRUPO_PRODUTO
