select
    produto,
    entidade,
    referencia,
    percentual_desconto,
    valor_unitario,
    fornecedor_desconto,
    quantidade_minima,
    tipo,
    percentual_repasse,
    pratica_desconto_cascata,
    empresa,
    tipo_fornecedor,
    data_validade_ini,
    data_validade_fim
from
    vw_produtos_precos_descontos_compras_produto_empresa_precificacao
