SELECT
	A.NF_FATURAMENTO AS nf_faturamento,
	A.LOTE AS lote,
	A.VALIDADE_DIGITACAO AS validade,
	A.PRODUTO AS produto,
	A.QUANTIDADE AS quantidade,
	B.MOVIMENTO
FROM NF_FATURAMENTO_PRODUTOS_LOTE_VALIDADE	A
LEFT JOIN NF_FATURAMENTO							B ON B.NF_FATURAMENTO = A.NF_FATURAMENTO
WHERE B.MOVIMENTO = CAST('REPLACE_START_DATE' AS DATE)