SELECT
    apuracao_antecipacao_icms,
    formulario_origem,
    tab_master_origem,
    reg_master_origem,
    reg_log_inclusao,
    data_hora,
    usuario_logado,
    empresa,
    entidade_filtro,
    processar,
    finalizar,
    movimento,
    gerar_parcelas,
    data_limite_fechamento,
    movimento_ini,
    movimento_fim,
    status_controladoria,
    observacao_aprovacao,
    registro_aprovacao,
    data_hora_aprovacao
FROM
    APURACOES_ANTECIPACOES_ICMS
