SELECT
    rebaixa_apuracao_ciclo,
    formulario_origem,
    tab_master_origem,
    reg_master_origem,
    reg_log_inclusao,
    rebaixa_apuracao,
    acordo_comercial,
    acordo_comercial_pai,
    ciclo,
    data_fechamento_inicial,
    data_fechamento_final
FROM
    REBAIXAS_APURACOES_CICLOS
