WITH TEMP_GRUPOS_COMPRAS AS (
    SELECT
        A.GRUPO_COMPRA,
        A.FORNECEDOR,
        A.COMPRADOR,
        B.MARCA
    FROM
	GRUPOS_COMPRAS A WITH(NOLOCK)
	LEFT JOIN GRUPOS_COMPRAS_MARCAS B WITH(NOLOCK) ON B.GRUPO_COMPRA = A.GRUPO_COMPRA
    WHERE
		1 = 1
        AND A.VINCULAR_COMPRADOR = 'S'
)

SELECT
	DISTINCT
	A.MARCA AS codigo_fornecedor
	,A.DESCRICAO AS fornecedor
	-- ,F.FABRICANTE_PRODUTO AS grupo_economico
	,C.COMPRADOR AS codigo_comprador
	,E.NOME AS comprador
	,B.ENTIDADE AS entidade
	,D.NOME_FANTASIA AS entidade_nome
	,dbo.SO_NUMERO(D.INSCRICAO_FEDERAL) AS cnpj
FROM
	MARCAS A
	LEFT JOIN MARCAS_ENTIDADES B WITH(NOLOCK)ON B.MARCA = A.MARCA AND B.PRINCIPAL = 'S'
	LEFT JOIN TEMP_GRUPOS_COMPRAS C WITH(NOLOCK) ON C.MARCA = A.MARCA
	LEFT JOIN ENTIDADES D WITH(NOLOCK)ON D.ENTIDADE = B.ENTIDADE
	LEFT JOIN COMPRADORES E WITH(NOLOCK)ON E.COMPRADOR = C.COMPRADOR
	-- LEFT JOIN FABRICANTES_PRODUTOS_MARCAS	F WITH(NOLOCK) ON F.MARCA = A.MARCA
