DECLARE @EMPRESA NUMERIC(15) = REPLACE_UNIT_HERE

DECLARE @CENTRO_ESTOQUE NUMERIC(15) = (SELECT TOP 1 A.CENTRO_ESTOQUE FROM OS_EMPRESAS_CENTROS_ESTOQUES_MAPAS A WHERE A.EMPRESA = @EMPRESA) 

SELECT
	T1.*,
    CAST(GETDATE() AS DATE) as data,
	sts.SITUACAO_PRODUTO AS situacao_produto,
	sts.LEGENDA AS legenda,
	sts.SITUACAO_PRODUTO_COMPRA AS situacao_compra
FROM (SELECT
    @EMPRESA                                                                 AS empresa,
    A.PRODUTO                                                                AS produto,
    CAST(SUM(ISNULL(D.ESTOQUE_SALDO, 0)) AS NUMERIC(15))                     AS estoque_saldo,
    CAST(SUM(ISNULL(C.SALDO, 0)) AS NUMERIC(15))                             AS pedidos_saldo,
    CAST(SUM(ISNULL(D.ESTOQUE_SALDO, 0) + ISNULL(C.SALDO,0)) AS NUMERIC(15)) AS saldo_total,
    ISNULL((SELECT Y.PRECO_VENDA
            FROM PRODUTOS_VENDAS        Y WITH(NOLOCK)
            JOIN GRUPOS_PRECOS_EMPRESAS Z WITH(NOLOCK) ON Z.GRUPO_PRECO = Y.GRUPO_PRECO
                                                        AND Z.EMPRESA_USUARIA = @EMPRESA
                    WHERE Y.PRODUTO = A.PRODUTO), 0) AS preco_venda
FROM      PRODUTOS               A WITH(NOLOCK)
LEFT JOIN ESTOQUE_ATUAL          D WITH(NOLOCK) ON D.PRODUTO         = A.PRODUTO
                                                AND D.CENTRO_ESTOQUE  = @CENTRO_ESTOQUE
LEFT JOIN (
        SELECT PRODUTO,
                SUM(SALDO) SALDO
            FROM PEDIDOS_COMPRAS_PRODUTOS_SALDO A WITH(NOLOCK)
            JOIN PEDIDOS_COMPRAS                B WITH(NOLOCK) ON A.PEDIDO_COMPRA = B.PEDIDO_COMPRA
                WHERE B.EMPRESA = @EMPRESA
            GROUP BY PRODUTO
                HAVING SUM(SALDO) > 0
        ) AS C ON C.PRODUTO = A.PRODUTO
GROUP BY A.PRODUTO) AS T1
INNER JOIN
(SELECT XXX.EMPRESA,
        XXX.PRODUTO,
        XXX.SITUACAO_PRODUTO,
		XXX.LEGENDA,
		XXX.SITUACAO_PRODUTO_COMPRA
FROM SITUACOES_PRODUTOS AA WITH (NOLOCK)
JOIN
    (SELECT CASE
                WHEN A.SITUACAO_PRODUTO= 2 THEN A.SITUACAO_PRODUTO
                ELSE ISNULL(B.SITUACAO_PRODUTO, 1)
            END AS SITUACAO_PRODUTO,
            A.PRODUTO AS PRODUTO,
            A.DESCRICAO AS DESCRICAO,
            b.EMPRESA,
			b.LEGENDA,
			b.SITUACAO_PRODUTO_COMPRA
    FROM PRODUTOS a WITH (nolock)
    JOIN PRODUTOS_PARAMETROS_EMPRESAS b WITH (nolock) ON A.PRODUTO=B.PRODUTO) AS XXX ON AA.SITUACAO_PRODUTO=XXX.SITUACAO_PRODUTO) sts ON sts.EMPRESA = T1.empresa AND sts.PRODUTO = T1.produto