select
    acordo_comercial_forma_pagamento
    ,acordo_comercial
    ,percentual
    ,modalidade
    ,titulo
    ,dias
    ,vencimento
    ,local_cobranca
    ,desconto_ate
    ,desconto_valor
    ,juros_atraso
    ,multa_atraso
    ,valor
    ,tarifa_bancaria
    ,retencao_ir
    ,retencao_darf
    ,retencao_iss
    ,retencao_gps
    ,retencao_inss
    ,retencao_pis
    ,retencao_cofins
    ,retencao_cssl
    ,retencao_copics
    ,antecipacao_receber
    ,objeto_controle
    ,classif_financeira
    ,forma_pagamento
from
    acordos_comerciais_formas_pagamentos