SELECT
	A.RESTRICAO_DIVISAO_FABRICANTE_VENDEDOR AS restricao_divisao_fabricante_vendedor,
	A.RESTRICAO_DIVISAO_FABRICANTE AS restricao_divisao_fabricante,
	A.VENDEDOR AS vendedor,
	A.TIPO_RESTRICAO AS tipo_restricao,
	A.EMPRESA AS empresa
FROM RESTRICOES_DIVISOES_FABRICANTES_VENDEDORES AS A