SELECT 
	A.VENDEDOR            AS codigo_vendedor,
	A.NOME                AS nome_vendedor,
	CASE 
		WHEN A.CARGO_COMERCIAL = 3
			THEN 1
		WHEN A.CARGO_COMERCIAL = 4
			THEN 2
		WHEN A.CARGO_COMERCIAL = 5
			THEN 3
		ELSE 4
	END       AS tipo_vendedor,
	A.ENTIDADE_SUPERVISOR AS codigo_supervisor,
	B.CARGO_COMERCIAL     AS cargo_comercial,
	B.DESCRICAO           AS cargo_comercial_descricao,
	C.COMISSAO_LIQUIDEZ,
	C.COMISSAO_VENDA
FROM
	VENDEDORES        A WITH(NOLOCK)
	JOIN CARGOS_COMERCIAIS B WITH(NOLOCK) ON B.CARGO_COMERCIAL = A.CARGO_COMERCIAL
	LEFT JOIN CARGOS_COMISSOES C WITH(NOLOCK) ON C.CARGO_COMISSAO = A.CARGO_COMISSAO
WHERE
	A.CARGO_COMERCIAL IN(2,3,4,5)