SELECT
    fornecedor_desconto_imp,
    formulario_origem,
    tab_master_origem,
    reg_master_origem,
    reg_log_inclusao,
    fornecedor_desconto,
    codigo_barras,
    descricao,
    referencia,
    desconto,
    valor_unitario,
    produto,
    percentual_repasse
FROM
    FORNECEDORES_DESCONTOS_IMPORTACOES
