SET NOCOUNT ON
SET ANSI_WARNINGS OFF

if object_id('tempdb..#TEMP_MARGEM') is not null              
   DROP TABLE #TEMP_MARGEM

SELECT 
    A.NF_FATURAMENTO_PRODUTO,
    A.NF_FATURAMENTO,
    A.PRODUTO,
    A.PREC_TIPO_CUSTO,
    A.QUANTIDADE_ESTOQUE,
    CAST( (A.TOTAL_PRODUTO / A.QUANTIDADE_ESTOQUE ) AS numeric(15,2))         AS PRECO_NF_LIQUIDO, 
    CAST((A.VALOR_DESC_FINANCEIRO / A.QUANTIDADE_ESTOQUE) AS numeric(15,4))   AS VALOR_DESCONTO_FIN_UNIT,
    
    A.PREC_CUSTO,
    A.PREC_ICMS_VALOR,
    A.PREC_PIS_VALOR,
    A.PREC_COFINS_VALOR,
    A.PREC_DESPESAS_ST_VALOR,
    CAST ( 0 AS NUMERIC(15,4)) AS LUCRO_LIQUIDO,
    CAST ( 0 AS NUMERIC(15,4)) AS RECEITA_LIQUIDA,
    CAST(B.MOVIMENTO AS DATE) AS MOVIMENTO
INTO #TEMP_MARGEM
       
  FROM NF_FATURAMENTO_PRODUTOS A WITH(NOLOCK)  
  JOIN NF_FATURAMENTO          B WITH(NOLOCK)  ON B.NF_FATURAMENTO  = A.NF_FATURAMENTO
  JOIN OPERACOES_FISCAIS       C WITH(NOLOCK)  ON C.OPERACAO_FISCAL = B.OPERACAO_FISCAL
  WHERE
    1 = 1
    AND B.MOVIMENTO >= CAST('REPLACE_START_DATE' AS DATE)
    AND B.MOVIMENTO < CAST('REPLACE_END_DATE' AS DATE)
    AND C.TIPO_OPERACAO = 3
	AND A.QUANTIDADE_ESTOQUE <> 0
    --AND A.PREC_CUSTO IS NOT NULL

	--ATUALIZA LUCRO--
	UPDATE A SET LUCRO_LIQUIDO =  PRECO_NF_LIQUIDO
	                             -VALOR_DESCONTO_FIN_UNIT
						         -PREC_CUSTO
						         -PREC_ICMS_VALOR
						         -PREC_PIS_VALOR
						         -PREC_COFINS_VALOR
						         +PREC_DESPESAS_ST_VALOR,


                RECEITA_LIQUIDA = PRECO_NF_LIQUIDO
	                             -VALOR_DESCONTO_FIN_UNIT
								 +PREC_DESPESAS_ST_VALOR

	  FROM #TEMP_MARGEM A 


SELECT A.*, 
    CAST(
        CASE 
            WHEN A.RECEITA_LIQUIDA = 0 THEN 0
            ELSE (A.LUCRO_LIQUIDO / A.RECEITA_LIQUIDA) * 100
        END AS NUMERIC(15,2)
    ) AS MARGEM
  FROM #TEMP_MARGEM A 
   WHERE A.RECEITA_LIQUIDA <> 0 
  ORDER BY MARGEM 