SELECT B.EMPRESA AS empresa,
       B.DATA_HORA AS data_hora,
       A.RECEBIMENTO AS recebimento,
       A.ENTIDADE AS entidade
    FROM APROVACOES_RECEB_VOLUMES_ITENS A
    JOIN APROVACOES_RECEB_VOLUMES       B ON B.RECEBIMENTO_APROVACAO = A.RECEBIMENTO_APROVACAO