select
    sellout_apuracao_parcela
    ,sellout_apuracao
    ,entidade
    ,valor
    ,vencimento
    ,modalidade
    ,classif_financeira
    ,objeto_controle
    ,nf_numero
    ,acordo_comercial_sellout
    ,ac_sellout
    ,empresa
    ,total_credito
    ,total_debito
    ,centro_custo
from
	sellout_apuracoes_parcelas
