SELECT A.ENTIDADE        AS cliente,
       B.EMPRESA_USUARIA AS empresa,
       B.VENDEDOR        AS vendedor
    FROM PEDIDOS_VENDAS_PARAMETROS_ENTIDADES     A WITH(NOLOCK)
    JOIN PEDIDOS_VENDAS_PARAMETROS_ENTIDADES_CDS B WITH(NOLOCK) ON B.PEDIDO_VENDA_PARAMETRO_ENTIDADE = A.PEDIDO_VENDA_PARAMETRO_ENTIDADE
        WHERE B.VENDEDOR IS NOT NULL
