SELECT
    formulario_origem,
    tab_master_origem,
    reg_master_origem,
    reg_log_inclusao,
    ac_provisao_receber,
    objeto_controle,
    saldo,
    situacao
FROM
    AC_PROVISOES_RECEBER_SALDO
