   SET NOCOUNT OFF
   
   SELECT A.PRODUTO,
          A.DESCRICAO,
          E.ESTADO_ORIGEM,
          E.ESTADO_DESTINO,
          A.NCM,
          A.CODIGO_CEST,
          A.GRUPO_TRIBUTARIO,
          A.GRUPO_TRIBUTARIO_ENTRADA,
          F.DESCRICAO AS MARCA,
          A.CST_ORIGEM,
          E.SITUACAO_TRIBUTARIA_ENTRADA    AS ENTRADA_CST,
          E.ALIQUOTA_ICMS                  AS ENTRADA_ICMS_PROPRIO,
          E.ALIQUOTA_ICMS_IMPORTACAO       AS ENTRADA_ICMS_PROPRIO_IMPORTACAO,
          E.ALIQUOTA_ICMS_PRECIFICACAO     AS ENTRADA_ICMS_PREC,
          E.ICMS_SUBSTITUTO                AS ENTRADA_ICMS_ST,
          E.IVA                            AS ENTRADA_IVA,
          E.FATOR_REDUCAO_ST_PRECIFICACAO  AS ENTRADA_RED_ICMS_ST_PREC,
          E.IVA_PRECIFICACAO               AS ENTRADA_IVA_PREC,
          E.IVA_PRECIFICACAO_IMPORTACAO    AS ENTRADA_IVA_PREC_IMP,
          E.ICMS_REGIME_PRECIFICACAO       AS ENTRADA_ICMS_REGIME_PRECIFICACAO,
          E.ICMS_REGIME_PRECIFICACAO_DIST  AS ENTRADA_ICMS_PREC_DISTR,
          E.ALIQUOTA_IPI                   AS ENTRADA_ALIQUOTA_IPI,
          E.ICMS_REDUCAO_BASE              AS ENTRADA_ICMS_REDUCAO_BASE,
          E.ICMS_REDUCAO_BASE_IMPORTACAO   AS ENTRADA_ICMS_REDUCAO_BASE_IMPORTACAO,
          NULL                             AS SAIDA_TRANSF_CST,
          0.00                             AS SAIDA_TRANSF_IVA,
          0.00                             AS SAIDA_TRANSF_ICMS_NORMAL,
          0.00                             AS SAIDA_TRANSF_ICMS_REDUCAO_BASE,
          0.00                             AS SAIDA_TRANSF_ICMS_REGIME_PRECIFICACAO,
          0.00                             AS SAIDA_TRANSF_ICMS_ST,
          0.00                             AS SAIDA_TRANSF_ICMS_RECUP,
          0.00                             AS SAIDA_TRANSF_ICMS_APUR,
          NULL                             AS ENTRADA_TRANSF_CST,
          0                                AS ENTRADA_TRANSF_ICMS_PROPRIO,
          0                                AS ENTRADA_TRANSF_ICMS_PROPRIO_IMPORTACAO,
          0                                AS ENTRADA_TRANSF_ICMS_PREC,
          0                                AS ENTRADA_TRANSF_ICMS_ST,
          0                                AS ENTRADA_TRANSF_IVA,
          0                                AS ENTRADA_TRANSF_RED_ICMS_ST_PREC,
          0                                AS ENTRADA_TRANSF_IVA_PREC,
          0                                AS ENTRADA_TRANSF_IVA_PREC_IMP,
          0                                AS ENTRADA_TRANSF_ICMS_PREC_DISTR,
          0                                AS ENTRADA_TRANSF_ALIQUOTA_IPI,
          0                                AS ENTRADA_TRANSF_ICMS_REDUCAO_BASE,
          0                                AS ENTRADA_TRANSF_ICMS_REDUCAO_BASE_IMPORTACAO,
          NULL                             AS SAIDA_VENDA_CST,
          0.00                             AS SAIDA_VENDA_IVA,
          0.00                             AS SAIDA_VENDA_ICMS_NORMAL,
          0.00                             AS SAIDA_VENDA_ICMS_REDUCAO_BASE,
          0.00                             AS SAIDA_VENDA_ICMS_REGIME_PRECIFICACAO,
          0.00                             AS SAIDA_VENDA_ICMS_ST,
          0.00                             AS SAIDA_VENDA_ICMS_RECUP,
          1 AS TIPO
  FROM PRODUTOS                              A WITH(NOLOCK)
  JOIN GRUPOS_TRIBUTARIOS_ENTRADA            D WITH(NOLOCK) ON D.GRUPO_TRIBUTARIO_ENTRADA = A.GRUPO_TRIBUTARIO_ENTRADA
  JOIN GRUPOS_TRIBUTARIOS_ENTRADA_PARAMETROS E WITH(NOLOCK) ON E.GRUPO_TRIBUTARIO_ENTRADA = D.GRUPO_TRIBUTARIO_ENTRADA
  LEFT JOIN MARCAS                           F WITH(NOLOCK) ON F.MARCA                    = A.MARCA
  UNION
   SELECT A.PRODUTO,
          A.DESCRICAO,
          E.ESTADO_ORIGEM,
          E.ESTADO_DESTINO,
          A.NCM,
          A.CODIGO_CEST,
          A.GRUPO_TRIBUTARIO,
          A.GRUPO_TRIBUTARIO_ENTRADA,
          F.DESCRICAO AS MARCA,
          A.CST_ORIGEM,
          NULL                             AS ENTRADA_CST,
          0.00                             AS ENTRADA_ICMS_PROPRIO,
          0.00                             AS ENTRADA_ICMS_PROPRIO_IMPORTACAO,
          0.00                             AS ENTRADA_ICMS_PREC,
          0.00                             AS ENTRADA_ICMS_ST,
          0.00                             AS ENTRADA_IVA,
          0.00                             AS ENTRADA_RED_ICMS_ST_PREC,
          0.00                             AS ENTRADA_IVA_PREC,
          0.00                             AS ENTRADA_IVA_PREC_IMP,
          0.00                             AS ENTRADA_ICMS_REGIME_PRECIFICACAO,
          0.00                             AS ENTRADA_ICMS_PREC_DISTR,
          0.00                             AS ENTRADA_ALIQUOTA_IPI,
          0.00                             AS ENTRADA_ICMS_REDUCAO_BASE,
          0.00                             AS ENTRADA_ICMS_REDUCAO_BASE_IMPORTACAO,
          E.SITUACAO_TRIBUTARIA            AS SAIDA_TRANSF_CST,
          E.IVA                            AS SAIDA_TRANSF_IVA,
          E.ALIQUOTA_ICMS                  AS SAIDA_TRANSF_ICMS_NORMAL,
          E.ALIQUOTA_ICMS                  AS SAIDA_TRANSF_ICMS_NORMAL,
          E.ICMS_REDUCAO_BASE              AS SAIDA_TRANSF_ICMS_REDUCAO_BASE,
          E.ICMS_REGIME_PRECIFICACAO       AS SAIDA_TRANSF_ICMS_REGIME_PRECIFICACAO,
          E.ICMS_SUBSTITUTO                AS SAIDA_TRANSF_ICMS_ST,
          E.ALIQUOTA_DESPESAS_ST           AS SAIDA_TRANSF_ICMS_RECUP,
          NULL                             AS ENTRADA_TRANSF_CST,
          0                                AS ENTRADA_TRANSF_ICMS_PROPRIO,
          0                                AS ENTRADA_TRANSF_ICMS_PROPRIO_IMPORTACAO,
          0                                AS ENTRADA_TRANSF_ICMS_PREC,
          0                                AS ENTRADA_TRANSF_ICMS_ST,
          0                                AS ENTRADA_TRANSF_IVA,
          0                                AS ENTRADA_TRANSF_RED_ICMS_ST_PREC,
          0                                AS ENTRADA_TRANSF_IVA_PREC,
          0                                AS ENTRADA_TRANSF_IVA_PREC_IMP,
          0                                AS ENTRADA_TRANSF_ICMS_PREC_DISTR,
          0                                AS ENTRADA_TRANSF_ALIQUOTA_IPI,
          0                                AS ENTRADA_TRANSF_ICMS_REDUCAO_BASE,
          0                                AS ENTRADA_TRANSF_ICMS_REDUCAO_BASE_IMPORTACAO,
          NULL                             AS SAIDA_VENDA_CST,
          0.00                             AS SAIDA_VENDA_IVA,
          0.00                             AS SAIDA_VENDA_ICMS_NORMAL,
          0.00                             AS SAIDA_VENDA_ICMS_REDUCAO_BASE,
          0.00                             AS SAIDA_VENDA_ICMS_REGIME_PRECIFICACAO,
          0.00                             AS SAIDA_VENDA_ICMS_ST,
          0.00                             AS SAIDA_VENDA_ICMS_RECUP,
          2 AS TIPO
  FROM PRODUTOS                              A WITH(NOLOCK)
  JOIN GRUPOS_TRIBUTARIOS                    D WITH(NOLOCK) ON D.GRUPO_TRIBUTARIO =
                                                               IIF(A.CST_ORIGEM IN ('1', '2', '3', '8'),
                                                                   A.GRUPO_TRIBUTARIO_IMPORTADOS, A.GRUPO_TRIBUTARIO)
  JOIN GRUPOS_TRIBUTARIOS_PARAMETROS         E WITH(NOLOCK) ON E.GRUPO_TRIBUTARIO = D.GRUPO_TRIBUTARIO
  LEFT JOIN MARCAS                           F WITH(NOLOCK) ON F.MARCA            = A.MARCA
UNION
   SELECT A.PRODUTO,
          A.DESCRICAO,
          E.ESTADO_ORIGEM,
          E.ESTADO_DESTINO,
          A.NCM,
          A.CODIGO_CEST,
          A.GRUPO_TRIBUTARIO,
          A.GRUPO_TRIBUTARIO_ENTRADA,
          F.DESCRICAO AS MARCA,
          A.CST_ORIGEM,
          NULL                             AS ENTRADA_CST,
          0                                AS ENTRADA_ICMS_PROPRIO,
          0                                AS ENTRADA_ICMS_PROPRIO_IMPORTACAO,
          0                                AS ENTRADA_ICMS_PREC,
          0                                AS ENTRADA_ICMS_ST,
          0                                AS ENTRADA_IVA,
          0                                AS ENTRADA_RED_ICMS_ST_PREC,
          0                                AS ENTRADA_IVA_PREC,
          0                                AS ENTRADA_IVA_PREC_IMP,
          0                                AS ENTRADA_ICMS_REGIME_PRECIFICACAO,
          0                                AS ENTRADA_ICMS_PREC_DISTR,
          0                                AS ENTRADA_ALIQUOTA_IPI,
          0                                AS ENTRADA_ICMS_REDUCAO_BASE,
          0                                AS ENTRADA_ICMS_REDUCAO_BASE_IMPORTACAO,
          NULL                             AS SAIDA_TRANSF_CST,
          0.00                             AS SAIDA_TRANSF_IVA,
          0.00                             AS SAIDA_TRANSF_ICMS_NORMAL,
          0.00                             AS SAIDA_TRANSF_ICMS_REDUCAO_BASE,
          0.00                             AS SAIDA_TRANSF_ICMS_REGIME_PRECIFICACAO,
          0.00                             AS SAIDA_TRANSF_ICMS_ST,
          0.00                             AS SAIDA_TRANSF_ICMS_RECUP,
          0.00                             AS SAIDA_TRANSF_ICMS_APUR,
          E.SITUACAO_TRIBUTARIA_ENTRADA    AS ENTRADA_TRANSF_CST,
          E.ALIQUOTA_ICMS                  AS ENTRADA_TRANSF_ICMS_PROPRIO,
          E.ALIQUOTA_ICMS_IMPORTACAO       AS ENTRADA_TRANSF_ICMS_PROPRIO_IMPORTACAO,
          E.ALIQUOTA_ICMS_PRECIFICACAO     AS ENTRADA_TRANSF_ICMS_PREC,
          E.ICMS_SUBSTITUTO                AS ENTRADA_TRANSF_ICMS_ST,
          E.IVA                            AS ENTRADA_TRANSF_IVA,
          E.FATOR_REDUCAO_ST_PRECIFICACAO  AS ENTRADA_TRANSF_RED_ICMS_ST_PREC,
          E.IVA_PRECIFICACAO               AS ENTRADA_TRANSF_IVA_PREC,
          E.IVA_PRECIFICACAO_IMPORTACAO    AS ENTRADA_TRANSF_IVA_PREC_IMP,
          E.ICMS_REGIME_PRECIFICACAO_DIST  AS ENTRADA_TRANSF_ICMS_PREC_DISTR,
          E.ALIQUOTA_IPI                   AS ENTRADA_TRANSF_ALIQUOTA_IPI,
          E.ICMS_REDUCAO_BASE              AS ENTRADA_TRANSF_ICMS_REDUCAO_BASE,
          E.ICMS_REDUCAO_BASE_IMPORTACAO   AS ENTRADA_TRANSF_ICMS_REDUCAO_BASE_IMPORTACAO,
          NULL                             AS SAIDA_VENDA_CST,
          0.00                             AS SAIDA_VENDA_IVA,
          0.00                             AS SAIDA_VENDA_ICMS_NORMAL,
          0.00                             AS SAIDA_VENDA_ICMS_REDUCAO_BASE,
          0.00                             AS SAIDA_VENDA_ICMS_REGIME_PRECIFICACAO,
          0.00                             AS SAIDA_VENDA_ICMS_ST,
          0.00                             AS SAIDA_VENDA_ICMS_RECUP,
          3 AS TIPO
  FROM PRODUTOS                              A WITH(NOLOCK)
  JOIN GRUPOS_TRIBUTARIOS_ENTRADA            D WITH(NOLOCK) ON D.GRUPO_TRIBUTARIO_ENTRADA = A.GRUPO_TRIBUTARIO_ENTRADA
  JOIN GRUPOS_TRIBUTARIOS_ENTRADA_PARAMETROS E WITH(NOLOCK) ON E.GRUPO_TRIBUTARIO_ENTRADA = D.GRUPO_TRIBUTARIO_ENTRADA
  LEFT JOIN MARCAS                           F WITH(NOLOCK) ON F.MARCA                    = A.MARCA
UNION
   SELECT A.PRODUTO,
          A.DESCRICAO,
          E.ESTADO_ORIGEM,
          E.ESTADO_DESTINO,
          A.NCM,
          A.CODIGO_CEST,
          A.GRUPO_TRIBUTARIO,
          A.GRUPO_TRIBUTARIO_ENTRADA,
          F.DESCRICAO AS MARCA,
          A.CST_ORIGEM,
          NULL                             AS ENTRADA_CST,
          0.00                             AS ENTRADA_ICMS_PROPRIO,
          0.00                             AS ENTRADA_ICMS_PROPRIO_IMPORTACAO,
          0.00                             AS ENTRADA_ICMS_PREC,
          0.00                             AS ENTRADA_ICMS_ST,
          0.00                             AS ENTRADA_IVA,
          0.00                             AS ENTRADA_RED_ICMS_ST_PREC,
          0.00                             AS ENTRADA_IVA_PREC,
          0.00                             AS ENTRADA_IVA_PREC_IMP,
          0.00                             AS ENTRADA_ICMS_REGIME_PRECIFICACAO,
          0.00                             AS ENTRADA_ICMS_PREC_DISTR,
          0.00                             AS ENTRADA_ALIQUOTA_IPI,
          0.00                             AS ENTRADA_ICMS_REDUCAO_BASE,
          0.00                             AS ENTRADA_ICMS_REDUCAO_BASE_IMPORTACAO,
          NULL                             AS SAIDA_TRANSF_CST,
          0.00                             AS SAIDA_TRANSF_IVA,
          0.00                             AS SAIDA_TRANSF_ICMS_NORMAL,
          0.00                             AS SAIDA_TRANSF_ICMS_NORMAL,
          0.00                             AS SAIDA_TRANSF_ICMS_REDUCAO_BASE,
          0.00                             AS SAIDA_TRANSF_ICMS_REGIME_PRECIFICACAO,
          0.00                             AS SAIDA_TRANSF_ICMS_ST,
          0.00                             AS SAIDA_TRANSF_ICMS_RECUP,
          NULL                             AS ENTRADA_TRANSF_CST,
          0                                AS ENTRADA_TRANSF_ICMS_PROPRIO,
          0                                AS ENTRADA_TRANSF_ICMS_PROPRIO_IMPORTACAO,
          0                                AS ENTRADA_TRANSF_ICMS_PREC,
          0                                AS ENTRADA_TRANSF_ICMS_ST,
          0                                AS ENTRADA_TRANSF_IVA,
          0                                AS ENTRADA_TRANSF_RED_ICMS_ST_PREC,
          0                                AS ENTRADA_TRANSF_IVA_PREC,
          0                                AS ENTRADA_TRANSF_IVA_PREC_IMP,
          0                                AS ENTRADA_TRANSF_ICMS_PREC_DISTR,
          0                                AS ENTRADA_TRANSF_ALIQUOTA_IPI,
          0                                AS ENTRADA_TRANSF_ICMS_REDUCAO_BASE,
          0                                AS ENTRADA_TRANSF_ICMS_REDUCAO_BASE_IMPORTACAO,
          E.SITUACAO_TRIBUTARIA            AS SAIDA_VENDA_CST,
          E.IVA                            AS SAIDA_VENDA_IVA,
          E.ALIQUOTA_ICMS                  AS SAIDA_VENDA_ICMS_NORMAL,
          E.ICMS_REDUCAO_BASE              AS SAIDA_VENDA_ICMS_REDUCAO_BASE,
          E.ICMS_REGIME_PRECIFICACAO       AS SAIDA_VENDA_ICMS_REGIME_PRECIFICACAO,
          E.ICMS_SUBSTITUTO                AS SAIDA_VENDA_ICMS_ST,
          E.ALIQUOTA_DESPESAS_ST           AS SAIDA_VENDA_ICMS_RECUP,
          4 AS TIPO
  FROM PRODUTOS                              A WITH(NOLOCK)
  JOIN GRUPOS_TRIBUTARIOS                    D WITH(NOLOCK) ON D.GRUPO_TRIBUTARIO =
                                                               IIF(A.CST_ORIGEM IN ('1', '2', '3', '8'),
                                                                   A.GRUPO_TRIBUTARIO_IMPORTADOS, A.GRUPO_TRIBUTARIO)
  JOIN GRUPOS_TRIBUTARIOS_PARAMETROS         E WITH(NOLOCK) ON E.GRUPO_TRIBUTARIO = D.GRUPO_TRIBUTARIO
  LEFT JOIN MARCAS                           F WITH(NOLOCK) ON F.MARCA            = A.MARCA
