select
    sellout_apuracao_produto
    ,sellout_apuracao
    ,empresa
    ,nf_numero
    ,pedido_venda
    ,configuracao_ol
    ,produto
    ,quantidade
    ,valor_unitario
    ,total_produto
    ,total_desconto
    ,percentual_reembolso
    ,valor_ressarcimento
    ,margem
    ,desconto_arquivo
    ,total_credito
    ,total_debito
    ,custo_operacional
    ,total_desconto_produto
from
	sellout_apuracoes_produtos
