SELECT A.NF_COMPRA_PRODUTO        AS nf_compra_produto,
       A.NF_COMPRA                AS nf_compra,
       A.REFERENCIA               AS referencia,
       A.PRODUTO                  AS produto,
       A.EAN                      AS ean,
       A.UNIDADE_MEDIDA           AS unidade_medida,
       A.OPERACAO_FISCAL          AS operacao_fiscal,
       A.QUANTIDADE               AS quantidade,
       A.QUANTIDADE_EMBALAGEM     AS quantidade_embalagem,
       A.QUANTIDADE_MULTIPLO      AS quantidade_multiplo,
       A.VALOR_UNITARIO           AS valor_unitario,
       A.DESCONTO                 AS valor_desconto,
       CAST(A.FABRICACAO AS DATE) AS data_fabricacao,
       CAST(A.VALIDADE AS DATE)   AS data_validade,
       A.LOTE                     AS lote,
       A.DATA_FABRICACAO          AS data_fabric_digitado,
       A.VALIDADE_DIGITACAO       AS data_valid_digitado,
       A.RATEIO_REPASSE           AS valor_repasse
FROM NF_COMPRA_PRODUTOS A WITH(NOLOCK)