SELECT
    fornecedor_desconto_produto,
    formulario_origem,
    tab_master_origem,
    reg_master_origem,
    reg_log_inclusao,
    fornecedor_desconto,
    produto,
    percentual_desconto,
    tipo,
    valor_unitario,
    referencia,
    sugestao_compra,
    ean,
    quantidade_minima,
    percentual_repasse
FROM
    FORNECEDORES_DESCONTOS_PRODUTOS
