SELECT
    ac_recebimento_transacao,
    formulario_origem,
    tab_master_origem,
    reg_master_origem,
    reg_log_inclusao,
    registro_controle,
    registro_controle_ii,
    ac_recebimento,
    data,
    debito,
    credito
FROM
    AC_RECEBIMENTOS_TRANSACOES
