SET NOCOUNT ON
DECLARE @DATA_INICIAL DATE = IIF('REPLACE_START_DATE' = '  /  /    ', NULL, 'REPLACE_START_DATE');
DECLARE @DATA_FINAL   DATE = IIF('REPLACE_END_DATE' = '  /  /    ', NULL, 'REPLACE_END_DATE');

IF OBJECT_ID('TEMPDB..#TEMP_NF') IS NOT NULL DROP TABLE #TEMP_NF;
SELECT A.FORMULARIO_ORIGEM,
       A.TAB_MASTER_ORIGEM,
       A.NF_FATURAMENTO AS REG_MASTER_ORIGEM,
       A.NF_FATURAMENTO AS REGISTRO_PROCIFT,
       A.NF_NUMERO,
       A.EMPRESA,
       A.EMISSAO,
       A.OPERACAO_FISCAL,
       A.DATA_HORA,
       A.CHAVE_NFE,
       A.USUARIO_LOGADO AS USUARIO,
       E.NOME AS USUARIO_NOME,
       CASE WHEN D.STATUS = 2 THEN 'EM FILA P/ PROCESSAMENTO'
            WHEN D.STATUS = 3 THEN 'COM INCONSCISTENCIA'
            WHEN D.STATUS = 4 THEN 'AUTORIZADA'
            ELSE ISNULL(CAST(D.STATUS AS VARCHAR), 'SEM STATUS')
       END AS STATUS,
       G.PRODUTO,
       G.DESCRICAO AS DESCRICAO_PRODUTO,
       F.QUANTIDADE,
       F.TOTAL_PRODUTO,
       SUM(C.TOTAL_PRODUTOS) AS TOTAL_PRODUTOS,
       SUM(C.TOTAL_GERAL)    AS TOTAL_GERAL,
	   F.VALIDADE
    INTO #TEMP_NF
    FROM NF_FATURAMENTO          A WITH(NOLOCK)
    JOIN NF_FATURAMENTO_PRODUTOS F WITH(NOLOCK) ON F.NF_FATURAMENTO    = A.NF_FATURAMENTO
    JOIN PRODUTOS                G WITH(NOLOCK) ON G.PRODUTO           = F.PRODUTO
    JOIN PP_OPS_DETALHES         B WITH(NOLOCK) ON B.OPERACAO_FISCAL   = A.OPERACAO_FISCAL
                                               AND B.EMPRESA           = A.EMPRESA
    JOIN NF_FATURAMENTO_TOTAIS   C WITH(NOLOCK) ON C.NF_FATURAMENTO    = A.NF_FATURAMENTO
    JOIN USUARIOS                E WITH(NOLOCK) ON E.USUARIO           = A.USUARIO_LOGADO
    LEFT
    JOIN NFE_CABECALHO           D WITH(NOLOCK) ON D.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM
                                               AND D.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM
                                               AND D.REG_MASTER_ORIGEM = A.REG_MASTER_ORIGEM
        WHERE A.EMISSAO BETWEEN @DATA_INICIAL AND @DATA_FINAL
        GROUP BY A.FORMULARIO_ORIGEM, A.TAB_MASTER_ORIGEM, A.REG_MASTER_ORIGEM, A.NF_FATURAMENTO, A.EMPRESA, A.EMISSAO, A.OPERACAO_FISCAL, A.DATA_HORA, A.EMISSAO, A.CHAVE_NFE, A.USUARIO_LOGADO, D.STATUS, E.NOME, A.NF_NUMERO, G.PRODUTO, G.DESCRICAO, F.QUANTIDADE, F.TOTAL_PRODUTO, F.VALIDADE

INSERT INTO #TEMP_NF
SELECT A.FORMULARIO_ORIGEM,
       A.TAB_MASTER_ORIGEM,
       A.NF_COMPRA AS REG_MASTER_ORIGEM,
       A.NF_COMPRA AS REGISTRO_PROCIFT,
       A.NF_NUMERO,
       A.EMPRESA,
       A.MOVIMENTO AS EMISSAO,
       A.OPERACAO_FISCAL,
       A.DATA_HORA,
       ISNULL(A.CHAVE_NFE, D.CHAVE_NFE) AS CHAVE_NFE,
       A.USUARIO_LOGADO AS USUARIO,
       E.NOME AS USUARIO_NOME,
       CASE WHEN D.STATUS = 2 THEN 'EM FILA P/ PROCESSAMENTO'
            WHEN D.STATUS = 3 THEN 'COM INCONSCISTENCIA'
            WHEN D.STATUS = 4 THEN 'AUTORIZADA'
            ELSE ISNULL(CAST(D.STATUS AS VARCHAR), 'SEM STATUS')
       END AS STATUS,
       G.PRODUTO,
       G.DESCRICAO AS DESCRICAO_PRODUTO,
       F.QUANTIDADE_ESTOQUE AS QUANTIDADE,
       F.TOTAL_PRODUTO,
       SUM(C.TOTAL_PRODUTOS) AS TOTAL_PRODUTOS,
       SUM(C.TOTAL_GERAL)    AS TOTAL_GERAL,
	   F.VALIDADE
    FROM NF_COMPRA             A WITH(NOLOCK)
    JOIN NF_COMPRA_PRODUTOS    F WITH(NOLOCK) ON F.NF_COMPRA       = A.NF_COMPRA
    JOIN PRODUTOS              G WITH(NOLOCK) ON G.PRODUTO         = F.PRODUTO
    JOIN PP_OPS_DETALHES       B WITH(NOLOCK) ON B.OPERACAO_FISCAL = A.OPERACAO_FISCAL
                                             AND B.EMPRESA         = A.EMPRESA
    JOIN NF_COMPRA_TOTAIS      C WITH(NOLOCK) ON C.NF_COMPRA       = A.NF_COMPRA
    JOIN USUARIOS              E WITH(NOLOCK) ON A.USUARIO_LOGADO  = E.USUARIO
    LEFT
    JOIN NFE_CABECALHO         D WITH(NOLOCK) ON D.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM
                                             AND D.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM
                                             AND D.REG_MASTER_ORIGEM = A.REG_MASTER_ORIGEM
        WHERE A.MOVIMENTO BETWEEN @DATA_INICIAL AND @DATA_FINAL
          AND A.STATUS_PROCESSAMENTO_INTEGRACAO = 1
        GROUP BY A.FORMULARIO_ORIGEM, A.TAB_MASTER_ORIGEM, A.NF_COMPRA, A.EMPRESA, A.EMISSAO, A.OPERACAO_FISCAL, A.DATA_HORA, A.CHAVE_NFE, A.USUARIO_LOGADO, E.NOME, D.STATUS, D.CHAVE_NFE, A.MOVIMENTO, A.NF_NUMERO, G.PRODUTO, G.DESCRICAO, F.QUANTIDADE_ESTOQUE, F.TOTAL_PRODUTO, F.VALIDADE

INSERT INTO #TEMP_NF
SELECT A.FORMULARIO_ORIGEM,
       A.TAB_MASTER_ORIGEM,
       A.NF_COMPRA_DEVOLUCAO AS REG_MASTER_ORIGEM,
       A.NF_COMPRA_DEVOLUCAO AS REGISTRO_PROCIFT,
       A.NF_NUMERO,
       A.EMPRESA,
       A.MOVIMENTO AS EMISSAO,
       A.OPERACAO_FISCAL,
       A.DATA_HORA,
       ISNULL(A.CHAVE_NFE, D.CHAVE_NFE) AS CHAVE_NFE,
       A.USUARIO_LOGADO AS USUARIO,
       E.NOME AS USUARIO_NOME,
       CASE WHEN D.STATUS = 2 THEN 'EM FILA P/ PROCESSAMENTO'
            WHEN D.STATUS = 3 THEN 'COM INCONSCISTENCIA'
            WHEN D.STATUS = 4 THEN 'AUTORIZADA'
            ELSE ISNULL(CAST(D.STATUS AS VARCHAR), 'SEM STATUS')
       END AS STATUS,
       G.PRODUTO,
       G.DESCRICAO AS DESCRICAO_PRODUTO,
       F.QUANTIDADE,
       F.TOTAL_PRODUTO,
       SUM(C.TOTAL_PRODUTOS) AS TOTAL_PRODUTOS,
       SUM(C.TOTAL_GERAL)    AS TOTAL_GERAL,
	   F.VALIDADE
    FROM NF_COMPRA_DEVOLUCOES          A WITH(NOLOCK)
    JOIN NF_COMPRA_DEVOLUCOES_PRODUTOS F WITH(NOLOCK) ON F.NF_COMPRA_DEVOLUCAO = A.NF_COMPRA_DEVOLUCAO
    JOIN PRODUTOS                      G WITH(NOLOCK) ON G.PRODUTO             = F.PRODUTO
    JOIN PP_OPS_DETALHES               B WITH(NOLOCK) ON B.OPERACAO_FISCAL     = A.OPERACAO_FISCAL
                                                     AND B.EMPRESA             = A.EMPRESA
    JOIN NF_COMPRA_DEVOLUCOES_TOTAIS   C WITH(NOLOCK) ON C.NF_COMPRA_DEVOLUCAO = A.NF_COMPRA_DEVOLUCAO
    JOIN USUARIOS                      E WITH(NOLOCK) ON A.USUARIO_LOGADO      = E.USUARIO
    LEFT
    JOIN NFE_CABECALHO                 D WITH(NOLOCK) ON D.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM
                                                     AND D.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM
                                                     AND D.REG_MASTER_ORIGEM = A.REG_MASTER_ORIGEM
        WHERE A.MOVIMENTO BETWEEN @DATA_INICIAL AND @DATA_FINAL
        GROUP BY A.FORMULARIO_ORIGEM, A.TAB_MASTER_ORIGEM, A.NF_COMPRA_DEVOLUCAO, A.EMPRESA, A.MOVIMENTO, A.OPERACAO_FISCAL, A.DATA_HORA, A.CHAVE_NFE, D.CHAVE_NFE, A.USUARIO_LOGADO, E.NOME, D.STATUS, A.NF_NUMERO, G.PRODUTO, G.DESCRICAO, F.QUANTIDADE, F.TOTAL_PRODUTO, F.VALIDADE

SELECT 
        A.FORMULARIO_ORIGEM AS formulario_origem,
        A.TAB_MASTER_ORIGEM AS tab_master_origem,
        A.REG_MASTER_ORIGEM AS reg_master_origem,
        A.REGISTRO_PROCIFT AS registro_procift,
        A.NF_NUMERO AS nf_numero,
        A.EMPRESA AS empresa,
        A.EMISSAO AS emissao,
        A.OPERACAO_FISCAL AS operacao_fiscal,
        A.DATA_HORA AS data_hora,
        A.CHAVE_NFE AS chave_nfe,
        A.USUARIO AS usuario,
        A.USUARIO_NOME AS usuario_nome,
        A.STATUS AS status,
        A.PRODUTO AS produto,
        A.DESCRICAO_PRODUTO AS descricao_produto,
        A.QUANTIDADE AS quantidade,
        A.TOTAL_PRODUTO AS total_produto,
        A.TOTAL_PRODUTOS AS total_produtos,
        A.TOTAL_GERAL AS total_geral,
        B.DESCRICAO AS formulario,
        CAST(A.VALIDADE AS DATE) AS validade
FROM
        #TEMP_NF    A
        JOIN FORMULARIOS B ON B.NUMID = A.FORMULARIO_ORIGEM
WHERE NOT EXISTS(SELECT TOP 1 1 FROM NFE_CANCELAMENTOS ZZ WHERE ZZ.IDNOTA = A.CHAVE_NFE)