SELECT
    grupo_economico_conta,
    formulario_origem,
    tab_master_origem,
    reg_master_origem,
    reg_log_inclusao,
    grupo_economico,
    nome,
    descricao,
    analista_responsavel,
    comprador,
    limite_maximo_debito
FROM
    GRUPOS_ECONOMICOS_CONTAS
