SET NOCOUNT ON

----REGRAS_EXCECAO

DECLARE @VALIDADE_INI DATETIME = CONVERT(VARCHAR(10),CAST('REPLACE_START_DATE' as DATE),103)
DECLARE @VALIDADE_FIM DATETIME = CONVERT(VARCHAR(10),CAST('REPLACE_END_DATE' as DATE),103)
DECLARE @EMPRESA       VARCHAR(1000)
DECLARE @MARCA           VARCHAR(1000)
DECLARE @PRODUTO       VARCHAR(1000)
DECLARE @CLIENTE       VARCHAR(1000)
DECLARE @REDE           VARCHAR(1000)
DECLARE @GRUPO           VARCHAR(1000)
DECLARE @APONTADOR     VARCHAR(1000)
DECLARE @IDENTIFICADOR VARCHAR(1000)
DECLARE @PROJETO       VARCHAR(1000)

-----------------------------------------------------------
-- Gera Tabela Temporária das Empresas do Usuário Logado --
-----------------------------------------------------------
if object_id('tempdb..#TEMP_EMPRESAS_USER') is not null
    drop table #TEMP_EMPRESAS_USER

SELECT * INTO #TEMP_EMPRESAS_USER FROM UDF_USUARIO_EMPRESAS('')


-- FILTRO EMPRESA - START
/*
IF :EMPRESA IS NOT NULL
    BEGIN
        SET @EMPRESA = :EMPRESA
    END

IF LEN(@EMPRESA) = 0
        SET @EMPRESA = NULL
*/

SET @EMPRESA = 3

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_EMPRESA') IS NOT NULL DROP TABLE #TEMP_FILTRO_EMPRESA

SELECT CONTEUDO AS EMPRESA
    INTO #TEMP_FILTRO_EMPRESA
FROM DBO.FN_SPLIT_TEXTO_TXT(@EMPRESA,',') A

UPDATE #TEMP_FILTRO_EMPRESA SET EMPRESA = TRIM(EMPRESA)
-- FILTRO EMPRESA - END

-- FILTRO MARCA - START
/*
IF :MARCA IS NOT NULL
    BEGIN
        SET @MARCA = :MARCA
    END

IF LEN(@MARCA) = 0
    SET @MARCA = NULL
*/

SET @MARCA = NULL

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_MARCA') IS NOT NULL DROP TABLE #TEMP_FILTRO_MARCA

SELECT CONTEUDO AS MARCA
    INTO #TEMP_FILTRO_MARCA
FROM DBO.FN_SPLIT_TEXTO_TXT(@MARCA,',') A

UPDATE #TEMP_FILTRO_MARCA SET MARCA = TRIM(MARCA)
-- FILTRO MARCA - END


-- FILTRO PRODUTO - START
/*
IF :PRODUTO IS NOT NULL
    BEGIN
        SET @PRODUTO = :PRODUTO
    END

IF LEN(@PRODUTO) = 0
    SET @PRODUTO = NULL
*/
SET @PRODUTO = NULL

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_PRODUTO') IS NOT NULL DROP TABLE #TEMP_FILTRO_PRODUTO

SELECT CONTEUDO AS PRODUTO
    INTO #TEMP_FILTRO_PRODUTO
FROM DBO.FN_SPLIT_TEXTO_TXT(@PRODUTO,',') A

UPDATE #TEMP_FILTRO_PRODUTO SET PRODUTO = TRIM(PRODUTO)
-- FILTRO PRODUTO - END



-- FILTRO CLIENTE - START
/*
IF :CLIENTE IS NOT NULL
    BEGIN
        SET @CLIENTE = :CLIENTE
    END

IF LEN(@CLIENTE) = 0
    SET @CLIENTE = NULL
*/

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_CLIENTE') IS NOT NULL DROP TABLE #TEMP_FILTRO_CLIENTE

SELECT CONTEUDO AS CLIENTE
    INTO #TEMP_FILTRO_CLIENTE
FROM DBO.FN_SPLIT_TEXTO_TXT(@CLIENTE,',') A

UPDATE #TEMP_FILTRO_CLIENTE SET CLIENTE = TRIM(CLIENTE)
-- FILTRO CLIENTE - END


-- FILTRO REDE - START
/*
IF :REDE IS NOT NULL
    BEGIN
        SET @REDE = :REDE
    END

IF LEN(@REDE) = 0
    SET @REDE = NULL
*/
SET @REDE = NULL

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_REDE') IS NOT NULL DROP TABLE #TEMP_FILTRO_REDE

SELECT CONTEUDO AS REDE
    INTO #TEMP_FILTRO_REDE
FROM DBO.FN_SPLIT_TEXTO_TXT(@REDE,',') A

UPDATE #TEMP_FILTRO_REDE SET REDE = TRIM(REDE)
-- FILTRO REDE - END


-- FILTRO GRUPO - START
/*
IF :GRUPO IS NOT NULL
    BEGIN
        SET @GRUPO = :GRUPO
    END

IF LEN(@GRUPO) = 0
    SET @GRUPO = NULL
*/
SET @GRUPO = NULL

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_GRUPO') IS NOT NULL DROP TABLE #TEMP_FILTRO_GRUPO

SELECT CONTEUDO AS GRUPO
    INTO #TEMP_FILTRO_GRUPO
FROM DBO.FN_SPLIT_TEXTO_TXT(@GRUPO,',') A

UPDATE #TEMP_FILTRO_GRUPO SET GRUPO = TRIM(GRUPO)
-- FILTRO GRUPO - END


-- FILTRO APONTADOR - START
/*
IF :APONTADOR IS NOT NULL
    BEGIN
        SET @APONTADOR = :APONTADOR
    END


IF LEN(@APONTADOR) = 0
    SET @APONTADOR = NULL
*/

SET @APONTADOR = NULL

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_APONTADOR') IS NOT NULL DROP TABLE #TEMP_FILTRO_APONTADOR

SELECT CONTEUDO AS APONTADOR
    INTO #TEMP_FILTRO_APONTADOR
FROM DBO.FN_SPLIT_TEXTO_TXT(@APONTADOR,',') A

UPDATE #TEMP_FILTRO_APONTADOR SET APONTADOR = TRIM(APONTADOR)
-- FILTRO APONTADOR - END


-- FILTRO IDENTIFICADOR - START
/*
IF :IDENTIFICADOR IS NOT NULL
    BEGIN
        SET @IDENTIFICADOR = :IDENTIFICADOR
    END

IF LEN(@IDENTIFICADOR) = 0
    SET @IDENTIFICADOR = NULL
*/
SET @IDENTIFICADOR = NULL

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_IDENTIFICADOR') IS NOT NULL DROP TABLE #TEMP_FILTRO_IDENTIFICADOR

SELECT CONTEUDO AS IDENTIFICADOR
    INTO #TEMP_FILTRO_IDENTIFICADOR
FROM DBO.FN_SPLIT_TEXTO_TXT(@IDENTIFICADOR,',') A

UPDATE #TEMP_FILTRO_IDENTIFICADOR SET IDENTIFICADOR = TRIM(IDENTIFICADOR)
-- FILTRO IDENTIFICADOR - END


-- FILTRO PROJETO - START
/*
IF :PROJETO IS NOT NULL
    BEGIN
        SET @PROJETO = :PROJETO
    END

IF LEN(@PROJETO) = 0
    SET @PROJETO = NULL
*/
SET @PROJETO = NULL

IF OBJECT_ID('TEMPDB..#TEMP_FILTRO_PROJETO') IS NOT NULL DROP TABLE #TEMP_FILTRO_PROJETO

SELECT CONTEUDO AS PROJETO
    INTO #TEMP_FILTRO_PROJETO
FROM DBO.FN_SPLIT_TEXTO_TXT(@PROJETO,',') A

UPDATE #TEMP_FILTRO_PROJETO SET PROJETO = TRIM(PROJETO)
-- FILTRO PROJETO - END


SELECT  '1 - MARCA'                   AS NIVEL
       ,A.CONFIGURACAO_OL_EXCECAO     AS CONFIGURACAO_OL
       ,A.USUARIO_LOGADO              AS COD_USUARIO
       ,C.NOME                        AS USUARIO
       ,A.DATA_HORA                   AS DATA_HORA
       ,A.DESCRICAO                   AS DESCRICAO
       ,A.PROJETO                     AS PROJETO
       ,B.DESCRICAO_PROJETO           AS DESCRICAO_PROJETO
       ,A.IDENTIFICADOR               AS IDENTIFICADOR
       ,D.DESCRICAO                   AS DESCRICAO_IDENTIFICADOR
       ,A.VALIDADE_INICIAL            AS VALIDADE_INICIAL
       ,A.VALIDADE_FINAL              AS VALIDADE_FINAL

       ,E.MARCA                       AS MARCA
       ,F.DESCRICAO                   AS MARCA_DESCRICAO
       ,E.DESCONTO_TOTAL              AS DESCONTO_TOTAL_MA
       ,E.DESCONTO_DISTRIBUIDORA      AS DESCONTO_DISTRIBUIDORA_MA
       ,E.DESCONTO_FABRICANTE         AS DESCONTO_FABRICANTE_MA
       ,E.DESCONTO_DE_INI              AS DESCONTO_DE_INI_MA /***/
       ,E.DESCONTO_DE_FIM             AS DESCONTO_DE_FIM_MA /***/
       ,I.DESCRICAO                   AS TIPO_ACAO_DESCONTO_MA -- MARCAS

       ,G.EMPRESA                     AS EMPRESA
       ,H.NOME_FANTASIA               AS DESCRICAO_EMPRESA

       ,U.DESCONTO_DE_INI             AS RD_DESCONTO_DE_INI
       ,U.DESCONTO_DE_FIM             AS RD_DESCONTO_DE_FIM
       ,U.DESCONTO_PARA               AS RD_DESCONTO_PARA
       ,U.DESCONTO_PARA_DISTRIBUIDORA AS RD_DESCONTO_PARA_DISTRIBUIDORA
       ,U.DESCONTO_PARA_INDUSTRIA     AS RD_DESCONTO_PARA_INDUSTRIA
       ,V.DESCRICAO                   AS TIPO_ACAO_DESCONTO -- Regras de Descontos

       ,L.PRODUTO                     AS PRODUTO
       ,L.DESCRICAO                   AS DESCRICAO_PRODUTO
       ,NULL                          AS DESCONTO_DISTRIBUIDORA_PROD
       ,NULL                          AS DESCONTO_INDUSTRIA_PROD
       ,NULL                          AS DESCONTO_FINAL_PROD
       ,NULL                          AS TIPO_ACAO_DESCONTO_PROD --PRODUTOS

       ,N.CONFIGURACAO_OL             AS OL_APONTADORES
       ,O.DESCRICAO                   AS DESCRICAO_OL_APONTADORES
       ,P.ENTIDADE                    AS COD_CLIENTE
       ,Q.NOME                        AS CLIENTE
       ,P.TIPO_RESTRICAO              AS COD_TIPO_RESTRICAO /***/
       ,BB.DESCRICAO                  AS TIPO_RESTRICAO /***/
       ,P.GRUPO_CLIENTE               AS COD_GRUPO
       ,S.DESCRICAO                   AS DESCRICAO_GRUPO
       ,P.CLIENTE_REDE                AS COD_REDE
       ,R.DESCRICAO                   AS DESCRICAO_REDE

     FROM CONFIGURACOES_OL_EXCECOES          A WITH(NOLOCK)
LEFT JOIN VANS_PROJETOS                      B WITH(NOLOCK) ON B.PROJETO                 = A.PROJETO
LEFT JOIN USUARIOS                           C WITH(NOLOCK) ON C.USUARIO                 = A.USUARIO_LOGADO
LEFT JOIN IDENTIFICADORES                    D WITH(NOLOCK) ON D.IDENTIFICADOR           = A.IDENTIFICADOR
     JOIN CONFIGURACOES_OL_EXCECOES_MARCAS   E WITH(NOLOCK) ON E.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN MARCAS                             F WITH(NOLOCK) ON F.MARCA                   = E.MARCA
LEFT JOIN CONFIGURACOES_OL_EXCECOES_UNIDADES G WITH(NOLOCK) ON G.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN EMPRESAS_USUARIAS                  H WITH(NOLOCK) ON H.EMPRESA_USUARIA         = G.EMPRESA
LEFT JOIN TIPOS_ACOES_DESCONTOS_OL           I WITH(NOLOCK) ON I.TIPO_ACAO_DESCONTO      = E.TIPO_ACAO_DESCONTO
LEFT JOIN CONFIGURACOES_OL_EXCECOES_PRODUTOS L1 WITH(NOLOCK) ON L1.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO

LEFT JOIN PRODUTOS                           L WITH(NOLOCK) ON L.PRODUTO                   = L1.PRODUTO
                                                           AND L.MARCA                       = E.MARCA

LEFT JOIN CONFIGURACOES_OL_EXCECOES_OLS       N WITH(NOLOCK) ON N.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN CONFIGURACOES_OL                    O WITH(NOLOCK) ON O.CONFIGURACAO_OL         = N.CONFIGURACAO_OL
LEFT JOIN CONFIGURACOES_OL_UNIDADES             O1 WITH(NOLOCK) ON O1.CONFIGURACAO_OL          = O.CONFIGURACAO_OL

LEFT JOIN CONFIGURACOES_OL_EXCECOES_CLIENTES  P WITH(NOLOCK) ON P.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN ENTIDADES                           Q WITH(NOLOCK) ON Q.ENTIDADE                = P.ENTIDADE
LEFT JOIN CLIENTES_REDES                      R WITH(NOLOCK) ON R.CLIENTE_REDE            = P.CLIENTE_REDE
LEFT JOIN GRUPOS_CLIENTES                     S WITH(NOLOCK) ON S.GRUPO_CLIENTE           = P.GRUPO_CLIENTE
LEFT JOIN CONFIGURACOES_OL_EXCECOES_DESCONTOS U WITH(NOLOCK) ON U.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN TIPOS_ACOES_DESCONTOS_OL            V WITH(NOLOCK) ON V.TIPO_ACAO_DESCONTO      = U.TIPO_ACAO_DESCONTO
     JOIN #TEMP_EMPRESAS_USER                 AA WITH(NOLOCK) ON AA.EMPRESA_USUARIA          = G.EMPRESA
LEFT JOIN TIPOS_RESTRICOES_COMERCIAIS          BB WITH(NOLOCK) ON BB.TIPO_RESTRICAO_COMERCIAL = P.TIPO_RESTRICAO

WHERE 1 = 1
  -- AND A.VALIDADE_INICIAL >= @VALIDADE_INI
  -- AND A.VALIDADE_FINAL   <= @VALIDADE_FIM

  --AND (A.VALIDADE_INICIAL BETWEEN @VALIDADE_INI AND @VALIDADE_FIM)
    --OR A.VALIDADE_FINAL BETWEEN @VALIDADE_INI AND @VALIDADE_FIM)
  AND (A.DATA_HORA BETWEEN @VALIDADE_INI AND @VALIDADE_FIM)
  AND (H.EMPRESA_USUARIA IN (SELECT EMPRESA FROM #TEMP_FILTRO_EMPRESA) OR @EMPRESA IS NULL)
  AND (F.MARCA           IN (SELECT MARCA FROM #TEMP_FILTRO_MARCA) OR @MARCA IS NULL)
  AND (L.PRODUTO         IN (SELECT PRODUTO FROM #TEMP_FILTRO_PRODUTO) OR @PRODUTO IS NULL)
  AND (Q.ENTIDADE        IN (SELECT CLIENTE FROM #TEMP_FILTRO_CLIENTE) OR @CLIENTE IS NULL)
  AND (R.CLIENTE_REDE    IN (SELECT REDE FROM #TEMP_FILTRO_REDE) OR @REDE IS NULL)
  AND (S.GRUPO_CLIENTE   IN (SELECT GRUPO FROM #TEMP_FILTRO_GRUPO) OR @GRUPO IS NULL)
  AND (O.CONFIGURACAO_OL IN (SELECT APONTADOR FROM #TEMP_FILTRO_APONTADOR) OR @APONTADOR IS NULL)
  AND (A.IDENTIFICADOR   IN (SELECT IDENTIFICADOR FROM #TEMP_FILTRO_IDENTIFICADOR) OR @IDENTIFICADOR IS NULL)
  AND (A.PROJETO         IN (SELECT PROJETO FROM #TEMP_FILTRO_PROJETO) OR @PROJETO IS NULL)
  AND O1.EMPRESA                  = H.EMPRESA_USUARIA
   --A.CONFIGURACAO_OL_EXCECAO    = 145
   --A.CONFIGURACAO_OL_EXCECAO    = 164

UNION ALL


SELECT  '2 - PRODUTO'                 AS NIVEL
       ,A.CONFIGURACAO_OL_EXCECAO     AS CONFIGURACAO_OL
       ,A.USUARIO_LOGADO              AS COD_USUARIO
       ,C.NOME                        AS USUARIO
       ,A.DATA_HORA                   AS DATA_HORA
       ,A.DESCRICAO                   AS DESCRICAO
       ,A.PROJETO                     AS PROJETO
       ,B.DESCRICAO_PROJETO           AS DESCRICAO_PROJETO
       ,A.IDENTIFICADOR               AS IDENTIFICADOR
       ,D.DESCRICAO                   AS DESCRICAO_IDENTIFICADOR
       ,A.VALIDADE_INICIAL            AS VALIDADE_INICIAL
       ,A.VALIDADE_FINAL              AS VALIDADE_FINAL

       ,NULL                          AS MARCA
       ,NULL                          AS MARCA_DESCRICAO
       ,NULL                          AS DESCONTO_TOTAL
       ,NULL                          AS DESCONTO_DISTRIBUIDORA
       ,NULL                          AS DESCONTO_FABRICANTE
       ,NULL                          AS DESCONTO_DE_INI_MA /***/
       ,NULL                          AS DESCONTO_DE_FIM_MA /***/
       ,NULL                          AS TIPO_ACAO_DESCONTO -- MARCAS

       ,G.EMPRESA                     AS EMPRESA
       ,H.NOME_FANTASIA               AS DESCRICAO_EMPRESA

       ,U.DESCONTO_DE_INI             AS RD_DESCONTO_DE_INI
       ,U.DESCONTO_DE_FIM             AS RD_DESCONTO_DE_FIM
       ,U.DESCONTO_PARA               AS RD_DESCONTO_PARA
       ,U.DESCONTO_PARA_DISTRIBUIDORA AS RD_DESCONTO_PARA_DISTRIBUIDORA
       ,U.DESCONTO_PARA_INDUSTRIA     AS RD_DESCONTO_PARA_INDUSTRIA
       ,V.DESCRICAO                   AS TIPO_ACAO_DESCONTO -- REGRAS DE DESCONTOS

       ,L.PRODUTO                     AS PRODUTO
       ,L.DESCRICAO                   AS DESCRICAO_PRODUTO
       ,J.DESCONTO_PARA_DISTRIBUIDORA AS DESCONTO_DISTRIBUIDORA
       ,J.DESCONTO_PARA_INDUSTRIA     AS DESCONTO_INDUSTRIA
       ,J.DESCONTO_PARA               AS DESCONTO_FINAL
       ,M.DESCRICAO                   AS TIPO_ACAO_DESCONTO --PRODUTOS

       ,N.CONFIGURACAO_OL             AS OL_APONTADORES
       ,O.DESCRICAO                   AS DESCRICAO_OL_APONTADORES

       ,P.ENTIDADE                    AS COD_CLIENTE
       ,Q.NOME                        AS CLIENTE
       ,P.TIPO_RESTRICAO              AS COD_TIPO_RESTRICAO /***/
       ,BB.DESCRICAO                  AS TIPO_RESTRICAO /***/
       ,P.GRUPO_CLIENTE               AS COD_GRUPO
       ,S.DESCRICAO                   AS DESCRICAO_GRUPO
       ,P.CLIENTE_REDE                AS COD_REDE
       ,R.DESCRICAO                   AS DESCRICAO_REDE

     FROM CONFIGURACOES_OL_EXCECOES          A WITH(NOLOCK)
LEFT JOIN VANS_PROJETOS                      B WITH(NOLOCK) ON B.PROJETO                 = A.PROJETO
LEFT JOIN USUARIOS                           C WITH(NOLOCK) ON C.USUARIO                 = A.USUARIO_LOGADO
LEFT JOIN IDENTIFICADORES                    D WITH(NOLOCK) ON D.IDENTIFICADOR           = A.IDENTIFICADOR

LEFT JOIN CONFIGURACOES_OL_EXCECOES_UNIDADES G WITH(NOLOCK) ON G.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN EMPRESAS_USUARIAS                  H WITH(NOLOCK) ON H.EMPRESA_USUARIA         = G.EMPRESA

/**/LEFT JOIN CONFIGURACOES_OL_EXCECOES_PRODUTOS  J WITH(NOLOCK) ON J.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN PRODUTOS                            L WITH(NOLOCK) ON L.PRODUTO                 = J.PRODUTO

LEFT JOIN TIPOS_ACOES_DESCONTOS_OL            M WITH(NOLOCK) ON M.TIPO_ACAO_DESCONTO      = J.TIPO_ACAO_DESCONTO
LEFT JOIN CONFIGURACOES_OL_EXCECOES_OLS       N WITH(NOLOCK) ON N.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN CONFIGURACOES_OL                    O WITH(NOLOCK) ON O.CONFIGURACAO_OL         = N.CONFIGURACAO_OL
LEFT JOIN CONFIGURACOES_OL_UNIDADES           O1 WITH(NOLOCK) ON O1.CONFIGURACAO_OL       = O.CONFIGURACAO_OL
LEFT JOIN CONFIGURACOES_OL_EXCECOES_CLIENTES  P WITH(NOLOCK) ON P.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN ENTIDADES                           Q WITH(NOLOCK) ON Q.ENTIDADE                = P.ENTIDADE
LEFT JOIN CLIENTES_REDES                      R WITH(NOLOCK) ON R.CLIENTE_REDE            = P.CLIENTE_REDE
LEFT JOIN GRUPOS_CLIENTES                     S WITH(NOLOCK) ON S.GRUPO_CLIENTE           = P.GRUPO_CLIENTE
LEFT JOIN CONFIGURACOES_OL_EXCECOES_DESCONTOS U WITH(NOLOCK) ON U.CONFIGURACAO_OL_EXCECAO = A.CONFIGURACAO_OL_EXCECAO
LEFT JOIN TIPOS_ACOES_DESCONTOS_OL            V WITH(NOLOCK) ON V.TIPO_ACAO_DESCONTO      = U.TIPO_ACAO_DESCONTO
     JOIN #TEMP_EMPRESAS_USER                 AA WITH(NOLOCK) ON AA.EMPRESA_USUARIA          = G.EMPRESA
LEFT JOIN TIPOS_RESTRICOES_COMERCIAIS         BB WITH(NOLOCK) ON BB.TIPO_RESTRICAO_COMERCIAL = P.TIPO_RESTRICAO

WHERE 1 = 1
  --A.VALIDADE_INICIAL >= @VALIDADE_INI
  --AND A.VALIDADE_FINAL   <= @VALIDADE_FIM
  -- AND (A.VALIDADE_INICIAL BETWEEN @VALIDADE_INI AND @VALIDADE_FIM)
    --OR A.VALIDADE_FINAL BETWEEN @VALIDADE_INI AND @VALIDADE_FIM)
  AND (A.DATA_HORA BETWEEN @VALIDADE_INI AND @VALIDADE_FIM)
  AND (H.EMPRESA_USUARIA IN (SELECT EMPRESA FROM #TEMP_FILTRO_EMPRESA) OR @EMPRESA IS NULL)
  AND (L.MARCA           IN (SELECT MARCA FROM #TEMP_FILTRO_MARCA) OR @MARCA IS NULL)
  AND (L.PRODUTO         IN (SELECT PRODUTO FROM #TEMP_FILTRO_PRODUTO) OR @PRODUTO IS NULL)
  AND (Q.ENTIDADE        IN (SELECT CLIENTE FROM #TEMP_FILTRO_CLIENTE) OR @CLIENTE IS NULL)
  AND (R.CLIENTE_REDE    IN (SELECT REDE FROM #TEMP_FILTRO_REDE) OR @REDE IS NULL)
  AND (S.GRUPO_CLIENTE   IN (SELECT GRUPO FROM #TEMP_FILTRO_GRUPO) OR @GRUPO IS NULL)
  AND (O.CONFIGURACAO_OL IN (SELECT APONTADOR FROM #TEMP_FILTRO_APONTADOR) OR @APONTADOR IS NULL)
  AND (A.IDENTIFICADOR   IN (SELECT IDENTIFICADOR FROM #TEMP_FILTRO_IDENTIFICADOR) OR @IDENTIFICADOR IS NULL)
  AND (A.PROJETO         IN (SELECT PROJETO FROM #TEMP_FILTRO_PROJETO) OR @PROJETO IS NULL)
  AND O1.EMPRESA                  = H.EMPRESA_USUARIA
