SELECT DISTINCT 
	   E301TCR.CODFIL AS FILIAL, 
	   E301TCR.NUMTIT AS NUMERO_TITULO,
	   E301MCR.SEQMOV AS SEQ_MOV,
       E301TCR.CODTPT AS TIPO,
       E301TCR.CODCLI AS CLIENTE,
       E085CLI.NOMCLI AS NOME_CLIENTE,
       E301TCR.DATEMI AS EMISSAO,
       E301TCR.VCTPRO AS VENCIMENTO,
       E301TCR.DATPPT AS PROV_PGTO,
       E301TCR.ULTPGT AS ULT_PGTO,
       E301TCR.SITTIT AS SITUACAO,
       E301TCR.CODFPG AS FORMA_PAGAMENTO,
       E301TCR.VLRORI AS VALOR_ORIGINAL,
       E301TCR.VLRABE AS VALOR_ABERTO,
	   E301TCR.VLRDSC AS DESCONTO,
	   (E301TCR.VLRORI + E301MCR.VLRJRS + E301MCR.VLRMUL + E301MCR.VLRENC + E301MCR.VLROAC - E301TCR.DSCNEG - E301TCR.VLRDSC - E301MCR.VLRODE) AS TOTAL,
	   E066FPG.DESFPG AS DESC_FORMA_PGTO,
	   E301TCR.DATENT AS ENTRADA,
	   E301TCR.VCTORI AS VCTO_ORIGINAL,
	   E001TNS.LISMOD AS MODALIDADE,
	   E301TCR.FILNFV AS FILIAL_NFS,
	   E301TCR.CODSNF AS SERIE_NFS,
	   E301TCR.NUMNFV AS NF_SAIDA,
	   E301TCR.FILNFC AS FILIAL_NFENTRADA,
	   E301TCR.FORNFC AS FORNECEDOR_NFENTRADA,
	   E301TCR.SNFNFC AS SERIE_NFENTRADA,
	   E085CLI.CODGRE AS GRUPO_EMPRESA,
	   E301TCR.VLROUD AS OUTROS_DESCONTOS,
	   E301MCR.VLROAC AS ACRESCIMOS,
	   E301TCR.JRSNEG AS JUROS_NEGOCIADO,
	   E301TCR.MULNEG AS MULTA_NEGOCIADA,
	   E301TCR.DSCNEG AS DESCONTOS_NEGOCIADOS,
	   E301TCR.PARCAR AS PARCELA_CARTAO,
	   E301TCR.CATTEF AS AUTORIZACAO_TEF,
	   E301TCR.NSUTEF AS NUMERACAO_TEF,
	   E301MCR.CODTNS AS TRANSACAO,
	   CASE
       	WHEN E001TNS.RECTPB  = 'PG' THEN 'Pagamento'
       	WHEN E001TNS.RECTPB = 'DV' THEN 'Devolução'
       	WHEN E001TNS.RECTPB = 'AB' THEN 'Abatimento'
       	WHEN E001TNS.RECTPB = 'CA' THEN 'Cancelamento'
       	WHEN E001TNS.RECTPB = 'CR' THEN 'Baixa Crédito'
       	WHEN E001TNS.RECTPB = 'CP' THEN 'Compensação'
       	WHEN E001TNS.RECTPB = 'LP' THEN 'Lucos e Perdas'
       	WHEN E001TNS.RECTPB = 'SU' THEN 'Substituição'
       	WHEN E001TNS.RECTPB = 'NA' THEN 'Não é baixa'
       END AS TIPO_TRANSACAO,
	   E001TNS.DESTNS AS DESCRICAO,
	   E301MCr.CODPOR AS PORTADOR,
       E039POR.DESPOR AS NOME_PORTADOR
       FROM (SAPIENS_PROD.E301TCR LEFT JOIN SAPIENS_PROD.E066FPG 
			               ON E066FPG.CODEMP = E301TCR.CODEMP
                          AND E066FPG.CODFPG = E301TCR.CODFPG),
            SAPIENS_PROD.E085CLI,
            SAPIENS_PROD.E001TNS,
            SAPIENS_PROD.E070FIL,
            SAPIENS_PROD.E090REP,
            SAPIENS_PROD.E301MCR,
            SAPIENS_PROD.E039POR
WHERE
	E301MCR.CODEMP = E301TCR.CODEMP
  	AND E301MCR.CODFIL = E301TCR.CODFIL
  	AND E301MCR.NUMTIT = E301TCR.NUMTIT
  	AND E301MCR.CODTPT = E301TCR.CODTPT
  	AND E085CLI.CODCLI = E301TCR.CODCLI
  	AND E090REP.CODREP = E301TCR.CODREP
  	AND E070FIL.CODEMP = E301TCR.CODEMP
  	AND E070FIL.CODFIL = E301TCR.CODFIL
  	AND E001TNS.CODEMP = E301MCR.CODEMP
  	AND E001TNS.CODTNS = E301MCR.CODTNS
  	AND E039POR.CODEMP = E301MCR.CODEMP
  	AND E039POR.CODPOR = E301MCR.CODPOR
  	AND E301TCR.CODEMP = 5
  	AND E001TNS.LISMOD <> 'CRP'
  	AND E301TCR.SITTIT <> 'CA'
	AND E301TCR.DATENT = TO_DATE('REPLACE_DATE_HERE', 'dd/mm/yyyy')
