SELECT A.CLIENTE AS codigo_cliente,
    DBO.SO_NUMERO(B.INSCRICAO_FEDERAL) AS cnpj,
    A.PRODUTO AS codigo_produto,
    ISNULL(C.EAN, A.PRODUTO) AS ean,
    SUM(A.VENDA_BRUTA) AS valor_bruto,
    SUM(A.VENDA_LIQUIDA) AS valor_liquido,
    CAST(SUM(A.QUANTIDADE) AS NUMERIC(15)) AS unidade_vendida,
    CAST(A.MOVIMENTO AS DATETIME) AS data_emissao,
    A.DOCUMENTO_NUMERO AS nota_fiscal,
    A.EMPRESA AS unidade,
    IIF(D.TIPO_OPERACAO = 10, 'S', 'N') AS bonificacao,
    '1' AS tipo_nota,
    C.NF_FATURAMENTO AS registro_procfit,
    ISNULL(
        (
            (SUM(A.VENDA_BRUTA) - SUM(A.VENDA_LIQUIDA)) / SUM(A.VENDA_BRUTA)
        ) * 100,
        0
    ) AS desconto,
    ISNULL(AVG(A.REPASSE), 0) AS repasse,
    ISNULL(AVG(C.ICMS_VALOR_SUFRAMA_DESCONTO), 0) AS suframa,
    ISNULL(AVG(A.DESCONTO_FINANCEIRO), 0) AS desconto_financeiro,
    ISNULL(AVG(A.DESCONTO_ARQUIVO), 0) AS desconto_arquivo,
    ISNULL(AVG(A.DESCONTO_INDUSTRIA), 0) AS desconto_industria,
    ISNULL(AVG(A.DESCONTO_DISTRIBUIDORA), 0) AS desconto_distribuidora,
    ISNULL(AVG(A.DESCONTO_INDUSTRIA_EXCECAO), 0) AS desconto_industria_excecao,
    ISNULL(AVG(A.DESCONTO_DISTRIBUIDORA_EXCECAO), 0) AS desconto_distribuidora_excecao,
	A.TIPO_ACAO_DESCONTO AS tipo_acao_desconto 
FROM VENDAS_ANALITICAS A WITH(NOLOCK)
    JOIN ENTIDADES B WITH(NOLOCK) ON B.ENTIDADE = A.CLIENTE
    JOIN NF_FATURAMENTO_PRODUTOS C WITH(NOLOCK) ON C.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM
    AND C.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM
    AND C.NF_FATURAMENTO = A.REG_MASTER_ORIGEM
    AND C.PRODUTO = A.PRODUTO
    JOIN OPERACOES_FISCAIS D WITH(NOLOCK) ON D.OPERACAO_FISCAL = A.OPERACAO_FISCAL
WHERE A.EMPRESA IN (SELECT OECEM.EMPRESA FROM OS_EMPRESAS_CENTROS_ESTOQUES_MAPAS AS OECEM)
    AND CAST(A.MOVIMENTO AS DATE) = 'REPLACE_START_DATE'
GROUP BY A.CLIENTE,
    DBO.SO_NUMERO(B.INSCRICAO_FEDERAL),
    A.PRODUTO,
    ISNULL(C.EAN, A.PRODUTO),
    CAST(A.MOVIMENTO AS DATETIME),
    A.DOCUMENTO_NUMERO,
    A.EMPRESA,
    IIF(D.TIPO_OPERACAO = 10, 'S', 'N'),
    C.NF_FATURAMENTO,
    A.TIPO_ACAO_DESCONTO

UNION ALL

SELECT A.CLIENTE AS codigo_cliente,
    DBO.SO_NUMERO(B.INSCRICAO_FEDERAL) AS cnpj,
    A.PRODUTO AS codigo_produto,
    ISNULL(
        (
            SELECT TOP 1 Z.EAN
            FROM PRODUTOS_EAN Z WITH(NOLOCK)
            WHERE Z.PRODUTO = A.PRODUTO
        ),
        A.PRODUTO
    ) AS ean,
    SUM(A.VENDA_BRUTA) AS valor_bruto,
    SUM(A.VENDA_LIQUIDA) AS valor_liquido,
    CAST(SUM(A.QUANTIDADE) AS NUMERIC(15)) AS unidade_vendida,
    CAST(A.MOVIMENTO AS DATETIME) AS data_emissao,
    ISNULL(C.NF_NUMERO_CLIENTE, C.NF_NUMERO) AS nota_fiscal,
    A.EMPRESA AS unidade,
    IIF(D.TIPO_OPERACAO = 10, 'S', 'N') AS bonificacao,
    '2' AS tipo_nota,
    C.NF_FATURAMENTO_DEVOLUCAO AS registro_procfit,
    ISNULL(AVG(A.DESCONTO), 0) AS desconto,
    ISNULL(AVG(A.REPASSE), 0) AS repasse,
    0 AS suframa,
    ISNULL(AVG(A.DESCONTO_FINANCEIRO), 0) AS desconto_financeiro,
    ISNULL(AVG(A.DESCONTO_ARQUIVO), 0) AS desconto_arquivo,
    ISNULL(AVG(A.DESCONTO_INDUSTRIA), 0) AS desconto_industria,
    ISNULL(AVG(A.DESCONTO_DISTRIBUIDORA), 0) AS desconto_distribuidora,
    ISNULL(AVG(A.DESCONTO_INDUSTRIA_EXCECAO), 0) AS desconto_industria_excecao,
    ISNULL(AVG(A.DESCONTO_DISTRIBUIDORA_EXCECAO), 0) AS desconto_distribuidora_excecao,
	A.TIPO_ACAO_DESCONTO AS tipo_acao_desconto 
FROM VENDAS_ANALITICAS A WITH(NOLOCK)
    JOIN ENTIDADES B WITH(NOLOCK) ON B.ENTIDADE = A.CLIENTE
    JOIN NF_FATURAMENTO_DEVOLUCOES C WITH(NOLOCK) ON C.FORMULARIO_ORIGEM = A.FORMULARIO_ORIGEM
				AND C.TAB_MASTER_ORIGEM = A.TAB_MASTER_ORIGEM
				AND C.NF_FATURAMENTO_DEVOLUCAO = A.REG_MASTER_ORIGEM
    JOIN OPERACOES_FISCAIS D WITH(NOLOCK) ON D.OPERACAO_FISCAL = A.OPERACAO_FISCAL
WHERE A.EMPRESA IN (SELECT OECEM.EMPRESA FROM OS_EMPRESAS_CENTROS_ESTOQUES_MAPAS AS OECEM)
    AND CAST(A.MOVIMENTO AS DATE) = 'REPLACE_START_DATE'
GROUP BY A.CLIENTE,
    DBO.SO_NUMERO(B.INSCRICAO_FEDERAL),
    A.PRODUTO,
    A.MOVIMENTO,
    ISNULL(C.NF_NUMERO_CLIENTE, C.NF_NUMERO),
    A.EMPRESA,
    IIF(D.TIPO_OPERACAO = 10, 'S', 'N'),
    C.NF_FATURAMENTO_DEVOLUCAO,
    A.TIPO_ACAO_DESCONTO