	SELECT 
		TNS.CODTNS AS COD_TRANSACAO,
		TNS.DESTNS AS DESC_TRANSACAO,
		TO_CHAR(T.DATENT,'DD/MM/YYYY') AS DATA_ENTRADA_TITULO,
		T.CODEMP AS EMPRESA,
		T.CODFIL AS FILIAL_ERP,
		FIL.SIGFIL AS NOME_FILIAL,
		M.SEQMOV AS SEQ_MOV,
		FIL.USU_UNINEG AS FILIAL_LINX,
		FIL.CIDFIL AS CIDADE_FILIAL,
		FIL.SIGUFS AS UF_FILIAL,
		COALESCE(RT.CODCCU, '0') AS COD_CC_TITULO,
		COALESCE(CCU.DESCCU, 'Sem centro de custo') AS DESCR_CC_RAT_TITULO,
		COALESCE(RT.CTARED, 0) AS COD_CONTABIL_TITULO,
		COALESCE(PLA.DESCTA, 'Sem conta contábil') AS DESCR_CONTA,
		RT.VLRRAT AS VALO_RATEIO_TITULO,
		TO_CHAR(T.DATEMI,'DD/MM/YYYY') AS DATA_EMISSAO_TITULO,
		T.NUMNFC AS NFE_TITULO,
		T.SNFNFC AS SERIE_NF_ENTRATA_TITULO,
		TO_CHAR(T.VCTORI,'DD/MM/YYYY') AS VENC_ORIGINAL,
		TO_CHAR(T.VCTPRO,'DD/MM/YYYY') AS VENC_PRORROGADA,
		TO_CHAR(T.ULTPGT,'DD/MM/YYYY') AS DATA_PAGTO,
		M.CODFPG AS COD_FORMA_PAGTO,
		COALESCE(FP.DESFPG, 'Sem forma de pagamento') AS DESCR_FORMA_PAGTO,
		T.SITTIT AS SITUACAO_TITULO,
		T.NUMTIT AS TITULO,
		T.CODTPT AS TIPO,
		TT.DESTPT AS DESCR_TIPO_TITULO,
		T.CODFOR AS COD_FORN,
		FO.NOMFOR AS NOME_FORNECEDOR,
		FO.APEFOR AS NOME_FANTASIA_FORN,
		FO.CGCCPF AS CPNJ_CPF,
		M.VLRIRF AS IRRF,
		M.VLRISS AS ISS,
		M.VLRINS AS INSS,
		M.VLRPIS AS PIS,
		M.VLRCOF AS COFINS,
		M.VLRCSL AS CSLL,
		M.ORIIRF AS OUTRAS_RETENCOES,
		T.VLRORI AS TOTAL_TITULO,
		T.VLRABE AS VALOR_ABERTO_TITULO,
		T.OBSTCP AS OBSERVACAO,
		M.VLRJRS AS JUROS,
		M.VLRMUL AS MULTA,
		M.VLRENC AS ENGARGO,
		M.VLROAC AS ACRESCIMO,
		M.VLRDSC AS DESCONTO,
		M.VLRODE AS OUTROS_DESCONTOS,
		COALESCE(UAPR.USUAPR, 0) AS COD_USU_APR_OC,
		COALESCE(UA.NOMUSU, 'SEM USUÁRIO APROVADOR') AS NOME_USU_APR_OC,
		COALESCE(UAPR.NIVAPR, 0) AS NIVEL_APROVADOR,
		'TITULOS SEM NOTA' AS TIPO,
		M.NUMLOT AS NUM_LOTE_CONTABIL		
	FROM SAPIENS_PROD.E501TCP T
	   INNER JOIN SAPIENS_PROD.E001TNS TNS
	   		   ON TNS.CODEMP = T.CODEMP 
	   		  AND TNS.CODTNS = T.CODTNS
	   INNER JOIN SAPIENS_PROD.E501MCP M 
	   		   ON M.CODEMP = T.CODEMP 
	   		  AND M.CODFIL = T.CODFIL 
	   		  AND M.NUMTIT = T.NUMTIT 
	   		  AND M.CODTPT = T.CODTPT 
	   		  AND M.CODFOR = T.CODFOR
	   INNER JOIN SAPIENS_PROD.E501RAT RT
	   		   ON RT.CODEMP = T.CODEMP 
	   		  AND RT.CODFIL = T.CODFIL 
	   		  AND RT.NUMTIT = T.NUMTIT 
	   		  AND RT.CODTPT = T.CODTPT 
	   		  AND RT.CODFOR = T.CODFOR
	   INNER JOIN SAPIENS_PROD.E002TPT TT
	   		   ON TT.CODTPT = T.CODTPT 
	   INNER JOIN SAPIENS_PROD.E095FOR FO
	   		   ON FO.CODFOR = T.CODFOR
	   INNER JOIN SAPIENS_PROD.E070FIL FIL
	   		   ON FIL.CODEMP = T.CODEMP 
	   		  AND FIL.CODFIL = T.CODFIL
	   INNER JOIN SAPIENS_PROD.E044CCU CCU
	   		   ON CCU.CODEMP = RT.CODEMP
	   		  AND CCU.CODCCU = RT.CODCCU
	   INNER JOIN SAPIENS_PROD.E045PLA PLA
	           ON PLA.CODEMP = RT.CODEMP
	          AND PLA.CTARED = RT.CTARED
		LEFT JOIN SAPIENS_PROD.E066FPG FP 
			   ON FP.CODEMP = T.CODEMP 
			  AND FP.CODFPG = T.CODFPG
		LEFT JOIN SAPIENS_PROD.E614USU UAPR 
	   		   ON UAPR.CODEMP = T.CODEMP 
	   		  AND UAPR.ROTNAP = T.ROTNAP
	   		  AND UAPR.NUMAPR = T.NUMAPR
	   LEFT JOIN SAPIENS_PROD.R999USU UA
	   	       ON UA.CODUSU = UAPR.USUAPR
	WHERE M.SEQMOV = (SELECT MIN(M1.SEQMOV) FROM SAPIENS_PROD.E501MCP M1
										   WHERE M1.CODEMP = M.CODEMP
											 AND M1.CODFIL = M.CODFIL
											 AND M1.NUMTIT = M.NUMTIT
											 AND M1.CODTPT = M.CODTPT
											 AND M1.CODFOR = M.CODFOR)
	AND	RT.SEQMOV = (SELECT MIN(RT1.SEQMOV) FROM SAPIENS_PROD.E501RAT RT1
		                                   WHERE RT1.CODEMP = RT.CODEMP 
		                                     AND RT1.CODFIL = RT.CODFIL 
		                                     AND RT1.NUMTIT = RT.NUMTIT 
		                                     AND RT1.CODTPT = RT.CODTPT 
		                                     AND RT1.CODFOR = RT.CODFOR)
	AND T.CODEMP IN (2, 5) --Empresa Drogaria Globo
	AND T.USUGER <> 388 --Usuário LINX mercadaria para revenda, não são despesas
	AND RT.CTARED >=536 --Contas contábis entre 536 até 1010 são despesas 
	AND RT.CTARED <=1010
	AND T.CODTPT <> 'DDA' --Retirando tílulos DDA (Débitos Diretos Autorizado), pois é possível que não ainda não deram entrada de notas
	AND T.CODTPT <> 'IRF'
	AND T.CODTPT <> 'IRR'
	AND T.CODTPT <> 'ISS'
	AND T.CODTPT <> 'PCC'
	AND T.CODTPT <> 'INS'
	AND T.CODTPT <> 'PCC'
	AND T.DATENT BETWEEN TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd') AND TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd')


