SELECT
    A.PEDIDO_VENDA_VALIDACAO                     AS pedido_venda_validacao,
    A.PEDIDO_VENDA                               AS pedido_venda,
    F.PRODUTO                                    AS produto,
    --L.DESCRICAO                                  AS descricao_produto,
    null                                  AS descricao_produto,
    ISNULL(M.DESCRICAO, 'Sem Motivo')            AS motivo,
    CAST(F.VALOR_UNITARIO AS NUMERIC(15,2))      AS valor_unitario,
    CAST(F.DESCONTO AS NUMERIC(15,2))            AS desconto,
    CAST(F.TOTAL_DESCONTO AS NUMERIC(15,2))      AS total_desconto,
    CAST(F.QUANTIDADE_ATENDIDA AS NUMERIC(15,2)) AS quantidade_atendida,
    CAST(F.QUANTIDADE_DIGITADA AS NUMERIC(15,2)) AS quantidade_digitada,
    CAST(F.QUANTIDADE_ATENDIDA * F.VALOR_UNITARIO AS NUMERIC(15,2)) AS valor_atendido,
    CAST(F.TOTAL_PRODUTO AS NUMERIC(15,2))                          AS valor_digitado,
    A.CONDICAO_PAGAMENTO						  AS condicao_pagamento
FROM      PEDIDOS_VENDAS_VALIDACOES          A WITH(NOLOCK)
JOIN      PEDIDOS_VENDAS_VALIDACOES_PRODUTOS F WITH(NOLOCK) ON F.PEDIDO_VENDA_VALIDACAO = A.PEDIDO_VENDA_VALIDACAO
JOIN      ORIGENS_VENDAS_CANAIS              D WITH(NOLOCK) ON D.ORIGEM_VENDA_CANAL     = A.ORIGEM_VENDA_CANAL
JOIN      VENDEDORES                         I WITH(NOLOCK) ON I.VENDEDOR               = A.VENDEDOR
JOIN      ENTIDADES                          K WITH(NOLOCK) ON K.ENTIDADE               = A.ENTIDADE
JOIN      PRODUTOS                           L WITH(NOLOCK) ON L.PRODUTO                = F.PRODUTO
LEFT JOIN MOTIVOS_VALIDACOES_PEDIDOS_VENDAS  M WITH(NOLOCK) ON M.MOTIVO_VALIDACAO       = F.MOTIVO
LEFT JOIN PEDIDOS_VENDAS                     E WITH(NOLOCK) ON E.PEDIDO_VENDA_VALIDACAO = A.PEDIDO_VENDA_VALIDACAO
LEFT JOIN VENDEDORES                         J WITH(NOLOCK) ON J.VENDEDOR               = E.DONO
LEFT JOIN PEDIDOS_VENDAS_STATUS              G WITH(NOLOCK) ON G.PEDIDO_VENDA           = A.PEDIDO_VENDA
LEFT JOIN STATUS_PEDIDOS_VENDAS              H WITH(NOLOCK) ON H.STATUS_PEDIDO_VENDA    = G.STATUS_PEDIDO_VENDA
LEFT JOIN CONDICOES_PAGAMENTO                B WITH(NOLOCK) ON B.CONDICAO_PAGAMENTO     = A.CONDICAO_PAGAMENTO
LEFT JOIN CONDICOES_COMERCIAIS               C WITH(NOLOCK) ON C.CONDICAO_COMERCIAL     = A.CONDICAO_COMERCIAL
    WHERE CAST(A.DATA_HORA AS DATE) = 'REPLACE_START_DATE'
    --BETWEEN CAST(GETDATE() - 10 AS DATE) AND CAST(GETDATE() + 1 AS DATE)
    GROUP BY A.PEDIDO_VENDA, F.PRODUTO, L.DESCRICAO, F.VALOR_UNITARIO, F.QUANTIDADE_ATENDIDA, F.QUANTIDADE_DIGITADA, F.TOTAL_DESCONTO, F.DESCONTO, F.TOTAL_PRODUTO, A.PEDIDO_VENDA_VALIDACAO, M.DESCRICAO, A.CONDICAO_PAGAMENTO
