SELECT 
	CODEMP AS EMPRESA,
	CTARED AS RED,
	DESCTA AS DESCRICAO,
	MSKGCC AS MASCARA,
	CLACTA AS CLASSIFICACAO,
	CASE 
		WHEN ANASIN = 'A' THEN 'Analico(a)'
		WHEN ANASIN = 'S' THEN 'Sintetico(a)'
	END AS TIPO,
	NATCTA AS NATUREZA
	FROM SAPIENS_PROD.E045PLA
