SELECT
    S.PROSER AS PRODUTO_OU_SERVICO,
		S.codemp AS EMPRESA,
		S.filsol AS FILIAL,
		S.CODDEP AS DEPOSITO,
		S.numsol AS NUM_SILICITACAO,
		S.CODPRO AS PRODUTO_SERVICO,
		S.SEQSOL AS SEQ,
		S.CPLPRO AS DESCRICAO_SERVICO_PRODUTO,
		S.CODDER AS DERIVACAO,
		S.QTDSOL AS QNT_SOLICITADA,
		C.qtdcot AS QNT_COTADA,
		S.OBSSOL AS OBSERVACAO_SOLICITACAO,
		S.DATSOL AS DATA_SOLICITACAO,
		C.datcot AS DATA_COTACAO,
		OC.DATEMI AS DATA_EMISSAO_OCP,
		S.DATPRV AS DATA_PREV_ENTREGA_SOLICITACAO,
		OCP.DATENT AS PREV_ENTREGA_PRODUTO_SERVICO,
		C.numcot AS NUM_COTACAO,
		C.codfor AS FORNECEDOR,
		C.PRZENT AS PRAZO_ENTREGA,
		C.codcpg AS COD_COND_PAG,
		CPG.DESCPG AS DESCR_COND_PAG,
		C.codder AS DERIVACAO_COT,
		C.precot AS PRECO_COTADO,
		C.VLRCOT AS VALOR_COTACAO,
		C.VLRPRS,
		C.VLRDSC AS VALOR_DESCONTO,
		C.VDIFCP AS VALOR_FCP,
		C.DSCCOT AS PERC_DESC_COT,
		C.usucot AS USUARIO_COTACAO,
		RU.NOMUSU AS NOME_USUARIO,
		C.ciffob,
		oc.NUMOCP AS NUM_ORDEM_DE_COMP,
		OC.CODFIL AS FILIAL_OCP,
		OC.OBSOCP AS OBSERVACAO_OCP
	FROM SAPIENS_PROD.E405SOL S
		INNER JOIN SAPIENS_PROD.E405RAT R
				ON R.CODEMP = S.CODEMP 
			   AND R.NUMSOL = S.NUMSOL
			   AND R.SEQSOL = S.SEQSOL 
		 LEFT JOIN SAPIENS_PROD.E410COT C 
				ON C.CODEMP = S.CODEMP 
			   AND C.NUMCOT = S.NUMCOT
		INNER JOIN SAPIENS_PROD.E028CPG CPG
				ON CPG.CODEMP = C.CODEMP 
			   AND CPG.CODCPG = C.CODCPG
		 LEFT JOIN SAPIENS_PROD.E420OCP OC
		 		ON OC.CODEMP = C.CODEMP 
		 	   AND OC.NUMOCP = C.NUMOCP
		 	   AND OC.CODFIL = C.FILOCP
		INNER JOIN SAPIENS_PROD.E420IPO OCP
		 		ON OCP.CODEMP = OC.CODEMP 
		 	   AND OCP.CODFIL = OC.CODFIL
		 	   AND OCP.NUMOCP = OC.NUMOCP
		INNER JOIN SAPIENS_PROD.E410LCO L
				ON L.CODEMP = OCP.CODEMP 
				AND L.NUMCOT = C.NUMCOT 
				AND L.SEQCOT = C.SEQCOT
				AND L.FILOCP = C.FILOCP 
				AND L.NUMOCP = C.NUMOCP 
				AND L.SEQIPO = OCP.SEQIPO
		INNER JOIN SAPIENS_PROD.R999USU ru 
				ON ru.CODUSU = c.USUCOT
	WHERE 
		S.codemp in (2, 5)
    AND S.DATSOL >= TO_DATE('2024-01-01', 'yyyy-mm-dd')
    AND S.DATSOL = TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd')

	  UNION ALL

	SELECT 
		S.PROSER AS PRODUTO_OU_SERVICO,
	    S.codemp AS EMPRESA,
		S.filsol AS FILIAL,
		S.CODDEP AS DEPOSITO,
		S.numsol AS NUM_SILICITACAO,
		S.CODSER AS PRODUTO_SERVICO,
		S.SEQSOL AS SEQ,
		S.CPLPRO AS DESCRICAO_SERVICO_PRODUTO,
		S.CODDER AS DERIVACAO,
		S.QTDSOL AS QNT_SOLICITADA,
		C.qtdcot AS QNT_COTADA,
		S.OBSSOL AS OBSERVACAO_SOLICITACAO,
		S.DATSOL AS DATA_SOLICITACAO,
		C.datcot AS DATA_COTACAO,
		OC.DATEMI AS DATA_EMISSAO_OCP,
		S.DATPRV AS DATA_PREV_ENTREGA_SOLICITACAO,
		OCS.DATENT AS PREV_ENTREGA_SERVICO_PRODUTO,
		C.numcot AS NUM_COTACAO,
		C.codfor AS FORNECEDOR,
		C.PRZENT AS PRAZO_ENTREGA,
		C.codcpg AS COD_COND_PAG,
		CPG.DESCPG AS DESCR_COND_PAG,
		C.codder AS DERIVACAO_COT,
		C.precot AS PRECO_COTADO,
		C.VLRCOT AS VALOR_COTACAO,
		C.VLRPRS,
		C.VLRDSC AS VALOR_DESCONTO,
		C.VDIFCP AS VALOR_FCP,
		C.DSCCOT AS PERC_DESC_COT,
		C.usucot AS USUARIO_COTACAO,
		ru.NOMUSU AS NOME_USUARIO,
		C.ciffob,
		oc.NUMOCP AS NUM_ORDEM_DE_COMP,
		OC.CODFIL AS FILIAL_OCP,
		OC.OBSOCP AS OBSERVACAO_OCP
	FROM SAPIENS_PROD.E405SOL S
	    INNER JOIN SAPIENS_PROD.E405RAT R
				ON R.CODEMP = S.CODEMP 
			   AND R.NUMSOL = S.NUMSOL
			   AND R.SEQSOL = S.SEQSOL
		 LEFT JOIN SAPIENS_PROD.E410COT C 
				ON C.CODEMP = S.CODEMP 
			   AND C.NUMCOT = S.NUMCOT
		INNER JOIN SAPIENS_PROD.E028CPG CPG
				ON CPG.CODEMP = C.CODEMP 
			   AND CPG.CODCPG = C.CODCPG
		 LEFT JOIN SAPIENS_PROD.E420OCP OC
		 		ON OC.CODEMP = C.CODEMP 
		 	   AND OC.NUMOCP = C.NUMOCP
		 	   AND OC.CODFIL = C.FILOCP
		INNER JOIN SAPIENS_PROD.E420ISO OCS
		 		ON OCS.CODEMP = OC.CODEMP 
		 	   AND OCS.CODFIL = OC.CODFIL
		 	   AND OCS.NUMOCP = OC.NUMOCP
		INNER JOIN SAPIENS_PROD.E410LCO L
				ON L.CODEMP = OCS.CODEMP 
				AND L.NUMCOT = C.NUMCOT 
				AND L.SEQCOT = C.SEQCOT
				AND L.FILOCP = C.FILOCP 
				AND L.NUMOCP = C.NUMOCP 
				AND L.SEQISO = OCS.SEQISO
		INNER JOIN SAPIENS_PROD.R999USU ru 
				ON ru.CODUSU = c.USUCOT 
	WHERE 
		S.codemp in (2, 5)
	  	AND S.DATSOL >= TO_DATE('2024-01-01', 'yyyy-mm-dd')
    AND S.DATSOL = TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd')
	  	
	
