SELECT
	NUMEMP AS EMPRESA,
	NUMCAD AS MATRICULA,
	CASE 
		WHEN TIPRCS = 1 THEN 'Rescisão Normal'
		WHEN TIPRCS = 2 THEN 'Rescisão Complementar'
		WHEN TIPRCS = 3 THEN 'Indenização'
	END AS TIPO_RESCISAO,
	TO_CHAR(PAGRCS, 'DD/MM/YYYY') AS DATA_PAGAMENTO,
	FRDVLR AS VALOR_FGTS_RECOLHIDO
FROM
	VETORH_PROD.R056RCS
WHERE
	NUMEMP IN (2, 5)
	AND TIPCOL = 1
