SELECT 
	TNS.CODTNS AS COD_TRANSACAO,
	TNS.DESTNS AS DESC_TRANSACAO,
	TO_CHAR(T.DATENT,'DD/MM/YYYY') AS DATA_ENTRADA_TITULO,
	T.CODEMP AS EMPRESA,
	T.CODFIL AS FILIAL_ERP,
	FIL.SIGFIL AS NOME_FILIAL,
	M.SEQMOV AS SEQ_MOV,
	FIL.USU_UNINEG AS FILIAL_LINX,
	FIL.CIDFIL AS CIDADE_FILIAL,
	FIL.SIGUFS AS UF_FILIAL,
	COALESCE(RNFS.CODCCU, '0') AS COD_CC_NFE,
	COALESCE(CCU.DESCCU, 'Sem centro de custo') AS DESCR_CC_RAT_NOTA,
	COALESCE(RNFS.CTARED, 0) AS COD_CONTABIL_NFE,
	COALESCE(PLA.DESCTA, 'Sem conta contábil') AS DESCR_CONTA,
	RNFS.VLRRAT AS VALOR_RAT_NFE,
	TO_CHAR(T.DATEMI,'DD/MM/YYYY') AS DATA_EMISSAO_TITULO,
	T.NUMNFC AS NFE_TITULO,
	T.SNFNFC AS SERIE_NF_ENTRATA_TITULO,
	TO_CHAR(T.VCTORI,'DD/MM/YYYY') AS VENC_ORIGINAL,
	TO_CHAR(T.VCTPRO,'DD/MM/YYYY') AS VENC_PRORROGADA,
	TO_CHAR(T.ULTPGT,'DD/MM/YYYY') AS DATA_PAGTO,
	M.CODFPG AS COD_FORMA_PAGTO,
	COALESCE(FP.DESFPG, 'Sem forma de pagamento') AS DESCR_FORMA_PAGTO,
	T.SITTIT AS SITUACAO_TITULO,
	T.NUMTIT AS TITULO,
	T.CODTPT AS TIPO,
	TT.DESTPT AS DESCR_TIPO_TITULO,
	T.CODFOR AS COD_FORN,
	FO.NOMFOR AS NOME_FORNECEDOR,
	FO.APEFOR AS NOME_FANTASIA_FORN,
	FO.CGCCPF AS CPNJ_CPF,
	COALESCE(NFS.VLRDFA, 0) AS DIFERENCIAL_ICMS,
	NFS.VLRIRF AS IRRF,
	NFS.VLRISS AS ISS,
	NFS.VLRINS AS INSS,
	NFS.VLRPIS AS PIS_RECUPERAR,
	NFS.VLRCOR AS COFINS_RECUPERAR,
	NFS.VLRCSL AS CSLL,
	NFS.VLROUR AS OUTRAS_RETENCOES,
	T.OBSTCP AS OBSERVACAO,
	M.VLRJRS AS JUROS,
	M.VLRMUL AS MULTA,
	M.VLRENC AS ENGARGO,
	M.VLROAC AS ACRESCIMO,
	M.VLRDSC AS DESCONTO,
	M.VLRODE AS OUTROS_DESCONTOS,
	COALESCE(NFS.NUMOCP, 0) AS NUM_ORDEM_COMPRA,
	COALESCE(NFS.NUMCTR, 0) AS NUM_CONTRATO,
	COALESCE(TO_CHAR(OCP.DATEMI,'DD/MM/YYYY'),'00/00/0000')  AS DATA_EMISSAO_OC,
	NFS.NUMNFC AS NOTA_FISCAL,
	NFS.SEQISC AS NFE_SEQ_SERVICO,
	NFS.CODSER AS SERVICO,
	NFS.CODFAM AS FAM_SERVICO,
	FAM.DESFAM AS DESCR_FAM_SERV,
	NFS.CPLISC AS DESCR_SERVICO,
	COALESCE(OCP.USUGER, 0) AS COD_USU_GER_OC,
	COALESCE(UOC.NOMUSU, 'Sem usuário') AS NOME_GER_OC,
	COALESCE(UAPR.USUAPR, 0) AS COD_USU_APR_OC,
	COALESCE(UA.NOMUSU, 'Sem aprovador') AS NOME_USU_APR_OC,
	COALESCE(UAPR.NIVAPR, 0) AS NIVEL_APROV_ORDEM_COMPRA,
	COALESCE(CTR.USUGER, 0) AS COD_USU_GER_CONTR,
	COALESCE(UCTR.NOMUSU, 'Sem usuário') AS NOME_USU_GER_CONTR,
	COALESCE(UAPRCTR.USUAPR, 0) AS COD_USU_APR_CONTR,
	COALESCE(UACTR.NOMUSU, 'Sem aprovador') AS NOME_USU_APR_CONTR,
	COALESCE(UAPRCTR.NIVAPR, 0) AS NIVEL_APROV_CONTRATO,
	COALESCE(OCP.PRCOCP, 0) AS COD_PROCED_OC,
	CASE 
		WHEN OCP.PRCOCP = 1 THEN 'Digitado'
		WHEN OCP.PRCOCP = 3 THEN 'Via Cotação'
		WHEN OCP.PRCOCP = 9 THEN 'Via Solicitação de Compra'
		ELSE 'Não tem ordem de compra'
	END	AS PROCEDENCIA_OC,
	'SERVICO' AS TIPO,
	COALESCE(OCP.SITOCP, 0) AS COD_SIT_OC,
	CASE
		WHEN OCP.SITOCP IS NULL THEN 'Sem Ordem de Compra'
		WHEN OCP.sitocp = 1 THEN 'Aberto total'
		WHEN OCP.sitocp = 2 THEN 'Aberto parcial'
		WHEN OCP.sitocp = 3 THEN 'Suspenso'
		WHEN OCP.sitocp = 4 THEN 'Liquidado'
		WHEN OCP.sitocp = 5 THEN 'Cancelado'
		WHEN OCP.sitocp = 6 THEN 'Aguardando integracao WMS'
		WHEN OCP.sitocp = 7 THEN 'Em transmissao'
		WHEN OCP.sitocp = 8 THEN 'Preparacao Analise ou NF'
		WHEN OCP.sitocp = 9 THEN 'Nao fechado' 
	END	AS SITUACAO_OC,
	COALESCE(M.NUMLOT, 0) AS LOTE_CONTABIL_TITULO,
	COALESCE(NDG.NUMLOT, 0) AS LOTE_CONTABIL_NOTA
FROM SAPIENS_PROD.E501TCP T
   INNER JOIN SAPIENS_PROD.E001TNS TNS
   		   ON TNS.CODEMP = T.CODEMP 
   		  AND TNS.CODTNS = T.CODTNS
   INNER JOIN SAPIENS_PROD.E501MCP M 
   		   ON M.CODEMP = T.CODEMP 
   		  AND M.CODFIL = T.CODFIL 
   		  AND M.NUMTIT = T.NUMTIT 
   		  AND M.CODTPT = T.CODTPT 
   		  AND M.CODFOR = T.CODFOR
   INNER JOIN SAPIENS_PROD.E002TPT TT
   		   ON TT.CODTPT = T.CODTPT 
   INNER JOIN SAPIENS_PROD.E095FOR FO
   		   ON FO.CODFOR = T.CODFOR
   INNER JOIN SAPIENS_PROD.E070FIL FIL
   		   ON FIL.CODEMP = T.CODEMP 
   		  AND FIL.CODFIL = T.CODFIL
   INNER JOIN SAPIENS_PROD.E440NFC NDG 
   		   ON NDG.CODEMP = T.CODEMP
   		  AND NDG.CODFIL = T.CODFIL
   		  AND NDG.CODFOR = T.CODFOR
  		  AND NDG.NUMNFC = T.NUMNFC  
   INNER JOIN SAPIENS_PROD.E440ISC NFS 
	       ON NFS.CODEMP = NDG.CODEMP 
	      AND NFS.CODFIL = NDG.CODFIL 
	      AND NFS.CODFOR = NDG.CODFOR 
	      AND NFS.NUMNFC = NDG.NUMNFC
	      AND NFS.CODSNF = NDG.CODSNF 
   INNER JOIN SAPIENS_PROD.E001TNS TNF
		   ON TNF.CODEMP = NFS.CODEMP 
	   	  AND TNF.CODTNS = NFS.TNSSER
   INNER JOIN SAPIENS_PROD.E012FAM FAM 
    	   ON FAM.CODEMP = NFS.CODEMP
    	  AND FAM.CODFAM = NFS.CODFAM
    LEFT JOIN SAPIENS_PROD.E420OCP OCP ---ordem de compra
   		   ON OCP.CODEMP = NFS.CODEMP 
   		  AND OCP.CODFIL = NFS.CODFIL
   		  AND OCP.NUMOCP = NFS.NUMOCP
    LEFT JOIN SAPIENS_PROD.R999USU UOC
   	       ON UOC.CODUSU = OCP.USUGER 
    LEFT JOIN SAPIENS_PROD.E614USU UAPR 
   		   ON UAPR.CODEMP = OCP.CODEMP 
   		  AND UAPR.ROTNAP = OCP.ROTNAP
   		  AND UAPR.NUMAPR = OCP.NUMAPR
   		  AND (UAPR.NIVAPR = 1 OR UAPR.NIVAPR IS NULL)
    LEFT JOIN SAPIENS_PROD.R999USU UA
   	       ON UA.CODUSU = UAPR.USUAPR
    LEFT JOIN SAPIENS_PROD.E460CTR CTR ---contrato
   		   ON CTR.CODEMP = NFS.CODEMP 
   		  AND CTR.CODFIL = NFS.CODFIL 
   		  AND CTR.NUMCTR = NFS.NUMCTR
    LEFT JOIN SAPIENS_PROD.R999USU UCTR
   	       ON UCTR.CODUSU = CTR.USUGER
    LEFT JOIN SAPIENS_PROD.E614USU UAPRCTR 
   		   ON UAPRCTR.CODEMP = CTR.CODEMP 
   		  AND UAPRCTR.ROTNAP = CTR.ROTNAP
   		  AND UAPRCTR.NUMAPR = CTR.NUMAPR
   		  AND (UAPRCTR.NIVAPR = 1 OR UAPRCTR.NIVAPR IS NULL)
    LEFT JOIN SAPIENS_PROD.R999USU UACTR
   	       ON UACTR.CODUSU = UAPRCTR.USUAPR
   INNER JOIN SAPIENS_PROD.E440RAT RNFS
   		   ON RNFS.CODEMP = NFS.CODEMP 
   		  AND RNFS.CODFIL = NFS.CODFIL 
   		  AND RNFS.CODFOR = NFS.CODFOR 
   		  AND RNFS.NUMNFC = NFS.NUMNFC
   		  AND RNFS.CODSNF = NFS.CODSNF
   		  AND RNFS.SEQISC = NFS.SEQISC
   INNER JOIN SAPIENS_PROD.E044CCU CCU
   		   ON CCU.CODEMP = RNFS.CODEMP
   		  AND CCU.CODCCU = RNFS.CODCCU
   INNER JOIN SAPIENS_PROD.E045PLA PLA
           ON PLA.CODEMP = RNFS.CODEMP
          AND PLA.CTARED = RNFS.CTARED
	LEFT JOIN SAPIENS_PROD.E066FPG FP 
		   ON FP.CODEMP = T.CODEMP 
		  AND FP.CODFPG = T.CODFPG
WHERE M.SEQMOV = (SELECT MIN(M1.SEQMOV) FROM SAPIENS_PROD.E501MCP M1
									   WHERE M1.CODEMP = M.CODEMP
										 AND M1.CODFIL = M.CODFIL
										 AND M1.NUMTIT = M.NUMTIT
										 AND M1.CODTPT = M.CODTPT
										 AND M1.CODFOR = M.CODFOR) 
	AND T.VCTORI = (SELECT MIN(t1.VCTORI)  FROM SAPIENS_PROD.E501TCP T1
							WHERE T1.CODEMP = T.CODEMP
							  AND T1.CODFIL = T.CODFIL 
							  AND T1.NUMNFC = T.NUMNFC
							  AND T1.CODTPT = T.CODTPT
							  AND T1.CODFOR = T.CODFOR)
	AND T.CODEMP IN (2, 5)
	AND ((UAPR.NIVAPR = 1 OR UAPR.NIVAPR IS NULL)  OR (UAPRCTR.NIVAPR = 1 OR UAPRCTR.NIVAPR IS NULL))
	AND T.USUGER <> 388
	AND RNFS.CTARED >= 536
	AND RNFS.CTARED <=1010
	AND TNF.CPRTCF <> 'I'
	AND T.DATENT = TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd') 
	
