SELECT 
	CODEMP AS EMPRESA,
	CODCCU AS COD_CUSTO,
	DESCCU AS DESCR_CUSTO,
	ANASIN AS TIPO,
	CASE 
		WHEN ACERAT = 'S' THEN 'Sim'
		WHEN ACERAT = 'N' THEN 'Não'
 	END AS ACEITA_RAT,
 	TO_CHAR(DATALT,'DD/MM/YYYY') AS DATA_ALT
FROM SAPIENS_PROD.E044CCU
