SELECT 
	CODEMP AS EMPRESA,
	CODCCU AS COD_CUSTO,
	DESCCU AS DESCR_CUSTO,
	ANASIN AS TIPO,
	CASE 
		WHEN ACERAT = 'S' THEN 'Sim'
		WHEN ACERAT = 'N' THEN 'Não'
 	END AS ACEITA_RAT,
 	TO_CHAR(DATALT,'DD/MM/YYYY') AS DATA_ALT,
 	TIPCCU AS TIPO_CUSTO,
 	CASE 
 		WHEN TIPCCU = 1 THEN 'Produtivo/Operacional Indireto'
 		WHEN TIPCCU = 2 THEN 'Produtivo/Operacional Direto'
 		WHEN TIPCCU = 3 THEN 'Administrativo'
 		WHEN TIPCCU = 4 THEN 'Comercial'
 		WHEN TIPCCU = 5 THEN 'Financeiro'
 	END AS DESCR_TIPO_CUSTO,
 	CCUPAI AS CUSTO_PAI
FROM SAPIENS_PROD.E044CCU
WHERE CODEMP IN (2,5)
--	AND CODCCU IN ('174','285','33','1')
