$schema: ../../../../schemas/entity.json
name: configuracoes_ol_excecoes_clientes
target_table: configuracoes_ol_excecoes_clientes
source: PbsNazariaDados
target: biMktNaz
process_type: full
sql_file: consulta_configuracoes_ol_excecoes_clientes.sql
columns:
  - configuracao_ol_excecao_cliente
  - formulario_origem
  - tab_master_origem
  - reg_master_origem
  - reg_log_inclusao
  - configuracao_ol_excecao
  - entidade
  - cliente_rede
  - grupo_cliente
  - contador_f6
  - tipo_restricao
