$schema: ../../../../schemas/entity.json
name: configuracoes_ol_excecoes_unidades
target_table: configuracoes_ol_excecoes_unidades
source: PbsNazariaDados
target: biMktNaz
process_type: full
sql_file: consulta_configuracoes_ol_excecoes_unidades.sql
columns:
  - formulario_origem
  - tab_master_origem
  - reg_master_origem
  - reg_log_inclusao
  - empresa
  - tipo_restricao