$schema: ../../../../schemas/entity.json
name: configuracoes_ol_excecoes_ols
target_table: configuracoes_ol_excecoes_ols
source: PbsNazariaDados
target: biMktNaz
process_type: full
sql_file: consulta_configuracoes_ol_excecoes_ols.sql
columns:
  - configuracao_ol_excecao_ol
  - formulario_origem
  - tab_master_origem
  - reg_master_origem
  - reg_log_inclusao
  - configuracao_ol_excecao
  - configuracao_ol
  - tipo_acao_desconto
  - contador_f5
