$schema: ../../../../schemas/entity.json
name: produto
target_table: produto
source: PbsNazariaDados
target: biMktNaz
process_type: full
sql_file: consulta_produto.sql
columns:
  - codigo_produto
  - ean
  - dum
  - descricao
  - familia
  - molecula
  - franquia
  - categoria
  - classificacao
  - situacao
  - curva
  - legenda
  - embalagem
  - laboratorio_id
  - grupo_produto
  - subgrupo_produto
  - situacao_compra
  - produto_resumo
  - produto_resumo_descricao
  - preco_monitorado
  - cst_origem
  - grupo_tributario
  - grupo_tributario_entrada
  - grupo_tributario_importados
  - ncm
  - codigo_cest
  - classe_produto
  - secao_produto
  - fabricante
  - classe_produto_descricao
  - secao_produto_descricao
  - fabricante_produto_descricao
  - marca
  - marca_descricao
  - dimensao_altura
  - dimensao_profundidade
  - dimensao_largura
  - peso_bruto
  - peso_liquido
