$schema: ../../../../schemas/entity.json
name: produtos
target_table: produtos
source: PbsNazariaDados
target: biNazaria
process_type: full
sql_file: consulta_produtos.sql
columns:
  - produto
  - ean
  - descricao
  - unidade_medida
  - unidade_medida_fator
  - fator_embalagem
  - embalagem_industria
  - clas_prod_est
  - sessao_prod
  - grupo_produto
  - classe_prod
  - fabricante
  - cd_marca
  - marca
  - sts_prod
  - sts_prod_compra
  - comprador
  - legenda
  - divisao
  - prod_resumo