SELECT 
	A.NUMEMP AS EMPRESA,
	A.NUMCAD AS MATRICULA,
	TO_CHAR(RCM.DATDEM, 'DD/MM/YYYY')  AS DATA_DEMISSAO,
	RCM.CAUDEM AS COD_CAUSA,
	CAU.DESDEM AS DESCR_CAUSA,
	RMD.CODRMD AS COD_MOTIVO,
	RMD.DESRMD AS DESCR_MOTIVO,
	RCM.DATAVI AS DATA_AVISO,
	RCM.FINAVI AS DATA_FIM_AVISO,
	RCM.QTDREA AS DIAS_AVISO,
	RCM.BINSLD AS BASE_INSS_SALDO,
	RCM.BIN13S AS BASE_INSS_13SAL,
	RCM.BIRSLD AS BASE_IR_SALDO,
	RCM.AIRSLD AS ABATIM_IR_SALDO,
	RCM.BIR13S AS BASE_IR_13SAL,
	RCM.AIR13S AS ABATIM_IR_13SAL,
	RCM.BIRFER AS BASE_IR_FERIAS,
	RCM.AIRFER AS ABATIM_IR_FERIAS,
	RCM.BIRPAR AS BASE_IR_PARTIC_LUCROS,
	RCM.BASFGT AS BASE_FGTS,
	RCM.ABAFGT AS ABATIM_FGTS,
	RCM.BASFGD AS BASE_FGTS_13SAL,
	RCM.ABAFGD AS ABATIM_FGTS_13SAL,
	RCM.TOTPRO AS TOTAL_PROVENTOS,
	RCM.TOTDES AS TOTAL_DESCONTO,
	(RCM.TOTPRO - RCM.TOTDES) AS TOTAL_LIQUIDO
FROM 
	VETORH_PROD.R034FUN A
LEFT JOIN VETORH_PROD.R042RCM RCM ---Rescisao mestre
	ON RCM.NUMEMP = A.NUMEMP
	AND RCM.TIPCOL = A.TIPCOL 
	AND RCM.NUMCAD = A.NUMCAD
LEFT JOIN VETORH_PROD.R042RCS RCS ---Rescisao complementar 
	ON RCS.NUMEMP = A.NUMEMP 
	AND RCS.TIPCOL = A.TIPCOL 
	AND RCS.NUMCAD = A.NUMCAD
INNER JOIN VETORH_PROD.R042CAU CAU --causa da demissão
		ON CAU.CAUDEM = RCM.CAUDEM 
INNER JOIN VETORH_PROD.R114RMD RMD ---motivo da demissão
		ON RMD.CODRMD = RCM.CODRMD
WHERE
	A.NUMEMP = 5 
	AND A.TIPCOL = 1
	AND A.SITAFA = 7
AND DATDEM = TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd')

