SELECT sol.CODFIL AS COD_FILIAL,
	   fil.CODEST AS UF,
	   fil.NOMFIL AS FILIAL,
	   TO_CHAR(sol.DATSVA,'DD/MM/YYYY') AS DATA_SOLICITACAO,
	   sol.CODSVA AS SOLICITACAO,
	   sol.TIPSVA AS TIPO,
	   tip.DESRRQ AS DESCR_TIPO,
	   sol.QTDVAG AS QTD_VAGAS,
	   sol.CODCAR AS COD_CARGO,
	   car.TITCAR AS CARGO,
	   sol.SITSVA AS COD_SITUACAO,
	   CASE 
	   		WHEN sol.SITSVA = 1 THEN 'Em definição'
	   		WHEN sol.SITSVA = 2 THEN 'Em aprovação'
	   		WHEN sol.SITSVA = 3 THEN 'Solicitação de alteração'
	   		WHEN sol.SITSVA = 4 THEN 'Aprovada'
	   		WHEN sol.SITSVA = 5 THEN 'Rejeitada'
	   		WHEN sol.SITSVA = 6 THEN 'Cancelada'
	   END AS SITUACAO_SOLICITACAO,
	   CASE 
	   	   WHEN sol.DTHRQU <> 0 THEN TO_CHAR(sol.DTHRQU + TO_DATE('01/01/1900','dd/mm/rrrr') -2, 'DD/MM/YYYY HH24:MI:SS')
	   	   ELSE '00/00/0000 00:00:00'
	   END AS DATA_CRIACAO_REQUISICAO,
	   COALESCE (req.CODRQU,0) AS COD_REQUISICAO,
	   COALESCE (req.SITRQU,0) AS COD_SITUACAO_REQUISICAO,
	   CASE 
	   	   WHEN req.SITRQU = 0 THEN 'Não iniciada'
	   	   WHEN req.SITRQU = 1 THEN 'Em andamento'
	   	   WHEN req.SITRQU = 2 THEN 'Cancelada'
	   	   WHEN req.SITRQU = 3 THEN 'Finalizada'
	   	   WHEN req.SITRQU = 5 THEN 'Suspensa'
	   	   ELSE 'Requisição ainda não foi criada'
	   END AS SITUACAO_REQUISICAO,
	   COALESCE (TO_CHAR(req.DATPRE,'DD/MM/YYYY') ,'00/00/0000') AS DATA_PREVISAO,
	   COALESCE (TO_CHAR(req.DATLIM,'DD/MM/YYYY') ,'00/00/0000') AS DATA_LIMITE_REQUISICAO,
	   COALESCE (TO_CHAR(req.DATENC,'DD/MM/YYYY') ,'00/00/0000') AS DATA_ENCERRAMENTO_REQUISICAO
FROM (VETORH_PROD.R126SVA sol LEFT OUTER JOIN VETORH_PROD.R126RQU req
							  ON req.CODRQU = sol.CODRQU),
	  VETORH_PROD.R114RRQ tip,
	  VETORH_PROD.R030FIL fil,
	  VETORH_PROD.R024CAR car
WHERE tip.CODRRQ = sol.TIPSVA
AND fil.NUMEMP = sol.NUMEMP 
AND fil.CODFIL = sol.CODFIL 
AND car.ESTCAR = sol.ESTCAR
AND car.CODCAR = sol.CODCAR
AND sol.NUMEMP = 5
--AND sol.DATSVA BETWEEN TO_DATE('REPLACE_START_DATE', 'dd/mm/yyyy') AND TO_DATE('REPLACE_END_DATE', 'dd/mm/yyyy')
ORDER BY sol.CODFIL