SELECT
		'ENTRADA' AS TIPO,
		NE.CODEMP AS EMPRESA,
		NE.CODFIL AS FILIAL_ERP,
		F.USU_UNINEG AS FILIAL_LINX,
		NE.NOPOPE AS CFOP,
		NE.CODTNS AS TRANSACAO,
		SUM(NE.VLRCTB) AS VALOR_CONTABIL,
		SUM(NE.VLRBIC) AS BASE_ICMS,
		SUM(NE.VLRICM) AS VALOR_ICMS,
		SUM(NE.VLRIIC) AS VALOR_ISENTO_ICMS,
		SUM(NE.VLROIC) AS VALOR_OUTROS_ICMS,
		(SUM(NE.VLRBIC) + SUM(NE.VLRIIC) + SUM(NE.VLROIC)) AS TOTAL,
		NE.DATENT AS DATA_EVENTO
	FROM SAPIENS_PROD.E660NFC NE
		INNER JOIN SAPIENS_PROD.E070FIL F ON
		F.CODEMP = NE.CODEMP 
		AND F.CODFIL = NE.CODFIL 
		INNER JOIN SAPIENS_PROD.E001TNS T ON
		T.CODEMP = NE.CODEMP 
		AND T.CODTNS = NE.CODTNS 
WHERE 
	NE.CODEMP IN (2, 5)
	AND NE.DATENT >= TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-2)))+1
	AND T.LISMOD IN ('COF','COS')
GROUP BY
	 NE.CODEMP, NE.CODFIL, F.USU_UNINEG, NE.NOPOPE, NE.CODTNS, NE.DATENT

UNION ALL 

SELECT
	'SAIDA' AS TIPO,
	NS.CODEMP AS EMPRESA,
	NS.CODFIL AS FILIAL_ERP,
	F.USU_UNINEG AS FILIAL_LINX,
	NS.NOPOPE AS CFOP,
	NS.CODTNS AS TRANSACAO,
	SUM(NS.VLRCTB) AS VALOR_CONTABIL,
	SUM(NS.VLRBIC) AS BASE_ICMS,
	SUM(NS.VLRICM) AS VALOR_ICMS,
	SUM(NS.VLRIIC) AS VALOR_ISENTO_ICMS,
	SUM(NS.VLROIC) AS VALOR_OUTROS_ICMS,
	(SUM(NS.VLRBIC) + SUM(NS.VLRIIC) + SUM(NS.VLROIC)) AS TOTAL,
	NS.DATEMI AS DATA_EVENTO
FROM SAPIENS_PROD.E660NFV NS
	INNER JOIN SAPIENS_PROD.E070FIL F ON
	F.CODEMP = NS.CODEMP 
	AND F.CODFIL = NS.CODFIL 
	INNER JOIN SAPIENS_PROD.E001TNS T ON
	T.CODEMP = NS.CODEMP 
	AND T.CODTNS = NS.CODTNS 
WHERE NS.CODEMP IN (2, 5)
	AND NS.DATEMI >= TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-2)))+1
	AND T.LISMOD IN ('VEF','VES')
GROUP BY 
	NS.CODEMP, NS.CODFIL, F.USU_UNINEG, NS.NOPOPE, NS.CODTNS, NS.DATEMI