SELECT
	    'CONTAS_RECEBER' AS tipo_descricao,
		TR.CODEMP AS EMPRESA,
		TR.CODFIL AS FIL_ERP,
		FIL.USU_UNINEG AS FIL_SIS_ORIGEM,
		FIL.SIGFIL AS NOME_FILIAL_ORIGEM,
		TR.DATPPT AS DATA_PROVAVEL_PG,
		TR.CODPOR AS PORTADOR,
		P.DESPOR AS NOME_PORTADOR,
		TR.CODCRT AS CARTEIRA,
		CART.DESCRT AS NOME_CARTEIRA,
		TR.CODCLI AS COD_CLIENTE,
		C.APECLI AS NOME_CLIENTE,
		COALESCE(C.CODGRE, 0) AS GRUPO_EMPRESA,
		COALESCE(G.NOMGRE, 'Sem Grupo Empresa') AS NOME_GP_EMP,
		TR.NUMTIT AS TITULO,
		TR.CODTPT AS TIPO,
		TR.CODREP AS REPRESENTANTE,
		COALESCE(TR.NUMCTR, 0) AS CONTRATO, 
		TR.VLRORI AS VALOR_ORIGINAL,
		TR.VLRABE AS VALOR_ABERTO,
		TR.PERMUL AS PERC_MULTA,
		TR.PERJRS AS PERC_JUROS,
		TR.TIPJRS AS TIPO_JUROS,
		TR.VLRDSC AS DESCONTO,
		(TR.VLRABE - TR.VLRDSC) AS VALOR_LIQ
	FROM
		SAPIENS_PROD.E301TCR TR
	INNER JOIN SAPIENS_PROD.E001TNS TNS ON
		TR.CODEMP = TNS.CODEMP 
		AND TR.CODTNS = TNS.CODTNS
	INNER JOIN	SAPIENS_PROD.E085CLI C ON
		TR.CODCLI = C.CODCLI
	INNER JOIN SAPIENS_PROD.E002TPT TPT ON
		TR.CODTPT = TPT.CODTPT
	INNER JOIN SAPIENS_PROD.E070FIL FIL ON
		TR.CODEMP = FIL.CODEMP 
		AND TR.CODFIL = FIL.CODFIL
	INNER JOIN SAPIENS_PROD.E039POR P ON
		TR.CODEMP = P.CODEMP
		AND TR.CODPOR = P.CODPOR
	INNER JOIN SAPIENS_PROD.E033CRT CART ON
		TR.CODCRT = CART.CODCRT
	LEFT JOIN SAPIENS_PROD.E069GRE G ON
		C.CODGRE = G.CODGRE
	WHERE
		TR.CODEMP IN (5)
		AND TR.CODFIL = 7
		AND TR.CODFIL <= 999
		AND TR.VLRABE > 0
		AND TPT.RECSOM = 'D'
		-- AND TR.VCTPRO  >= TO_DATE('01/05/2025', 'YYYY-MM-DD')
		-- AND TR.VCTPRO <= TO_DATE('31/05/2025', 'YYYY-MM-DD')
		AND TR.DATEMI >= TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD')
		AND TR.DATEMI < TO_DATE('REPLACE_END_DATE', 'YYYY-MM-DD')
		AND TNS.LISMOD = 'CRE'
UNION ALL
	SELECT
		'CONTAS_PAGAR' AS tipo_descricao,
		TP.CODEMP AS EMPRESA,
		TP.CODFIL AS FIL_ERP,
		FIL.USU_UNINEG AS FIL_SIS_ORIGEM,
		FIL.SIGFIL AS NOME_FILIAL_ORIGEM,
		TP.DATPPT AS DATA_PROVAVEL_PG,
		TP.CODPOR AS PORTADOR,
		P.DESPOR AS NOME_PORTADOR,
		TP.CODCRT AS CARTEIRA,
		CART.DESCRT AS NOME_CARTEIRA,
		TP.CODFOR AS COD_FORNECEDOR,
		F.APEFOR AS NOME_FORNECEDOR,
		COALESCE(F.CODGRE, 0) AS GRUPO_EMPRESA,
		COALESCE(G.NOMGRE, 'Sem Grupo Empresa') AS NOME_GP_EMP,
		TP.NUMTIT AS TITULO,
		TP.CODTPT AS TIPO,
		0 AS REPRESENTANTE,
		COALESCE(TP.NUMCTR, 0) AS CONTRATO, 
		TP.VLRORI AS VALOR_ORIGINAL,
		TP.VLRABE AS VALOR_ABERTO,
		TP.PERMUL AS PERC_MULTA,
		TP.PERJRS AS PERC_JUROS,
		TP.TIPJRS AS TIPO_JUROS,
		TP.VLRDSC AS DESCONTO,
		(TP.VLRABE - TP.VLRDSC) AS VALOR_LIQ
	FROM
		SAPIENS_PROD.E501TCP TP
	left JOIN SAPIENS_PROD.E001TNS TNS ON
		TP.CODEMP = TNS.CODEMP 
		AND TP.CODTNS = TNS.CODTNS
	left JOIN	SAPIENS_PROD.E095FOR F ON
		TP.CODFOR = F.CODFOR
	left JOIN SAPIENS_PROD.E002TPT TPT ON
		TP.CODTPT = TPT.CODTPT
	left JOIN SAPIENS_PROD.E070FIL FIL ON
		TP.CODEMP = FIL.CODEMP 
		AND TP.CODFIL = FIL.CODFIL
	LEFT JOIN SAPIENS_PROD.E039POR P ON
		TP.CODEMP = P.CODEMP 
		AND TP.CODPOR = P.CODPOR
	LEFT JOIN SAPIENS_PROD.E033CRT CART ON
		TP.CODCRT = CART.CODCRT
	LEFT JOIN SAPIENS_PROD.E069GRE G ON
		F.CODGRE = G.CODGRE
	WHERE
		TP.CODEMP IN (2,5)
		AND TP.CODFIL >= 1
		AND TP.CODFIL <= 999
		AND TP.VLRABE > 0
		AND TPT.PAGSOM = 'D'
		-- AND TP.VCTPRO  >= TO_DATE('25/03/2025', 'YYYY-MM-DD')
		-- AND TP.VCTPRO <= TO_DATE('25/03/2025', 'YYYY-MM-DD')
		AND TP.DATEMI >= TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD')
		AND TP.DATEMI < TO_DATE('REPLACE_END_DATE', 'YYYY-MM-DD')
		AND TNS.LISMOD = 'CPE'
	ORDER BY 1, 2, 3, 5
