SELECT 
	FUN.NUMEMP AS EMPRESA,
	RCS.NUMCAD AS MATRICULA,
	TO_CHAR(RCS.PAGRCS,'DD/MM/YYYY') AS DATA_VENCIMENTO,
	RCS.FMDDEP AS MULTA,
	RCS.FRDVLR AS RESCISAO,
	RCS.FVIVLR AS INDENIZACAO,
	(RCS.FMDDEP + RCS.FRDVLR  + RCS.FVIVLR ) AS TOTAL
FROM
	VETORH_PROD.R034FUN FUN
INNER JOIN VETORH_PROD.R056RCS RCS ON
	RCS.NUMEMP = FUN.NUMEMP 
	AND RCS.TIPCOL = FUN.TIPCOL
	AND RCS.NUMCAD = FUN.NUMCAD
INNER JOIN VETORH_PROD.R038HLO HLO ON
	HLO.NUMEMP = FUN.NUMEMP 
	AND HLO.TIPCOL = FUN.TIPCOL 
	AND HLO.NUMCAD = FUN.NUMCAD
INNER JOIN VETORH_PROD.R038HFI HFI ON
	HFI.NUMEMP = FUN.NUMEMP 
	AND HFI.TIPCOL = FUN.TIPCOL 
	AND HFI.NUMCAD = FUN.NUMCAD 
INNER JOIN VETORH_PROD.R016HIE HIE ON
	HIE.TABORG = HLO.TABORG
	AND HIE.NUMLOC = HLO.NUMLOC 
INNER JOIN VETORH_PROD.R016ORN ORN ON
	ORN.TABORG = HLO.TABORG 
	AND ORN.NUMLOC = HLO.NUMLOC
INNER JOIN VETORH_PROD.R030FIL FIL ON
	FIL.NUMEMP = HFI.NUMEMP 
	AND FIL.CODFIL = HFI.CODFIL 
WHERE
	FUN.NUMEMP IN (2, 5)
	AND((RCS.FADVLR > 0)
		OR (RCS.FRDVLR > 0)
			OR (RCS.FVIVLR > 0)
				OR (RCS.FMDVLR > 0)
					OR (RCS.FADVLA > 0)
						OR (RCS.FRDVLA > 0)
							OR (RCS.FVIVLA > 0)
								OR (RCS.FMDVLA > 0))
		AND FUN.TIPCOL = 1
		AND HFI.DATALT = (SELECT MAX (DATALT)
								 FROM VETORH_PROD.R038HFI TAB2
								WHERE TAB2.NUMEMP = HFI.NUMEMP
								  AND TAB2.TIPCOL = HFI.TIPCOL
								  AND TAB2.NUMCAD = HFI.NUMCAD
				    			  AND TAB2.NUMEMP = TAB2.EMPATU
							      AND TAB2.NUMCAD = TAB2.CADATU
								  )
								  AND HLO.DATALT = (SELECT	MAX (DATALT)
														   FROM VETORH_PROD.R038HLO TABELA001
														  WHERE TABELA001.NUMEMP = HLO.NUMEMP
														    AND TABELA001.TIPCOL = HLO.TIPCOL
															AND TABELA001.NUMCAD = HLO.NUMCAD
															)
ORDER BY
	FUN.NUMEMP,
	FUN.NUMCAD
