-- titulos_edocs
SELECT
    5 AS EMPRESA,
    FIL.CODFIL AS FILIAL_ERP,
    fil.NUMCGC AS CNPJ,
    FIL.USU_UNINEG AS FILIAL_LINX,
    FIL.SIGFIL AS NOME_FILIAL,
    N.CGCFOR AS CNPJ_FORNECEDOR,
    F.APEFOR AS NOME_FORNECEDOR,
    N.DATEMI AS DATA_EMISSAO,
    N.NUMNFC AS NUMERO,
    N.VLRLIQ AS VALOR_NOTA,
    NP.NOPPRO AS CFOP,
    NP.CODPRO AS PRODUTO_ERP,
    NP.PROFOR AS CODIGO_PRODUTO_FORN,
    NP.VLRBRU AS VALOR_BRUTO_PRODUTO,
    NP.VLRDSC AS DESC_PRODUTO,
    NP.VLRICS AS ICMS_ST_PRODUTO,
    NP.VLRIPI AS IPI_PRODUTO,
    NP.VLRFRE AS FRETE_PRODUTO,
    NP.VLRSEG AS SEGURO_PRODUTO,
    NP.VLREMB AS EMBALAGEM_PRODUTO,
    NP.VLRENC AS ENCARGOS_PRODUTO,
    NP.VLROUT AS OUTROS_DESP_PRODUTO,
    (NP.VLRBRU-NP.VLRDSC+NP.VLRICS+NP.VLRIPI+NP.VLRFRE+NP.VLRSEG+NP.VLREMB+NP.VLRENC+NP.VLROUT) AS VALOR_LIQUIDO_PRODUTO,
    NP.CODBAR AS COD_BARRA_PRODUTO,
    N.CHVNEL AS CHAVE,
    COALESCE (C.CODFIL, 0) AS FILIAL_NFE_ENTRADA,
    COALESCE (C.CODFOR, 0) AS FORN_NFE_ENTRADA,
    COALESCE (C.NUMNFC, 0) AS NUMERO_NFE_ENTRADA,
    COALESCE (T.NUMTIT, '0') AS TITULO,
    N.INDCAN AS CANCELADO
FROM
    SAPIENS_PROD.E000NFC N
LEFT JOIN SAPIENS_PROD.E000PAR P ON
    P.CGCFIL = N.CGCFIL
    AND P.CGCFOR = N.CGCFOR
    AND P.CHVNEL = N.CHVNEL
    AND P.NUMNFC = N.NUMNFC
INNER JOIN SAPIENS_PROD.E000IPC NP ON
    NP.CGCFIL = N.CGCFIL 
    AND NP.CGCFOR = N.CGCFOR 
    AND NP.CHVNEL = N.CHVNEL
INNER JOIN SAPIENS_PROD.E070FIL FIL ON
    FIL.NUMCGC = N.CGCFIL
LEFT JOIN SAPIENS_PROD.E095FOR F ON
    F.CGCCPF = N.CGCFOR
LEFT JOIN SAPIENS_PROD.E440NFC C ON
    C.NUMNFC = N.NUMNFC
    AND C.CHVNEL = N.CHVNEL
LEFT JOIN SAPIENS_PROD.E501TCP T ON
    T.CODEMP = C.CODEMP 
    AND T.CODFIL = C.CODFIL 
    AND T.NUMNFC = C.NUMNFC 
WHERE
    N.CGCFIL LIKE '63503007%'
    AND N.TIPNFE = 1
    AND TRUNC(N.DATEMI) = TRUNC(TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD'))

UNION ALL

SELECT 
    2 AS EMPRESA, 
    FIL.CODFIL AS FILIAL_ERP,
    fil.NUMCGC AS CNPJ,
    FIL.USU_UNINEG AS FILIAL_LINX,
    FIL.SIGFIL AS NOME_FILIAL,
    N.CGCFOR AS CNPJ_FORNECEDOR,
    F.APEFOR AS NOME_FORNECEDOR,
    N.DATEMI AS DATA_EMISSAO,
    N.NUMNFC AS NUMERO,
    N.VLRLIQ AS VALOR_NOTA,
    NP.NOPPRO AS CFOP,
    NP.CODPRO AS PRODUTO_ERP,
    NP.PROFOR AS CODIGO_PRODUTO_FORN,
    NP.VLRBRU AS VALOR_BRUTO_PRODUTO,
    NP.VLRDSC AS DESC_PRODUTO,
    NP.VLRICS AS ICMS_ST_PRODUTO,
    NP.VLRIPI AS IPI_PRODUTO,
    NP.VLRFRE AS FRETE_PRODUTO,
    NP.VLRSEG AS SEGURO_PRODUTO,
    NP.VLREMB AS EMBALAGEM_PRODUTO,
    NP.VLRENC AS ENCARGOS_PRODUTO,
    NP.VLROUT AS OUTROS_DESP_PRODUTO,
    (NP.VLRBRU-NP.VLRDSC+NP.VLRICS+NP.VLRIPI+NP.VLRFRE+NP.VLRSEG+NP.VLREMB+NP.VLRENC+NP.VLROUT) AS VALOR_LIQUIDO_PRODUTO,
    NP.CODBAR AS COD_BARRA_PRODUTO,
    N.CHVNEL AS CHAVE,
    COALESCE (C.CODFIL, 0) AS FILIAL_NFE_ENTRADA,
    COALESCE (C.CODFOR, 0) AS FORN_NFE_ENTRADA,
    COALESCE (C.NUMNFC, 0) AS NUMERO_NFE_ENTRADA,
    COALESCE (T.NUMTIT, '0') AS TITULO,
    N.INDCAN AS CANCELADO
FROM
    SAPIENS_PROD.E000NFC N
LEFT JOIN SAPIENS_PROD.E000PAR P ON
    P.CGCFIL = N.CGCFIL
    AND P.CGCFOR = N.CGCFOR
    AND P.CHVNEL = N.CHVNEL
    AND P.NUMNFC = N.NUMNFC
INNER JOIN SAPIENS_PROD.E000IPC NP ON
    NP.CGCFIL = N.CGCFIL 
    AND NP.CGCFOR = N.CGCFOR 
    AND NP.CHVNEL = N.CHVNEL
INNER JOIN SAPIENS_PROD.E070FIL FIL ON
    FIL.NUMCGC = N.CGCFIL
LEFT JOIN SAPIENS_PROD.E095FOR F ON
    F.CGCCPF = N.CGCFOR
LEFT JOIN SAPIENS_PROD.E440NFC C ON
    C.NUMNFC = N.NUMNFC
    AND C.CHVNEL = N.CHVNEL
LEFT JOIN SAPIENS_PROD.E501TCP T ON
    T.CODEMP = C.CODEMP 
    AND T.CODFIL = C.CODFIL 
    AND T.NUMNFC = C.NUMNFC 
WHERE
    N.CGCFIL LIKE '7224991%'
    AND N.TIPNFE = 1
    AND TRUNC(N.DATEMI) = TRUNC(TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD'))
	