SELECT 
	TO_CHAR(af.DATAFA, 'yyyy-mm-dd') AS DATA_AFASTAMENTO,
	af.NUMEMP AS EMPRESA, 
	f.CODFIL AS COD_FILIAL,
	f.NOMFIL AS NOME_FILIAL,
	f.CODEST AS UF,
	af.TIPCOL AS TIPO,
	CASE 
		WHEN af.TIPCOL = 1 THEN 'Empregado' 
		WHEN af.TIPCOL = 2 THEN 'Terceiro'
		WHEN af.TIPCOL = 3 THEN 'Parceiro'
	END AS NOME_TIPO,
	af.NUMCAD AS MATRICULA,
	af.SITAFA AS SITUACAO,
	saf.DESSIT AS DESC_SITUACAO,
	af.DIAPRV AS QTA_DIAS,
	COALESCE (af.CODDOE,'0') AS CIDDEZ,
	COALESCE (cid.DESDOE,'Sem CID-10') AS DESC_CIDDEZ,
	COALESCE (af.CODSUB,'0') AS CIDDEZ_SUBGRUPO,
	COALESCE (sub.DESSUB,'Sem Subgrupo CID-10') AS DESC_CIDDEZ_SUBGRUPO
FROM 
	VETORH_PROD.R034FUN fun,
	(VETORH_PROD.R038AFA af LEFT OUTER JOIN VETORH_PROD.R192DOE cid
						ON cid.CODDOE = af.CODDOE
				LEFT OUTER JOIN VETORH_PROD.R192SUB sub
						ON sub.CODSUB = af.CODSUB),
	VETORH_PROD.R010SIT saf,
	VETORH_PROD.R030FIL f
WHERE af.NUMEMP = fun.NUMEMP
AND af.TIPCOL = fun.TIPCOL 
AND af.NUMCAD = fun.NUMCAD 
AND saf.CODSIT = af.SITAFA
AND f.NUMEMP = af.NUMEMP
AND f.NUMEMP = fun.NUMEMP
AND f.CODFIL = fun.CODFIL
AND af.NUMEMP = 5
AND af.TIPCOL = 1
AND af.DATAFA = (SELECT max(af1.DATAFA) FROM VETORH_PROD.R038AFA af1
								WHERE af1.NUMEMP = af.NUMEMP
								AND af1.TIPCOL = af.TIPCOL 
								AND af1.NUMCAD = af.NUMCAD
								AND af1.DATAFA = TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd'))
