SELECT
	DISTINCT 
	M.CODEMP AS EMPRESA, 
	M.NUMTIT AS TITULO,
	M.SEQMOV AS SEQ_MOV,
	M.CODTPT AS TIPO_TITULO,
	M.CODFOR AS FORNECEDOR,
	F.CGCCPF AS CNPJ_CPF_FORNECEDOR,
	M.CODFIL AS FILIAL,
	T.SITTIT AS SITUACAO,
	C.TNSPRO AS CFOP,
	T.NUMNFC AS NF_ENTRADA,
	C.CHVNEL AS CHAVE_ELETRONICA,
	TO_CHAR(T.VCTPRO,'DD/MM/YYYY') AS VENCIMENTO,
	TO_CHAR(T.ULTPGT,'DD/MM/YYYY') AS ULTIMO_PAGAMENTO,
	TO_CHAR(T.DATENT,'DD/MM/YYYY')  AS ENTRADA,
	T.VLRORI AS VALOR_ORIGINAL,
	T.VLRABE AS VALOR_ABERTO,
	M.VLRMOV AS VALOR_MOVIMENTO,
	F.NOMFOR AS NOME_FORNECEDOR,
	TO_CHAR(T.DATEMI,'DD/MM/YYYY') AS EMISSAO,
	TO_CHAR(T.VCTORI,'DD/MM/YYYY') AS VENCIMENTO_ORIGINAL,
	TO_CHAR(M.DATMOV,'DD/MM/YYYY')  AS DATA_MOVIMENTO, 
	TO_CHAR(M.DATPGT,'DD/MM/YYYY')  AS DATA_PAGAMENTO,
	M.VLRJRS AS JUROS,
	M.VLRJRS AS MULTA,
	M.VLRENC AS ENCARGOS,
	M.VLROAC AS ACRESCIMOS,
	M.VLRDSC AS DESCONTOS,
	M.VLRODE AS OUTROS_DESCONTOS,
	F.CODGRE AS GRUPO_EMPRESA,
	M.CODTNS AS TRANSACAO,
	CASE
		WHEN TNS.PAGTPB = 'PG' THEN 'Pagamento'
		WHEN TNS.PAGTPB = 'DV' THEN 'Devolução'
		WHEN TNS.PAGTPB = 'AB' THEN 'Abatimento'
		WHEN TNS.PAGTPB = 'CA' THEN 'Cancelamento'
		WHEN TNS.PAGTPB = 'CR' THEN 'Baixa Crédito'
		WHEN TNS.PAGTPB = 'CP' THEN 'Compensação'
		WHEN TNS.PAGTPB = 'LP' THEN 'Lucos e Perdas'
		WHEN TNS.PAGTPB = 'SU' THEN 'Substituição'
		WHEN TNS.PAGTPB = 'NA' THEN 'Não é baixa'
	END AS TIPO_TRANSACAO,
	TNS.DESTNS AS DESCRICAO,
	T.SNFNFC AS SERIE_NF_ENTRADA,
	T.TIPIMP,
	CASE
		WHEN T.TIPIMP = 0 THEN '0'
		WHEN T.TIPIMP = 1 THEN 'IPI'
		WHEN T.TIPIMP = 2 THEN 'ICMS'
		WHEN T.TIPIMP = 3 THEN 'ICMS Dif Alíquota'
		WHEN T.TIPIMP = 4 THEN 'ICMS Substituto'
		WHEN T.TIPIMP = 5 THEN 'ISS'
		WHEN T.TIPIMP = 6 THEN 'Outros (Base Faturamento)'
		WHEN T.TIPIMP = 7 THEN 'PIS Substituto'
		WHEN T.TIPIMP = 8 THEN 'COFINS Substituto'
		WHEN T.TIPIMP = 9 THEN 'Funrural'
		WHEN T.TIPIMP = 10 THEN 'INSS'
		WHEN T.TIPIMP = 11 THEN 'IRRF'
		WHEN T.TIPIMP = 12 THEN 'Simples'
		WHEN T.TIPIMP = 13 THEN 'IRPJ Lucro Presumido - Atividade Principal'
		WHEN T.TIPIMP = 14 THEN 'IRPJ Lucro Presumido - Atividade Secundária'
		WHEN T.TIPIMP = 15 THEN 'CSLL Presumido - Atividade Principal'
		WHEN T.TIPIMP = 16 THEN 'CSLL Presumido - Atividade Secundária'
		WHEN T.TIPIMP = 17 THEN 'IRPJ Adicional'
		WHEN T.TIPIMP = 18 THEN 'COFINS'
		WHEN T.TIPIMP = 19 THEN 'PIS'
		WHEN T.TIPIMP = 20 THEN 'PIS - Não Cumulativo'
		WHEN T.TIPIMP = 21 THEN 'COFINS - Não Cumulativo'
		WHEN T.TIPIMP = 22 THEN 'CONFINS - Retenção'
		WHEN T.TIPIMP = 23 THEN 'PIS - Retenção'
		WHEN T.TIPIMP = 24 THEN 'CSLL - Retenção'
		WHEN T.TIPIMP = 25 THEN 'Outras Retenções'
		WHEN T.TIPIMP = 26 THEN 'ICMS Responsabilidade Tributária/Frete'
		WHEN T.TIPIMP = 27 THEN 'IRPJ Lucro Presumido - Atividade Terciária'
		WHEN T.TIPIMP = 28 THEN 'CSLL Presumido - Atividade Terciária'
		WHEN T.TIPIMP = 29 THEN 'INSS Empresa'
		WHEN T.TIPIMP = 30 THEN 'Super Simples'
		WHEN T.TIPIMP = 31 THEN 'ICMS ST - Responsável Solidário'
		WHEN T.TIPIMP = 32 THEN 'IPF'
		WHEN T.TIPIMP = 33 THEN 'CPMF'
		WHEN T.TIPIMP = 34 THEN 'ICMS Substituro por Estado'
		WHEN T.TIPIMP = 35 THEN 'CIDE - Combustíveis'
		WHEN T.TIPIMP = 36 THEN 'IPVA'
		WHEN T.TIPIMP = 37 THEN 'Licenciamento'
		WHEN T.TIPIMP = 38 THEN 'DPVAT'
		WHEN T.TIPIMP = 39 THEN 'IPTU'
		WHEN T.TIPIMP = 40 THEN 'FGTS'
		WHEN T.TIPIMP = 41 THEN 'PIS Não Cumulativo (SPED)'
		WHEN T.TIPIMP = 42 THEN 'COFINS Não Cumulativo (SPED)'
		WHEN T.TIPIMP = 43 THEN 'PIS Cumulativo (SPED)'
		WHEN T.TIPIMP = 44 THEN 'COFINS Cumulativo (SPED)'
		WHEN T.TIPIMP = 45 THEN 'Subsídio'
		WHEN T.TIPIMP = 46 THEN 'CIDE - Tecnologia'
		WHEN T.TIPIMP = 47 THEN 'PIS - Regime de Caixa (SPED)'
		WHEN T.TIPIMP = 48 THEN 'COFINS - Regime de Caixa (SPED)'
		WHEN T.TIPIMP = 49 THEN 'Contribuição Previdenciária sobre Receita Bruta'
		WHEN T.TIPIMP = 50 THEN 'IRRF Exterior - Contratos de Empréstimos de Mercado Externo'
		WHEN T.TIPIMP = 51 THEN 'FCI'
		WHEN T.TIPIMP = 52 THEN 'SENAR/SENAT'
		WHEN T.TIPIMP = 53 THEN 'IRPJ - Lucro presumido (SPED)'
		WHEN T.TIPIMP = 54 THEN 'CSLL - Lucro presumido (SEPD)'
		WHEN T.TIPIMP = 55 THEN 'IRPJ - Lucro real (SPED)'
		WHEN T.TIPIMP = 56 THEN 'CSLL - Lucro real (SPED)'
		WHEN T.TIPIMP = 57 THEN 'IRPJ - Lucro arbitrado (SPED)'
		WHEN T.TIPIMP = 58 THEN 'CSLL - Lucro arbitrado (SPED)'
		WHEN T.TIPIMP = 59 THEN 'IRPJ - Imune/Isenta (SPED)'
		WHEN T.TIPIMP = 60 THEN 'CSLL - Imune/Isenta (SEPD)'
		WHEN T.TIPIMP = 61 THEN 'IRPJ - Diferença pela mudança de coeficiente'
		WHEN T.TIPIMP = 62 THEN 'Super Simples (Regime Caixa)'
		WHEN T.TIPIMP = 63 THEN 'Dif. Alíq. do ICMS interestadual com consumidor final'
		WHEN T.TIPIMP = 64 THEN 'FCP - Fundo de combate a pobreza'
		WHEN T.TIPIMP = 65 THEN 'ISS Retido'
		WHEN T.TIPIMP = 66 THEN 'ISS Retido - RPA'
		WHEN T.TIPIMP = 67 THEN 'Débito Especial'
		WHEN T.TIPIMP = 68 THEN 'Simples Nacional'
		WHEN T.TIPIMP = 69 THEN 'INSS - EFD Reinf'
		WHEN T.TIPIMP = 70 THEN 'ICMS ST Complementar'
		WHEN T.TIPIMP = 71 THEN 'Contribuição Previdenciária sobre Receita Bruta - REINF'
		WHEN T.TIPIMP = 72 THEN 'ISS Próprio das Instituições Financeiras'
		WHEN T.TIPIMP = 73 THEN 'ISS (LC 175/2020)'
		WHEN T.TIPIMP = 74 THEN 'ISS Retido (LC 175/2020'
		WHEN T.TIPIMP = 75 THEN 'ISS Partilha (LC 175/2020)'
		WHEN T.TIPIMP = 76 THEN 'Agronegócio'
		WHEN T.TIPIMP = 77 THEN 'Retenção na fonte - EDS Reinf'
		WHEN T.TIPIMP = 78 THEN 'ICMS Monofísico'
		WHEN T.TIPIMP = 95 THEN 'Regime de Caixa/Financeiro'
		WHEN T.TIPIMP = 96 THEN 'Totalizador'
		WHEN T.TIPIMP = 97 THEN 'Livre'
		WHEN T.TIPIMP = 98 THEN 'Contábil'
		WHEN T.TIPIMP = 99 THEN 'Estoque'
	END AS TIPO_IMPOSTO,
	T.PERDSC AS PER_DESCONTO,
	M.CODPOR AS PORTADOR,
	P.DESPOR AS NOME_PORTADOR,
	r.CODCCU AS COD_CUSTO,
	cr.DESCCU AS DESCR_CUSTO, 
	R.VLRRAT AS VALOR_RATEIO, 
	T.OBSTCP AS OBSERVACAO, 
	t.FORNFC AS FORN_COMPRA
FROM
	SAPIENS_PROD.E501TCP T
INNER JOIN SAPIENS_PROD.E095FOR F ON
	F.CODFOR = T.CODFOR
INNER JOIN SAPIENS_PROD.E501MCP M ON
	M.CODEMP = T.CODEMP
	AND M.CODFIL = T.CODFIL
	AND M.NUMTIT = T.NUMTIT
	AND M.CODTPT = T.CODTPT
	AND M.CODFOR = T.CODFOR
INNER JOIN SAPIENS_PROD.E001TNS TNS ON
	TNS.CODEMP = M.CODEMP
	AND TNS.CODTNS = M.CODTNS
INNER JOIN SAPIENS_PROD.E039POR P ON
	P.CODEMP = M.CODEMP
	AND P.CODPOR = M.CODPOR
LEFT JOIN SAPIENS_PROD.E440NFC C ON
	C.CODEMP = T.CODEMP 
	AND C.CODFIL = T.CODFIL 
	AND C.CODFOR = T.CODFOR 
	AND C.NUMNFC = T.NUMNFC 
	AND C.CODSNF = T.SNFNFC
LEFT JOIN SAPIENS_PROD.E501RAT r
	ON r.CODEMP = m.CODEMP
	AND r.CODFIL = m.CODFIL 
	AND r.CODFOR = m.CODFOR 
	AND r.NUMTIT = m.NUMTIT 
	AND r.CODTPT = m.CODTPT 
	AND r.SEQMOV = m.SEQMOV 
INNER JOIN SAPIENS_PROD.E044CCU cr
	ON cr.CODEMP = r.CODEMP 
	AND cr.CODCCU = r.CODCCU
WHERE
	T.CODEMP in (2,5)
	AND T.SITTIT <> 'CA'
	AND tns.LISMOD IN ('CPE','CPB')
	AND T.DATENT = TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd')