----------------------marcacao pontos------------------
SELECT 
	HCH.NUMEMP AS EMPRESA,
	TO_CHAR(MARC.DATACC,'DD/MM/YYYY')  AS DATA_ACESSO, 
	MARC.HORACC AS HORA_ACESSO, 
	TO_CHAR(MARC.DATAPU,'DD/MM/YYYY')  AS DATA_APURACAO, 
	MARC.CODPLT AS CODIGO_SITE, 
	P.DESPLT AS DESCR_SITE, 
	MARC.CODRLG AS COLETOR, 
	COLET.DESRLG AS DESCR_COLETOR, 
	MARC.CODFNC AS COD_FUNCAO, 
	MARC.ORIACC AS ORIGEM_MARCACAO, 
	MARC.USOMAR AS USO_MARCACAO, 
	MARC.TIPACC AS TIPO_ACESSO, 
	MARC.NUMCRA AS MATRICULA, 
	MARC.DIRACC AS DIRECAO_ACESSO, 
	MARC.EXCPON AS EXCLUIDO_DO_PONTO,
   	TO_CHAR(TRUNC((MARC.HORACC * 60) / 3600), 'FM9900') || ':' ||
   	TO_CHAR(TRUNC(MOD((MARC.HORACC * 60), 3600) / 60), 'FM00') || ':' ||
   	TO_CHAR(MOD((MARC.HORACC * 60), 60), 'FM00') AS MIN_TO_HOUR
 FROM VETORH_PROD.R070ACC MARC 
 LEFT JOIN  VETORH_PROD.R058RLG COLET
 	ON  MARC.CODPLT = COLET.CODPLT 
 	AND MARC.CODRLG = COLET.CODRLG 
 LEFT JOIN  VETORH_PROD.R058PLT P 
  	ON MARC.CODPLT = P.CODPLT
 INNER JOIN VETORH_PROD.R038HCH HCH ON
 	HCH.TIPCOL = MARC.TIPCOL 
 	AND HCH.NUMEMP = MARC.NUMEMP
 	AND HCH.NUMCAD = MARC.NUMCAD
 	AND HCH.NUMCRA = MARC.NUMCRA 
WHERE HCH.NUMEMP IN (2, 5)
  	AND HCH.TIPCOL = 1
 	AND MARC.DATACC >= TO_DATE('2024-01-01', 'yyyy-mm-dd')
 	AND (MARC.DATACC > HCH.DATINI OR (MARC.DATACC = HCH.DATINI AND MARC.HORACC >= HCH.HORINI)) 
