SELECT
	E.NUMCCO AS CONTA,
	e.DATEXT AS DATA_EXTRATO,
	e.DOCMOV AS NUMERO_DOCUMENTO,
	e.HISEXT AS HISTORICO,
	e.VLREXT AS VALOR_EXTRATO,
	e.DECEXT AS DEBITO_CREDITO,
	c.SALINI AS SALDO_INICIAL
FROM
	SAPIENS_PROD.E605EXT e, SAPIENS_PROD.E600CCO c
WHERE e.CODEMP = c.CODEMP
	AND e.NUMCCO = c.NUMCCO 
	AND e.CODEMP = 5
	AND DATEXT = TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd')