SELECT
	LB.NUMEMP AS EMPRESA,
	LB.TIPCOL AS COD_TIPO,
	CASE
		WHEN LB.TIPCOL = 1 THEN 'Empregado'
		WHEN LB.TIPCOL = 2 THEN 'Terceiro'
		WHEN LB.TIPCOL = 3 THEN 'Parceiro'
	END AS DESCR_TIPO,
	LB.NUMCAD AS MATRICULA,
	LB.CODBHR AS COD_BANCO_HORAS,
	B.DESBHR AS DESCR_BANCO_HORAS,
	LB.CODSIT AS COD_SITUACAO,
	S.DESSIT AS DESCR_SITUACAO,
	CASE 
		WHEN LB.ORILAN = 'A' THEN 'Apuracao'
		WHEN LB.ORILAN = 'B' THEN 'Abono Antecipado'
		WHEN LB.ORILAN = 'D' THEN 'Digitado'
		WHEN LB.ORILAN = 'G' THEN 'Geracao de Eventos'
		WHEN LB.ORILAN = 'N' THEN 'Anular Debito'
		WHEN LB.ORILAN = 'O' THEN 'Outros'
		WHEN LB.ORILAN = 'R' THEN 'Regra'
		WHEN LB.ORILAN = 'F' THEN 'Transferencia de Filial'
		WHEN LB.ORILAN = 'M' THEN 'Migracao'
		WHEN LB.ORILAN = 'S' THEN 'Desconto Antecipado'
	END AS ORGEM_LANCAMENTO,
	LB.SINLAN AS SOMA_DIMINUI,
	TO_CHAR(TRUNC((LB.QTDHOR  * 60) / 3600), 'FM9900') || ':' ||
   	TO_CHAR(TRUNC(MOD((LB.QTDHOR * 60), 3600) / 60), 'FM00') || ':' ||
   	TO_CHAR(MOD((LB.QTDHOR * 60), 60), 'FM00') AS QTDA_HORAS_LANCAMENTO,
   	TO_CHAR(TRUNC((LB.QTDPAG  * 60) / 3600), 'FM9900') || ':' ||
   	TO_CHAR(TRUNC(MOD((LB.QTDPAG * 60), 3600) / 60), 'FM00') || ':' ||
   	TO_CHAR(MOD((LB.QTDPAG * 60), 60), 'FM00') AS QTDA_HORAS_PAGAS, 
   	TO_CHAR(TRUNC((LB.HORCMP * 60) / 3600), 'FM9900') || ':' ||
   	TO_CHAR(TRUNC(MOD((LB.HORCMP * 60), 3600) / 60), 'FM00') || ':' ||
   	TO_CHAR(MOD((LB.HORCMP * 60), 60), 'FM00') AS QTDA_HORAS_A_COMPENSAR,
   	TO_CHAR(LB.DATCMP,'DD/MM/YYYY') AS DATA_LIMITE_COMPENSACAO,
  LB.DATLAN AS DATA_LANCAMENTO
FROM
	VETORH_PROD.R011LAN LB
INNER JOIN VETORH_PROD.R011BHR B ON
	B.CODBHR = LB.CODBHR 
INNER JOIN VETORH_PROD.R010SIT S ON
	S.CODSIT = LB.CODSIT
WHERE
	LB.TIPCOL = 1
	AND LB.NUMEMP IN (2, 5)
  AND LB.DATLAN >= TO_DATE('2024-01-01', 'yyyy-mm-dd')
