--------------------- Ajustes ponto ------------------------------
SELECT 
	sit.NUMEMP AS EMPRESA,
	SIT.TIPCOL AS TIPO,
	SIT.NUMCAD AS MATRICULA,
	S.SITEXC AS SITUACAO_EXCECAO,
	SIT.CODSIT AS COD_SITUACAO,
	S.DESSIT AS DESCR_SITUACAO,
	COALESCE(O.DESOBS,' ') AS OBSERVACAO,
	TO_CHAR(SIT.DATAPU,'DD/MM/YYYY') AS DATA_APURACAO, 
	TO_CHAR(TRUNC((SIT.QTDHOR  * 60) / 3600), 'FM9900') || ':' ||
   	TO_CHAR(TRUNC(MOD((SIT.QTDHOR * 60), 3600) / 60), 'FM00') || ':' ||
   	TO_CHAR(MOD((SIT.QTDHOR * 60), 60), 'FM00') AS MARCACAO
FROM VETORH_PROD.R066SIT SIT
INNER JOIN VETORH_PROD.R010SIT S ON
	S.CODSIT = SIT.CODSIT
LEFT JOIN VETORH_PROD.R066OBS O ON
	O.NUMEMP = SIT.NUMEMP 
	AND O.TIPCOL = SIT.TIPCOL
	AND O.NUMCAD = SIT.NUMCAD 
	AND O.DATAPU = SIT.DATAPU
	AND O.CODSIT = SIT.CODSIT
WHERE SIT.NUMEMP IN (2, 5)
AND SIT.TIPCOL = 1
AND SIT.DATAPU >= TO_DATE('2024-01-01', 'yyyy-mm-dd')
