SELECT
    m.CODEMP AS EMPRESA,
    'MOVIMENTO' AS TIPO_DESCRICAO,
    m.CODFIL AS FIL_ERP,
    F.USU_UNINEG AS FIL_SIST_ORIGEM,
    F.SIGFIL AS NOME_FILIAL,
    m.NUMCCO AS CONTA,
    c.CODTCC AS COD_TIP_CONTA,
    tc.DESTCC AS NOME_TIP_CONTA,
    M.DATMOV AS DAT_MOV,
    M.DATLIB AS DAT_LIB,
    COALESCE(m.CODFOR, 0) AS FORNECEDOR,
    m.CODTNS AS TRANSACAO,
    tns.DESTNS AS DESCRICAO_TRANSACAO,
    COALESCE(m.HISMOV, ' ') AS HISTORICO,
    SUM(M.VLRMOV) AS VLR_MOV,
    m.DEBCRE,
    m.SEQCON AS SEQ_CONCIL,
    CASE
        WHEN m.DATCNC = TO_DATE('31-12-1900', 'DD-MM-YYYY') THEN '0000-00-00'
        ELSE TO_CHAR(m.DATCNC, 'YYYY-MM-DD')
    END AS DAT_CONC_REGISTRO,
    CASE
        WHEN m.DATCNC = TO_DATE('31-12-1900', 'DD-MM-YYYY') THEN 'Não conciliado'
        ELSE 'Conciliado'
    END AS SITUACAO_CONCILIACAO
FROM
    SAPIENS_PROD.E600MCC m
    INNER JOIN SAPIENS_PROD.E070FIL f ON m.CODEMP = f.CODEMP
    AND m.CODFIL = f.CODFIL
    INNER JOIN SAPIENS_PROD.E600CCO c ON m.CODEMP = c.CODEMP
    AND m.NUMCCO = c.NUMCCO
    INNER JOIN SAPIENS_PROD.E034TCC tc ON c.CODTCC = tc.CODTCC
    INNER JOIN SAPIENS_PROD.E001TNS tns ON m.codemp = tns.codemp
    AND m.CODTNS = tns.codtns
WHERE
    m.CODEMP IN (2, 5)
    AND m.CODFIL >= 1
    AND m.CODFIL <= 219
    AND m.SITMCC = 'A'
    AND DATMOV >= TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD')
    AND DATMOV < TO_DATE('REPLACE_END_DATE', 'YYYY-MM-DD')
GROUP BY
    M.CODEMP,
    M.NUMCCO,
    M.DATMOV,
    M.DATLIB,
    M.DEBCRE,
    m.CODFOR,
    c.CODTCC,
    tc.DESTCC,
    m.SEQCON,
    m.DATCNC,
    m.CODFIL,
    F.USU_UNINEG,
    F.SIGFIL,
    m.HISMOV,
    m.CODTNS,
    tns.destns
UNION ALL
SELECT
    e.CODEMP AS EMPRESA,
    'EXTRATO' AS TIPO,
    0,
    ' ',
    '',
    e.NUMCCO AS CONTA,
    c.CODTCC AS COD_TIP_CONTA,
    tc.DESTCC AS NOME_TIP_CONTA,
    E.DATEXT AS DAT_EXT,
    E.DATEXT AS DAT_LIB,
    0 AS FORNECEDOR,
    '',
    '',
    COALESCE(e.HISEXT, ' ') AS HISTORICO,
    SUM(E.VLREXT),
    E.DECEXT AS DEBCRE,
    E.SEQEXT AS SEQ_CONCIL,
    CASE
        WHEN e.DATCNC = TO_DATE('31-12-1900', 'DD-MM-YYYY') THEN '0000-00-00'
        ELSE TO_CHAR (e.DATCNC, 'YYYY-MM-DD')
    END AS DAT_CONC_REGISTRO,
    CASE
        WHEN e.DATCNC = TO_DATE('31-12-1900', 'DD-MM-YYYY') THEN 'Não conciliado'
        ELSE 'Conciliado'
    END AS SITUACAO_CONCILIACAO
FROM
    SAPIENS_PROD.E605EXT e
    INNER JOIN SAPIENS_PROD.E600CCO c ON e.CODEMP = c.CODEMP
    AND e.NUMCCO = c.NUMCCO
    INNER JOIN SAPIENS_PROD.E034TCC tc ON c.CODTCC = tc.CODTCC
WHERE
    E.CODEMP IN (2, 5)
    AND e.DATEXT >= TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD')
    AND e.DATEXT < TO_DATE('REPLACE_END_DATE', 'YYYY-MM-DD')
GROUP BY
    E.CODEMP,
    E.NUMCCO,
    E.DATEXT,
    E.DECEXT,
    E.SEQEXT,
    c.CODTCC,
    tc.DESTCC,
    e.DATCNC,
    e.HISEXT