SELECT DISTINCT 
	S.PROSER AS PRODUTO_OU_SERVICO,
	CASE 
		WHEN S.TIPCPR = 'D' THEN 'Compra Direta'
		WHEN S.TIPCPR = 'L' THEN 'Licitação'
	END AS TIPO_COMPRA,
	CASE 
		WHEN S.SITSOL = 0 THEN 'Digitada'
		WHEN S.SITSOL = 1 THEN 'Cotação'
		WHEN S.SITSOL = 2 THEN 'Ordem de Compra'
		WHEN S.SITSOL = 3 THEN 'Finalizada'
		WHEN S.SITSOL = 9 THEN 'Cancelada'
	END AS SITUACAO_SOLICITACAO,
	S.CODEMP AS EMPRESA,
	S.FILSOL AS FILIAL_ERP, ---filial da solicitação
	FIL.USU_UNINEG AS FILIAL_LINX,
	S.USUSOL AS COD_USU_SOLIC, ---código geração da solicitação
	USOL.NOMUSU AS USUARIO_SOLICITACAO, ----nome do usuário da solicitação
	S.NUMSOL AS NUM_SILICITACAO, ---Número solicitação
	S.CODFAM AS FAM_PRODUTO_SERVICO, ---Código da família do produto
	FAM.DESFAM AS DESCR_FAMILIA_PRODUTO_SERVICO, ----Descrição da família
	S.CODPRO AS PRODUTO_SERVICO,
	S.SEQSOL AS SEQ,
	S.CPLPRO AS DESCRICAO_SERVICO_PRODUTO, ----Descrição do Produto
	S.CODDER AS DERIVACAO,
	P.DESDER AS DESCR_DERIVACAO,
	R.CTARED AS COD_CONTABIL,
	PLA.DESCTA AS DESCR_CONTABIL,
	R.CODCCU AS COD_CUSTO, ---Código centro de custo
	CCU.DESCCU AS DESCR_CUSTO, ---Descrição centro de custo
	S.QTDSOL AS QTDA_SOLICITADA, ---Quantidade Solicitada
	COALESCE(S.OBSSOL,'SEM OBSERVAÇÃO') AS OBSERVACAO_SOLICITACAO, ----Observação da solicitação
	TO_CHAR(S.DATSOL,'DD/MM/YYYY')  AS DATA_SOLICITACAO, ---Data da solicitação 
	COALESCE(TO_CHAR(OC.DATEMI,'DD/MM/YYYY'),'00/00/0000') AS DATA_EMISSAO_OCP, ---Data emissão da ordem de compra 
	COALESCE(TO_CHAR(S.DATPRV, 'DD/MM/YYYY'),'00/00/0000')  AS DATA_PREV_ENTREGA_SOLICITACAO,
	COALESCE(TO_CHAR(OCP.DATENT, 'DD/MM/YYYY'),'00/00/0000')  AS PREV_ENTREGA_SERVICO_PRODUTO,
	COALESCE(S.NUMCOT,0) AS NUM_COTACAO,---número da cotação
	COALESCE(OC.VLRORI,0) AS VALOR_ORDEM_COMPRA, ---Valor ordem de compra
	COALESCE(OCP.QTDORI,0) AS QTDA_ORDEM_COMPRA, ---quantidade item da ordem de compra
	COALESCE(OCP.VLRORI,0) AS VALOR_ITEM_ORDEM_COMPRA, ---Valor item da ordem de compra
	COALESCE(OC.NUMOCP,0) AS NUM_ORDEM_DE_COMP, ---Número da Ordem de Compra
	COALESCE(N.CODFOR,0) AS COD_FORNECEDOR_NOTA,
	COALESCE(FORN.APEFOR,'0') AS NOME_FANTASIA_FORNECEDOR,
	COALESCE(N.NUMNFC,0) AS NUM_NOTA_FISCAL,
	COALESCE(TO_CHAR(N.DATENT,'DD/MM/YYYY'),'00/00/0000') AS DATA_ENTRADA_NFE, 
	COALESCE(TO_CHAR(T.VCTORI,'DD/MM/YYYY'),'00/00/0000') AS DATA_VENCIMENTO_TITULO,
	COALESCE(TO_CHAR(T.ULTPGT,'DD/MM/YYYY'),'00/00/0000') AS SITUACAO_TITULO,
	CASE 
		WHEN OC.PRCOCP = 1 THEN 'Digitada'
		WHEN OC.PRCOCP = 3 THEN 'Via Cotacao'
		WHEN OC.PRCOCP = 9 THEN 'Via Solicitacao de Compra'
		WHEN OC.PRCOCP = 17 THEN 'Via Contrato de Compra'
		ELSE 'Ainda não foi gerado ordem de compra'
	END AS PRODECENCIA_ORDEM_COMPRA
FROM
		SAPIENS_PROD.E405SOL S
	INNER JOIN SAPIENS_PROD.E405RAT R ON
		R.CODEMP = S.CODEMP
		AND R.NUMSOL = S.NUMSOL
		AND R.SEQSOL = S.SEQSOL
	INNER JOIN SAPIENS_PROD.E070FIL FIL ON
		FIL.CODEMP = S.CODEMP
		AND FIL.CODFIL = S.FILSOL
	LEFT JOIN SAPIENS_PROD.R999USU USOL ON
		USOL.CODUSU = S.USUSOL
	LEFT JOIN SAPIENS_PROD.E410LCO L ON
		L.CODEMP = S.CODEMP
		AND L.NUMCOT = S.NUMCOT
		AND L.FILOCP = S.FILSOL
	LEFT JOIN SAPIENS_PROD.E420OCP OC ON
		OC.CODEMP = L.CODEMP
		AND OC.NUMOCP = L.NUMOCP
		AND OC.CODFIL = L.FILOCP
	LEFT JOIN SAPIENS_PROD.E420IPO OCP ON
		OCP.CODEMP = OC.CODEMP
		AND OCP.CODFIL = OC.CODFIL
		AND OCP.NUMOCP = OC.NUMOCP
		AND ocp.CODPRO = S.CODPRO
		AND OCP.CODDER = S.CODDER 
	LEFT JOIN SAPIENS_PROD.E044CCU CCU ON
		CCU.CODEMP = R.CODEMP 
		AND CCU.CODCCU = R.CODCCU
	LEFT JOIN SAPIENS_PROD.E045PLA PLA ON
		PLA.CODEMP = R.CODEMP 
		AND PLA.CTARED = R.CTARED 
	LEFT JOIN SAPIENS_PROD.E075DER P ON
		P.CODEMP = S.CODEMP 
		AND P.CODPRO = S.CODPRO 
		AND P.CODDER = S.CODDER
	LEFT JOIN SAPIENS_PROD.E012FAM FAM ON
		FAM.CODEMP = S.CODEMP 
		AND FAM.CODFAM = S.CODFAM
	LEFT JOIN SAPIENS_PROD.E440IPC NP ON
		NP.CODEMP = OC.CODEMP 
		AND NP.CODFIL = OC.CODFIL 
		AND NP.CODFOR = OC.CODFOR 
		AND NP.NUMOCP = OC.NUMOCP
	LEFT JOIN SAPIENS_PROD.E440NFC N ON 
		N.CODEMP = NP.CODEMP 
		AND N.CODFIL = NP.CODFIL 
		AND N.CODFOR = NP.CODFOR 
		AND N.NUMNFC = NP.NUMNFC
		AND N.CODSNF = NP.CODSNF 
	LEFT JOIN SAPIENS_PROD.E501TCP T ON
		T.CODEMP = N.CODEMP 
		AND T.CODFIL = N.CODFIL 
		AND T.NUMNFC = N.NUMNFC 
		AND T.CODFOR = N.CODFOR 
		AND T.SNFNFC = N.CODSNF 
	LEFT JOIN SAPIENS_PROD.E095FOR FORN ON
		FORN.CODFOR = N.CODFOR
	WHERE 
		S.CODEMP IN (2,5)
		AND S.PROSER = 'P'
		AND S.DATSOL BETWEEN SYSDATE - 365 AND SYSDATE

UNION ALL

	SELECT DISTINCT 
	S.PROSER AS PRODUTO_OU_SERVICO,
	CASE 
		WHEN S.TIPCPR = 'D' THEN 'Compra Direta'
		WHEN S.TIPCPR = 'L' THEN 'Licitação'
	END AS TIPO_COMPRA,
	CASE 
		WHEN S.SITSOL = 0 THEN 'Digitada'
		WHEN S.SITSOL = 1 THEN 'Cotação'
		WHEN S.SITSOL = 2 THEN 'Ordem de Compra'
		WHEN S.SITSOL = 3 THEN 'Finalizada'
		WHEN S.SITSOL = 9 THEN 'Cancelada'
	END AS SITUACAO_SOLICITACAO,
	S.CODEMP AS EMPRESA,
	S.FILSOL AS FILIAL_ERP, ---filial da solicitação
	FIL.USU_UNINEG AS FILIAL_LINX,
	S.USUSOL AS COD_USU_SOLIC, ---código geração da solicitação
	USOL.NOMUSU AS USUARIO_SOLICITACAO, ----nome do usuário da solicitação
	S.NUMSOL AS NUM_SILICITACAO, ---Número solicitação
	S.CODFAM AS FAM_PRODUTO_SERVICO, ---Código da família do produto
	FAM.DESFAM AS DESCR_FAMILIA_PRODUTO_SERVICO, ----Descrição da família
	S.CODSER AS PRODUTO_SERVICO,
	S.SEQSOL AS SEQ,
	S.CPLPRO AS DESCRICAO_SERVICO_PRODUTO, ----Descrição do Produto
	' ',
	' ', 
	R.CTARED AS COD_CONTABIL,
	PLA.DESCTA AS DESCR_CONTABIL,
	R.CODCCU AS COD_CUSTO, ---Código centro de custo
	CCU.DESCCU AS DESCR_CUSTO, ---Descrição centro de custo
	S.QTDSOL AS QTDA_SOLICITADA, ---Quantidade Solicitada
	COALESCE(S.OBSSOL,'SEM OBSERVAÇÃO') AS OBSERVACAO_SOLICITACAO, ----Observação da solicitação
	TO_CHAR(S.DATSOL,'DD/MM/YYYY')  AS DATA_SOLICITACAO, ---Data da solicitação 
	COALESCE(TO_CHAR(OC.DATEMI,'DD/MM/YYYY'),'00/00/0000') AS DATA_EMISSAO_OCP, ---Data emissão da ordem de compra 
	COALESCE(TO_CHAR(S.DATPRV, 'DD/MM/YYYY'),'00/00/0000')  AS DATA_PREV_ENTREGA_SOLICITACAO,
	COALESCE(TO_CHAR(OCS.DATENT, 'DD/MM/YYYY'),'00/00/0000')  AS PREV_ENTREGA_SERVICO_PRODUTO,
	COALESCE(S.NUMCOT,0) AS NUM_COTACAO,---número da cotação
	COALESCE(OC.VLRORI,0) AS VALOR_ORDEM_COMPRA, ---Valor ordem de compra
	COALESCE(OCS.QTDORI,0) AS QTDA_ORDEM_COMPRA, ---quantidade item da ordem de compra
	COALESCE(OCS.VLRORI,0) AS VALOR_ITEM_ORDEM_COMPRA, ---Valor item da ordem de compra
	COALESCE(OC.NUMOCP,0) AS NUM_ORDEM_DE_COMP, ---Número da Ordem de Compra
	COALESCE(N.CODFOR,0) AS COD_FORNECEDOR_NOTA,
	COALESCE(FORN.APEFOR,'0') AS NOME_FANTASIA_FORNECEDOR,
	COALESCE(N.NUMNFC,0) AS NUM_NOTA_FISCAL,
	COALESCE(TO_CHAR(N.DATENT,'DD/MM/YYYY'),'00/00/0000') AS DATA_ENTRADA_NFE, 
	COALESCE(TO_CHAR(T.VCTORI,'DD/MM/YYYY'),'00/00/0000') AS DATA_VENCIMENTO_TITULO,
	COALESCE(TO_CHAR(T.ULTPGT,'DD/MM/YYYY'),'00/00/0000') AS SITUACAO_TITULO,
	CASE 
		WHEN OC.PRCOCP = 1 THEN 'Digitada'
		WHEN OC.PRCOCP = 3 THEN 'Via Cotacao'
		WHEN OC.PRCOCP = 9 THEN 'Via Solicitacao de Compra'
		WHEN OC.PRCOCP = 17 THEN 'Via Contrato de Compra'
		ELSE 'Ainda não foi gerado ordem de compra'
	END AS PRODECENCIA_ORDEM_COMPRA
FROM
	SAPIENS_PROD.E405SOL S
INNER JOIN SAPIENS_PROD.E405RAT R ON
	R.CODEMP = S.CODEMP
	AND R.NUMSOL = S.NUMSOL
	AND R.SEQSOL = S.SEQSOL
INNER JOIN SAPIENS_PROD.E070FIL FIL ON
	FIL.CODEMP = S.CODEMP
	AND FIL.CODFIL = S.FILSOL
LEFT JOIN SAPIENS_PROD.R999USU USOL ON
	USOL.CODUSU = S.USUSOL
LEFT JOIN SAPIENS_PROD.E410LCO L ON
	L.CODEMP = S.CODEMP
	AND L.NUMCOT = S.NUMCOT
	AND L.FILOCP = S.FILSOL
LEFT JOIN SAPIENS_PROD.E420OCP OC ON
	OC.CODEMP = L.CODEMP
	AND OC.NUMOCP = L.NUMOCP
	AND OC.CODFIL = L.FILOCP
LEFT JOIN SAPIENS_PROD.E420ISO OCS ON
	OCS.CODEMP = OC.CODEMP
	AND OCS.CODFIL = OC.CODFIL
	AND OCS.NUMOCP = OC.NUMOCP
	AND OCS.SEQISO = S.SEQSOL
LEFT JOIN SAPIENS_PROD.E044CCU CCU ON
	CCU.CODEMP = R.CODEMP 
	AND CCU.CODCCU = R.CODCCU
LEFT JOIN SAPIENS_PROD.E045PLA PLA ON
	PLA.CODEMP = R.CODEMP 
	AND PLA.CTARED = R.CTARED 
LEFT JOIN SAPIENS_PROD.E080SER SER ON
	SER.CODEMP = OCS.CODEMP 
	AND SER.CODSER = OCS.CODSER 
LEFT JOIN SAPIENS_PROD.E012FAM FAM ON
	FAM.CODEMP = S.CODEMP 
	AND FAM.CODFAM = S.CODFAM
LEFT JOIN SAPIENS_PROD.E440ISC NS ON 
	NS.CODEMP = OC.CODEMP 
	AND NS.CODFIL = OC.CODFIL 
	AND NS.CODFOR = OC.CODFOR 
	AND NS.NUMOCP = OC.NUMOCP 
LEFT JOIN SAPIENS_PROD.E440NFC N ON 
	N.CODEMP = NS.CODEMP 
	AND N.CODFIL = NS.CODFIL 
	AND N.CODFOR = NS.CODFOR  
	AND N.NUMNFC = NS.NUMNFC 
	AND N.CODSNF = NS.CODSNF 
LEFT JOIN SAPIENS_PROD.E501TCP T ON
	T.CODEMP = N.CODEMP 
	AND T.CODFIL = N.CODFIL 
	AND T.NUMNFC = N.NUMNFC 
	AND T.CODFOR = N.CODFOR 
	AND T.SNFNFC = N.CODSNF
LEFT JOIN SAPIENS_PROD.E095FOR FORN ON
	FORN.CODFOR = N.CODFOR
WHERE 
	S.CODEMP IN (2,5)
	AND S.PROSER = 'S'
	AND S.DATSOL BETWEEN SYSDATE - 365 AND SYSDATE
