WITH PARAMS AS (
SELECT
	TO_DATE('REPLACE_START_DATE', 'yyyy-mm-dd') AS DT_INI_VCT,
	TO_DATE('REPLACE_END_DATE', 'yyyy-mm-dd') AS DT_FIM_VCT
FROM
	DUAL
)
SELECT
	'CONTAS_RECEBER' AS TIPO,
	TR.CODEMP AS EMPRESA,
	TR.CODFIL AS FILIAAL_EPR,
	FIL.USU_UNINEG AS FILIAL_SIST_ORIGEM,
	FIL.SIGFIL AS NOME_FILIAL,
	TR.DATEMI AS DATA_EMISSAO,
	TR.VCTORI AS VENCIMENTO_ORIGINAL, 
	TR.DATPPT AS DATA_PROVAVEL_PAGT,
	TR.ULTPGT AS ULTIMO_PAGT,
	TR.CODPOR AS PORTADOR,
	P.DESPOR AS DESCRICAO_PORTADOR,
	TR.CODCRT AS CARTEIRA,
	CART.DESCRT AS DESCRICAO_CARTEIRA,
	TR.CODCLI AS COD_CLIENTE,
	C.APECLI AS NOME_FANTASIA_CLIENTE,
	NVL(C.CODGRE, 0) AS GRUPO_EMPRESA,
	NVL(G.NOMGRE, 'Sem Grupo Empresa') AS NOME_GRUPO_EMPRESA,
	TR.NUMNFV AS NOTA,
	TR.NUMTIT AS TITULO,
	TR.CODTPT AS TIPO_TITULO,
	TPT.DESTPT AS DESCRICAO_TIPO_TITULO,
	TR.CODREP AS COD_REPRESENTANTE,
	NVL(TR.NUMCTR, 0) AS NUM_CONTRATO,
	TR.SITTIT AS SITUACAO_TITULO,
	TR.VLRORI AS VALOR_ORIGINAL,
	TR.VLRABE AS VALOR_ABERTO,
	TR.PERMUL AS PERC_MULTA,
	TR.PERJRS AS PERC_JUROS,
	CASE
		WHEN TR.TIPJRS = 'S' THEN 'Simples'
		ELSE 'Composto'
	END AS TIPO_JUROS,
	TR.VLRDSC AS DESCONTO,
	(TR.VLRABE - TR.VLRDSC) AS VALOR_LIQ,
	NVL(N.TNSPRO, '0') AS TRANSACAO_NOTA_PRODUTO,
	NVL(N.TNSSER, '0') AS TRANSACAO_NOTA_SERVICO,
	TNSN.COMNAT AS CFOP_NOTA,
	TNSN.DESTNS AS DESCRICAO_CFOP,
	CASE
		WHEN TNSN.CPRTCF = 'N' THEN 'Comercialização'
		WHEN TNSN.CPRTCF = 'S' THEN 'Consumo Próprio'
		WHEN TNSN.CPRTCF = 'I' THEN 'Imobilizado'
		WHEN TNSN.CPRTCF = 'R' THEN 'Remessas'
		WHEN TNSN.CPRTCF = 'O' THEN 'Retornos'
		WHEN TNSN.CPRTCF = 'T' THEN 'Transferências'
		WHEN TNSN.CPRTCF = 'D' THEN 'Devoluções'
		WHEN TNSN.CPRTCF = 'A' THEN 'Devoluções c/ substituição tributária'
		WHEN TNSN.CPRTCF = 'B' THEN 'Substituição Tributária'
		WHEN TNSN.CPRTCF = 'E' THEN 'Energia Elética'
		WHEN TNSN.CPRTCF = 'C' THEN 'Comunicação'
		WHEN TNSN.CPRTCF = 'F' THEN 'Transporte'
		WHEN TNSN.CPRTCF = 'G' THEN 'Integração'
		WHEN TNSN.CPRTCF = 'V' THEN 'Serviços'
		WHEN TNSN.CPRTCF = 'X' THEN 'Outros'
		ELSE 'Sem NF'
	END AS APLICACAO_OPERACAO,
	TNST.CODTNS AS TRANSACAO_TITULO,
	TNST.DESTNS AS DESCRICAO_TRANSACAO_TITULO
FROM
	SAPIENS_PROD.E301TCR TR
JOIN PARAMS PRT ON
	1 = 1
JOIN SAPIENS_PROD.E001TNS TNST 
    ON
	TR.CODEMP = TNST.CODEMP
	AND TR.CODTNS = TNST.CODTNS
JOIN SAPIENS_PROD.E140NFV N 
    ON
	TR.CODEMP = N.CODEMP
	AND TR.CODFIL = N.CODFIL
	AND TR.CODSNF = N.CODSNF
	AND TR.NUMNFV = N.NUMNFV
JOIN SAPIENS_PROD.E001TNS TNSN 
    ON
	N.CODEMP = TNSN.CODEMP
	AND TNSN.CODTNS = NVL(N.TNSPRO, N.TNSSER)
JOIN SAPIENS_PROD.E085CLI C 
    ON
	TR.CODCLI = C.CODCLI
JOIN SAPIENS_PROD.E002TPT TPT 
    ON
	TR.CODTPT = TPT.CODTPT
JOIN SAPIENS_PROD.E070FIL FIL 
    ON
	TR.CODEMP = FIL.CODEMP
	AND TR.CODFIL = FIL.CODFIL
LEFT JOIN SAPIENS_PROD.E039POR P 
    ON
	TR.CODEMP = P.CODEMP
	AND TR.CODPOR = P.CODPOR
LEFT JOIN SAPIENS_PROD.E033CRT CART 
    ON
	TR.CODCRT = CART.CODCRT
LEFT JOIN SAPIENS_PROD.E069GRE G 
    ON
	C.CODGRE = G.CODGRE
WHERE
	TR.CODEMP IN (2,5)
	AND TR.CODFIL BETWEEN 1 AND 999
	AND TR.SITTIT <> 'CA'
	AND TR.VCTORI >= PRT.DT_INI_VCT
	AND TR.VCTORI < PRT.DT_FIM_VCT
	AND TNST.LISMOD = 'CRE'
UNION ALL
	SELECT 
	'CONTAS_PAGAR' AS TIPO,
	TP.CODEMP AS EMPRESA,
	TP.CODFIL AS FILIAAL_EPR,
	FIL.USU_UNINEG AS FILIAL_SIST_ORIGEM,
	FIL.SIGFIL AS NOME_FILIAL,
	TP.DATEMI AS DATA_EMISSAO,
	TP.VCTORI AS VENCIMENTO_ORIGINAL, 
	TP.DATPPT AS DATA_PROVAVEL_PAGT,
	TP.ULTPGT AS ULTIMO_PAGT,
	TP.CODPOR AS PORTADOR,
	P.DESPOR AS DESCRICAO_PORTADOR,
	TP.CODCRT AS CARTEIRA,
	CART.DESCRT AS DESCRICAO_CARTEIRA,
	TP.CODFOR AS COD_FORNECEDOR,
	F.APEFOR AS NOME_FANTASIA_FORNECEDOR,
	NVL(F.CODGRE, 0) AS GRUPO_EMPRESA,
	NVL(G.NOMGRE, 'Sem Grupo Empresa') AS NOME_GRUPO_EMPRESA,
	TP.NUMNFV AS NOTA,
	TP.NUMTIT AS TITULO,
	TP.CODTPT AS TIPO_TITULO,
	TPT.DESTPT AS DESCRICAO_TIPO_TITULO,
	0,
	NVL(TP.NUMCTR, 0) AS NUM_CONTRATO,
	TP.SITTIT AS SITUACAO_TITULO,
	TP.VLRORI AS VALOR_ORIGINAL,
	TP.VLRABE AS VALOR_ABERTO,
	TP.PERMUL AS PERC_MULTA,
	TP.PERJRS AS PERC_JUROS,
	CASE
		WHEN TP.TIPJRS = 'S' THEN 'Simples'
		ELSE 'Composto'
	END AS TIPO_JUROS,
	TP.VLRDSC AS DESCONTO,
	(TP.VLRABE - TP.VLRDSC) AS VALOR_LIQ,
	NVL(N.TNSPRO, '0') AS TRANSACAO_NOTA_PRODUTO,
	NVL(N.TNSSER, '0') AS TRANSACAO_NOTA_SERVICO,
	TNSN.COMNAT AS CFOP_NOTA,
	TNSN.DESTNS AS DESCRICAO_CFOP,
	CASE
		WHEN TNSN.CPRTCF = 'N' THEN 'Comercialização'
		WHEN TNSN.CPRTCF = 'S' THEN 'Consumo Próprio'
		WHEN TNSN.CPRTCF = 'I' THEN 'Imobilizado'
		WHEN TNSN.CPRTCF = 'R' THEN 'Remessas'
		WHEN TNSN.CPRTCF = 'O' THEN 'Retornos'
		WHEN TNSN.CPRTCF = 'T' THEN 'Transferências'
		WHEN TNSN.CPRTCF = 'D' THEN 'Devoluções'
		WHEN TNSN.CPRTCF = 'A' THEN 'Devoluções c/ substituição tributária'
		WHEN TNSN.CPRTCF = 'B' THEN 'Substituição Tributária'
		WHEN TNSN.CPRTCF = 'E' THEN 'Energia Elética'
		WHEN TNSN.CPRTCF = 'C' THEN 'Comunicação'
		WHEN TNSN.CPRTCF = 'F' THEN 'Transporte'
		WHEN TNSN.CPRTCF = 'G' THEN 'Integração'
		WHEN TNSN.CPRTCF = 'V' THEN 'Serviços'
		WHEN TNSN.CPRTCF = 'X' THEN 'Outros'
		ELSE 'Sem NF'
	END AS APLICACAO_OPERACAO,
	TNST.CODTNS AS TRANSACAO_TITULO,
	TNST.DESTNS AS DESCRICAO_TRANSACAO_TITULO
FROM
	SAPIENS_PROD.E501TCP TP
JOIN PARAMS PRT ON
	1 = 1
LEFT JOIN SAPIENS_PROD.E001TNS TNST 
    ON
	TP.CODEMP = TNST.CODEMP
	AND TP.CODTNS = TNST.CODTNS
LEFT JOIN SAPIENS_PROD.E440NFC N 
    ON
	TP.CODEMP = N.CODEMP
	AND TP.CODFIL = N.CODFIL
	AND TP.CODFOR = N.CODFOR
	AND TP.NUMNFC = N.NUMNFC
	AND TP.SNFNFC = N.CODSNF
LEFT JOIN SAPIENS_PROD.E001TNS TNSN 
    ON
	N.CODEMP = TNSN.CODEMP
	AND TNSN.CODTNS = NVL(N.TNSPRO, N.TNSSER)
LEFT JOIN SAPIENS_PROD.E095FOR F 
    ON
	TP.CODFOR = F.CODFOR
LEFT JOIN SAPIENS_PROD.E002TPT TPT 
    ON
	TP.CODTPT = TPT.CODTPT
LEFT JOIN SAPIENS_PROD.E070FIL FIL 
    ON
	TP.CODEMP = FIL.CODEMP
	AND TP.CODFIL = FIL.CODFIL
LEFT JOIN SAPIENS_PROD.E039POR P 
    ON
	TP.CODEMP = P.CODEMP
	AND TP.CODPOR = P.CODPOR
LEFT JOIN SAPIENS_PROD.E033CRT CART 
    ON
	TP.CODCRT = CART.CODCRT
LEFT JOIN SAPIENS_PROD.E069GRE G 
    ON
	F.CODGRE = G.CODGRE
WHERE
	TP.CODEMP IN (2,5)
	AND TP.CODFIL BETWEEN 1 AND 999
	AND TP.SITTIT <> 'CA'
	AND TP.VCTORI >= PRT.DT_INI_VCT
	AND TP.VCTORI < PRT.DT_FIM_VCT
	AND TNST.LISMOD = 'CPE'
ORDER BY
	1,
	2,
	3,
	5;