------------------ Balancete contábil ------------------
SELECT 
	s.CODEMP AS EMPRESA,
	TO_CHAR(TRUNC(s.MESANO, 'MM'), 'YYYY-MM-DD') AS DATA_LANCAMENTO,
	s.CODFIL AS FIL_ERP,
	f.USU_UNINEG AS FIL_SIS_ORIGEM,
	f.SIGFIL AS NOME_FILIAL,
	p.GRUCTA AS GRUPO,
	CASE
		WHEN p.DEFGRU = 'A' THEN 'Ativo'
		WHEN p.DEFGRU = 'P' THEN 'Passivo'
		WHEN p.DEFGRU = 'D' THEN 'Despesas'
		WHEN p.DEFGRU = 'R' THEN 'Receitas'
		WHEN p.DEFGRU = 'X' THEN 'Ambas(Resultado)'
		WHEN p.DEFGRU = 'M' THEN 'Receitas Financeiras'
		WHEN p.DEFGRU = 'N' THEN 'Despesas Financeiras'
		WHEN p.DEFGRU = 'U' THEN 'Conta Auxiliar'
		WHEN p.DEFGRU = 'L' THEN 'Patrimônio Líquido'
		WHEN p.DEFGRU = 'V' THEN 'Custo de Venda'
		WHEN p.DEFGRU = 'C' THEN 'Custo de Produção'
		WHEN p.DEFGRU = 'S' THEN 'Custo de Ordem Dedutora'
		WHEN p.DEFGRU = 'E' THEN 'Custo de Ordem Credora'
		WHEN p.DEFGRU = 'O' THEN 'Outras'
		WHEN p.DEFGRU = 'T' THEN 'Contas de Compensação'
	END AS DESCR_GRUPO,
	p.CLACTA AS CLASSIFICACAO,
	p.MSKGCC AS MASCARA,
	s.CTARED AS CONTA,
	p.DESCTA AS DESCR_CONTA,
	SUM(s.SALMES) - SUM(s.DEBMES) + SUM(s.CREMES) SALANT,
	COALESCE(SUM(s.DEBMES), 0) DEBMES,
	COALESCE(SUM(s.CREMES), 0) CREMES,
	SUM(s.SALMES) SALMES,
	SUM(s.DEBMES) - SUM(s.CREMES) MOVIMENTO
FROM
	SAPIENS_PROD.E070FIL f
INNER JOIN SAPIENS_PROD.E650SAL s ON
	s.CODEMP = f.CODEMP
	AND s.CODFIL = f.CODFIL
	AND s.MESANO >= TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD')
	AND s.MESANO < TO_DATE('REPLACE_END_DATE', 'YYYY-MM-DD')
INNER JOIN SAPIENS_PROD.E045PLA p ON 
	s.CODEMP = p.CODEMP
	AND S.CTARED = p.CTARED
	AND p.NIVCTA = 5
WHERE
	f.CODEMP IN (2, 5)
GROUP BY
	s.CODEMP,
	s.CODFIL,
	f.USU_UNINEG,
	f.SIGFIL,
	p.GRUCTA,
	p.DEFGRU,
	s.CTARED,
	p.DESCTA,
	s.MESANO,
	p.CLACTA,
	p.MSKGCC
HAVING 
	COALESCE(SUM(s.SALMES), 0) <> 0
    OR COALESCE(SUM(s.DEBMES), 0) <> 0
    OR COALESCE(SUM(s.CREMES), 0) <> 0
ORDER BY
	1,
	2,
	3,
	6,
	10