WITH EXTRATO AS (
  SELECT
    DATEXT AS DATMOV,
    COUNT(*) AS QTD_EXTR,
    SUM(VLREXT) AS VALOR_EXTR
  FROM SAPIENS_PROD.E605EXT
  WHERE CODEMP = 5
    AND NUMCCO = '65764'
    AND DECEXT = 'C'
     AND DATEXT >= TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD')
    AND DATEXT < TO_DATE('REPLACE_END_DATE', 'YYYY-MM-DD')
  GROUP BY DATEXT
),
MOVIMENTO AS (
  SELECT
    DATMOV AS DATMOV,
    COUNT(*) AS QTD_MOV,
    SUM(
      CASE
        WHEN DEBCRE = 'D' THEN VLRMOV * -1
        ELSE VLRMOV
      END
    ) AS VALOR_MOV
  FROM SAPIENS_PROD.E600MCC
  WHERE CODEMP = 5
    AND NUMCCO = '65764TRANSIT'
    AND CODTNS <> '92657'
    AND SITMCC = 'A'
     AND DATMOV >= TO_DATE('REPLACE_START_DATE', 'YYYY-MM-DD')
    AND DATMOV < TO_DATE('REPLACE_END_DATE', 'YYYY-MM-DD')
  GROUP BY DATMOV
),
POSICAO_DIARIA AS (
  SELECT
    COALESCE(e.DATMOV, m.DATMOV) AS DATMOV,
    NVL(e.QTD_EXTR, 0)   AS QTD_EXTR,
    NVL(e.VALOR_EXTR, 0) AS VALOR_EXTR,
    NVL(m.QTD_MOV, 0)    AS QTD_MOV,
    NVL(m.VALOR_MOV, 0)  AS VALOR_MOV,
    NVL(e.VALOR_EXTR, 0) - NVL(m.VALOR_MOV, 0) AS DIFERENCA
  FROM EXTRATO e
  FULL OUTER JOIN MOVIMENTO m
    ON e.DATMOV = m.DATMOV
),
-- Identifica, para cada linha, o próximo dia com DIFERENCA > 0
BLOCOS AS (
  SELECT
    DATMOV,
    QTD_EXTR,
    VALOR_EXTR,
    QTD_MOV,
    VALOR_MOV,
    DIFERENCA,
    MIN(CASE WHEN DIFERENCA > 0 THEN DATMOV END)
      OVER (ORDER BY DATMOV
            ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS DIA_POSITIVO
  FROM POSICAO_DIARIA
),
-- Agrega somente os dias que "fluem" para um DIA_POSITIVO (negativos + o próprio positivo)
AGREGADO_BLOCOS AS (
  SELECT
    DIA_POSITIVO       AS DATMOV,
    SUM(QTD_EXTR)      AS QTD_EXTR,
    SUM(VALOR_EXTR)    AS VALOR_EXTR,
    SUM(QTD_MOV)       AS QTD_MOV,
    SUM(VALOR_MOV)     AS VALOR_MOV,
    SUM(DIFERENCA)     AS DIFERENCA
  FROM BLOCOS
  WHERE DIA_POSITIVO IS NOT NULL
  GROUP BY DIA_POSITIVO
),
-- Agora juntamos:
-- 1) os dias que NÃO participam de bloco (ou seja, onde DIFERENCA = 0 E não são igual a nenhum DIA_POSITIVO)
-- 2) os dias agregados dos blocos (AGREGADO_BLOCOS)
DIAS_NAO_AGREGADOS AS (
  SELECT
    p.DATMOV,
    p.QTD_EXTR,
    p.VALOR_EXTR,
    p.QTD_MOV,
    p.VALOR_MOV,
    p.DIFERENCA
  FROM POSICAO_DIARIA p
  LEFT JOIN (
    SELECT DISTINCT DIA_POSITIVO
    FROM BLOCOS
    WHERE DIA_POSITIVO IS NOT NULL
  ) b
    ON p.DATMOV = b.DIA_POSITIVO
  WHERE
      p.DIFERENCA = 0           -- dias que já estavam "zerados"
  AND b.DIA_POSITIVO IS NULL    -- e que não são um dia positivo de bloco
),
RESULTADO_SEM_TOTAL AS (
  SELECT
    DATMOV,
    QTD_EXTR,
    VALOR_EXTR,
    QTD_MOV,
    VALOR_MOV,
    DIFERENCA
  FROM AGREGADO_BLOCOS
  UNION ALL
  SELECT
    DATMOV,
    QTD_EXTR,
    VALOR_EXTR,
    QTD_MOV,
    VALOR_MOV,
    DIFERENCA
  FROM DIAS_NAO_AGREGADOS
)
SELECT
  DATMOV AS DATDOC,
  QTD_EXTR,
  VALOR_EXTR,
  QTD_MOV,
  VALOR_MOV,
  DIFERENCA
FROM RESULTADO_SEM_TOTAL
ORDER BY DATMOV