SELECT
	f.NUMCAD,
	fil.NOMFIL AS NOME_FILIAL,
	fil.CODEST AS UF,
	TO_CHAR(f.DATADM,'dd/mm/yyyy') AS DATA_ADMISSAO, ---informação para calcular tempo de empresa
	fc.DURCON AS DURACAO_CONTRATO, ---Duração Contrato de Experiência
	hcc.CODCCU AS COD_CentroCusto,
	cc.NOMCCU AS NOME_CentroCusto,
	hl.NUMLOC AS NUM_LOCAL,
	l.NOMLOC AS NOME_LOCAL,
	TO_CHAR(hs.DATALT, 'dd/mm/yyyy') AS DATA_ALTERACAO_SALARIAL,
	hs.CODMOT AS MOTIVO_PROM_SALARIAL,
	mp.NOMMOT AS NOME_MOTIVO_PROM,
	f.CODCAR AS CARGO,
	c.TITCAR AS NOME_CARGO,
	f.TIPSEX AS SEXO,
	COALESCE (f.RACCOR, 0) AS COD_RACA,
	COALESCE (ra.DESETN, 'Sem definição de raça') AS NOME_RACA,
	f.GRAINS AS COD_GRADUCACAO,
	gi.DESGRA AS GRADUACAO,
	TO_CHAR(f.DATNAS,'dd/mm/yyyy') AS DATA_NASCIMENTO,
	CASE
		WHEN f.DEFFIS = 'N' THEN 'N'
		WHEN f.DEFFIS = 'S' THEN 'S'
		WHEN f.DEFFIS = ' ' THEN 'Sem Definição'
	END	AS DEFICIENTE,
	f.CODDEF AS COD_DEFICIENTE,
	CASE
		WHEN f.CODDEF = 01 THEN 'Deficiencia Fisica'
		WHEN f.CODDEF = 02 THEN 'Dificiencia Auditiva'
		WHEN f.CODDEF = 03 THEN 'Dificiencia Visual'
		WHEN f.CODDEF = 04 THEN 'Deficiencia Mental'
		WHEN f.CODDEF = 05 THEN 'Dificiencia Multipla'
	  ELSE 'Sem Deficiência'
	END AS TIPO_DEFICIENCIA,
	COALESCE (TO_CHAR(f.DATAFA,'dd/mm/yyyy'), '00/00/0000' ) AS DATA_DEMISSAO,
	COALESCE (rc.DESDEM, '0') AS CAUSA_DEMISSAO,
	f.SITAFA AS COD_SITACAO,
	s.DESSIT AS SITUACAO
FROM
	(VETORH_PROD.R034FUN f LEFT OUTER JOIN VETORH_PROD.R022DEF d
				 			ON d.CODDEF = f.CODDEF
			   LEFT OUTER JOIN VETORH_PROD.R042RCM  r
			   				ON r.NUMEMP = f.NUMEMP
			   			   AND r.TIPCOL = f.TIPCOL
			   			   AND r.NUMCAD = f.NUMCAD
			   LEFT OUTER JOIN VETORH_PROD.R042CAU rc
			        		ON rc.CAUDEM = r.CAUDEM
			   LEFT OUTER JOIN VETORH_PROD.R034CPL fc
			   				ON fc.NUMEMP = f.NUMEMP
			   			   AND fc.TIPCOL = f.TIPCOL
			   			   AND fc.NUMCAD = f.NUMCAD
			   LEFT OUTER JOIN VETORH_PROD.R010ETN ra
			                ON f.RACCOR = ra.CODETN),
	VETORH_PROD.R024CAR c,
	VETORH_PROD.R022GRA gi,
	VETORH_PROD.R038HSA hs,
	VETORH_PROD.R038HCC hcc,
	VETORH_PROD.R038HLO hl,
	VETORH_PROD.R076MOT mp,
	VETORH_PROD.R018CCU cc,
	VETORH_PROD.R016ORN l,
	VETORH_PROD.R030FIL fil,
	VETORH_PROD.R010SIT s
WHERE c.ESTCAR = f.ESTCAR
AND c.CODCAR = f.CODCAR
AND f.GRAINS = gi.GRAINS
AND hs.NUMEMP = f.NUMEMP
AND hs.TIPCOL = f.TIPCOL
AND hs.NUMCAD = f.NUMCAD
AND mp.CODMOT = hs.CODMOT
AND hcc.NUMEMP = f.NUMEMP
AND hcc.TIPCOL = f.TIPCOL
AND hcc.NUMCAD = f.NUMCAD
AND hl.NUMEMP = f.NUMEMP
AND hl.TIPCOL = f.TIPCOL
AND hl.NUMCAD = f.NUMCAD
AND cc.NUMEMP = f.NUMEMP
AND cc.CODCCU = f.CODCCU
AND l.TABORG = f.TABORG
AND l.NUMLOC = f.NUMLOC
AND fil.NUMEMP = f.NUMEMP
AND fil.CODFIL = f.CODFIL
AND s.CODSIT = f.SITAFA
AND TO_DATE(TO_CHAR(hs.DATALT, 'dd/mm/yyyy'), 'dd/mm/yyyy') = (SELECT MAX(hs1.DATALT)   FROM VETORH_PROD.R038HSA hs1
															    WHERE hs1.NUMEMP = hs.NUMEMP
															      AND hs1.TIPCOL = hs.TIPCOL
															      AND hs1.NUMCAD = hs.NUMCAD)
AND TO_DATE(TO_CHAR(hcc.DATALT, 'dd/mm/yyyy'), 'dd/mm/yyyy') = (SELECT MAX(hcc1.DATALT) FROM VETORH_PROD.R038HCC hcc1
															    WHERE hcc1.NUMEMP = hcc.NUMEMP
															      AND hcc1.TIPCOL = hcc.TIPCOL
															      AND hcc1.NUMCAD = hcc.NUMCAD)
AND TO_DATE(TO_CHAR(hl.DATALT, 'dd/mm/yyyy'), 'dd/mm/yyyy') = (SELECT MAX(hl1.DATALT) FROM VETORH_PROD.R038HLO hl1
										   				      WHERE hl1.NUMEMP = hl.NUMEMP
															    AND hl1.TIPCOL = hl.TIPCOL
															    AND hl1.NUMCAD = hl.NUMCAD)
AND f.NUMEMP = 5
AND f.TIPCOL = 1
